### ISSUE TITLE
[Feature]: Optional GPU support

### ISSUE THREAD

**Issue by andypotato** [Gourieff/sd-webui-reactor#106]
### Feature description

First of all, I am aware this has already been discussed. The consensus seems to be that GPU does not offer any speed benefits and eventually makes things slower due to a number of reasons.

I would still want to give this another shot, as I believe there are situations where GPU support will offer benefits:

If you are using SD on GPU compute providers like Runpod or Colab, the GPU will be fast, but the CPU will be really (really) slow, to a point that it's almost unusable. Just for comparison:

- Locally I am running an Intel i5 / 12500 paired with a 4060ti. Creating a batch of 4 images (768x512 resolution) via txt2img and swapping the faces takes about 22 seconds (14 seconds to create the 4 images, 8 seconds to run face swap on all of them)
- Running the exact same setup on Runpod using a 3090ti, the same process takes about one minute (just 5-6 seconds to create 4 images, almost a minute to run face swap)

So you can see this is a huge difference.

I'm currently reviewing the code and wondering if you could point me to the right place, so I can try and enable GPU support. I will test this on Runpod and report back my numbers.

Thank you for your time and efforts!

**Comment by Gourieff** [comment]
That's interesting

You can try to change the next lines:

https://github.com/Gourieff/sd-webui-reactor/blob/main/requirements.txt#L3
```
onnxruntime-gpu>=1.15.0
```

https://github.com/Gourieff/sd-webui-reactor/blob/main/scripts/reactor_swapper.py#L23

```python
providers = ["CUDAExecutionProvider"]
```

https://github.com/Gourieff/sd-webui-reactor/blob/main/scripts/reactor_swapper.py#L198

```python
face_analyser = getAnalysisModel()
```

This is rather raw variant for GPU support, but must work (the only things is that det_size will be forcefully attached to the analysis model, but it's not a big issue for most cases, it will be fine for tests)

And also don't forget to remove onnxruntime folders from venv site-packages when you test it locally and let ReActor to install ort-gpu

**Comment by andypotato** [comment]
Hi, thanks for the feedback. I'll try the modifications you suggested!

Meanwhile, here is the result of a test I ran using a similar extension
https://glucauze.github.io/sd-webui-faceswaplab/

_All tests are generating a batch of 4 images via txt2img @ 768x512 resulution_

**Using i5 12500, RTX 4060ti, CPUExecutionProvider**
Generating images 14s, FaceSwap 16s, Total 30s

**Using i5 1200, RTX 4060ti, CUDAExecutionProvider**
Generating images 14s, FaceSwap 10s, Total 24s

**Using Runpod 3090ti, 8vcpu, CPUExecutionProvider**
Generating images 6s, Faceswap 52s, Total 58s

**Using Runpod 3090ti, 8vcpu, CUDAExecutionProvider**
Generating images 5s, Faceswap 6s, Total 11s

So my initial theory of there being significant benefits at higher batch sizes and slow cloud CPUs seems to be confirmed.

I'll now try doing the same with Reactor and report back!

**Comment by andypotato** [comment]
So I tried your extension on both my local machine and a Runpod instance. Here's the comparison:

_Again, all tests are creating a txt2img batch of 4 images @786x512 resolution_

**Local machine (i5 12500, RTX 4060ti) CPUExecutionProvider:**
Creating images: 12.2s
Creating images + Face swap: 28s

**Local machine (i5 12500, RTX 4060ti) CUDAExecutionProvider:**
Creating images: 12.2s
Creating images + Face swap: 23.5s

**Runpod (8vcpu, RTX 3090ti) CPUExecutionProvider:**
Creating images: 5.4s
Creating images + Face swap: 48.7s

**Runpod (8vcpu, RTX 3090ti) CUDAExecutionProvider:**
Creating images: 5.4s
Creating images + Face swap: 20.7s

So it's obvious there is a significant performance increase using the CUDAExecutionProvider in this specific situation.

**Comment by Gourieff** [comment]
Wow... You're hero, my friend!
Very interesting result
This makes sense, I think a new branch with CUDAExecutionProvider support will be a good solution in such case

**Comment by andypotato** [comment]
I am also having a look at the [code in this project](https://glucauze.github.io/sd-webui-faceswaplab/). It has GPU support and during my testing, this code worked even faster. Maybe they added some additional caching or optimizations.

**Comment by Gourieff** [comment]
@andypotato yeah, they use caching and also there was a very little difference while getting a face with analyzer 
So, I published separate repository for GPU version, it will be great if you can test it and share results
https://github.com/Gourieff/sd-webui-reactor-force

**Comment by andypotato** [comment]
Sure, I'll find some time next week and try it. Awesome work!
