### ISSUE TITLE
[Feature]: Please consider moving the face restore model folder to comfyUI/models/facerestore_models

### ISSUE THREAD

**Issue by basvdelsen** [Gourieff/sd-webui-reactor#109]
### Feature description

I have other face restore custom nodes installed that use the same face restore models but they are installed in comfyui/models/facerestore_models. Having to copy them to comfyui/custom_nodes/comfyui-reactor-node/models/facerestore_models takes up unnecessary space. Thanks.

**Comment by Gourieff** [comment]
You probably wanted to add an issue topic here https://github.com/Gourieff/comfyui-reactor-node/issues
And this topic already exists
This the answer: https://github.com/Gourieff/comfyui-reactor-node/issues/31#issuecomment-1724898710
I will fix it soon

**Comment by basvdelsen** [comment]
Okay thank you, I'll close this
