### ISSUE TITLE
Installation should stop, if no venv directory is present.

### ISSUE THREAD

**Issue by MR-444** [Gourieff/sd-webui-reactor#115]
### Feature description

I wrote in your announcement page already, and your expansion is NOT installable, if the venv directory in the stable diffusion is missing. (This happens if you install SD with the autoinstaller without root privileges, I think.)
So a check and warning message should be in the installation process. 
I only found this issue, because you always mentioned that there is a venv directory, but you did not say where.

**Comment by Gourieff** [comment]
VENV is only one of several variants of organizing python's enclosure
You can even install everything directly in your OS (without any environments) and it will work if you know what you do
If you cannot make this work - this means that you do smth wrong
More than 1000 users every day install this extension
This extension is not a standalone app, so its installation depends on how you tune your SD WebUI, if you do everything according to the instructions (WebUI instruction, this extension instruction) - everything will work with no errors

**Comment by Gourieff** [comment]
The installation of this extension does not depend on the presence of VENV
VENV (virtual environment) is one of the most simple ways to make isolated virtual enclosure to run a python's application
Almost all of current WebUI's (e.g. A1111, SD.Next) use VENV or python's embedded enclosure by default
Read all the instructions carefully and you will succeed
