### ISSUE TITLE
The Roop extension in Stable Diffusion is not loading. I think it is because of the file that is missing: the file for inswapper_128.onnx  Because the command prompt gives this error: Most likely because of that error: 'NoneType' object has no attribute  How can I fix it? Because the file is no longer availabe online in Roop description. Thank you.

### ISSUE THREAD

**Issue by justinason** [Gourieff/sd-webui-reactor#117]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

The Roop extension is not loading. I think it is because of the file that is missing: the file for inswapper_128.onnx  Because the command prompt gives this error: Most likely because of that error: 'NoneType' object has no attribute  How can I fix it? Because the file is no longer availabe online in Roop description. Thank you.

### Steps to reproduce the problem

1. I run C:\Users\justi\stable-diffusion-webui\webui-user.bat
2. I go stable diffusion web UI inteface on google chrome.
3. And there is no Roop panel, which has to be displayed on the bottom, as in this video: https://youtu.be/bjGM_fwg9_c?t=142
However it is displayed as installed extension on extension tab.

### Sysinfo

I installed Stable Diffusion and Roop on my computer -  
windows 11 home
DELL
64 bit
32 GB RAM
Nvidia Geforce GTX 970
i7 processor 10700F

### Relevant console log

```Shell
I think it loads normaly in cmd


venv "C:\Users\justi\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Launching Web UI with arguments: --xformers --lowvram
2023-10-04 13:16:41,015 - ControlNet - INFO - ControlNet v1.1.410
ControlNet preprocessor location: C:\Users\justi\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-10-04 13:16:41,147 - ControlNet - INFO - ControlNet v1.1.410
Loading weights [cc6cb27103] from C:\Users\justi\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned-emaonly.ckpt
2023-10-04 13:16:41,900 - ControlNetFastload - INFO - Load Controlnet Fastload Filter on isRemote=None and accessLevel=2
Running on local URL:  http://127.0.0.1:7860


To create a public link, set `share=True` in `launch()`.
Startup time: 12.3s (prepare environment: 3.0s, import torch: 3.6s, import gradio: 1.0s, setup paths: 0.8s, initialize shared: 0.2s, other imports: 0.7s, setup codeformer: 0.1s, load scripts: 2.1s, create ui: 0.4s, gradio launch: 0.3s).
Creating model from config: C:\Users\justi\stable-diffusion-webui\configs\v1-inference.yaml
Applying attention optimization: Doggettx... done.
Model loaded in 7.1s (load weights from disk: 3.1s, create model: 0.4s, apply weights to model: 1.4s, apply half(): 0.7s, calculate empty prompt: 1.6s).
```

### Additional information

Thank you.

**Comment by Gourieff** [comment]
I think you're using sd-webui-roop instead of sd-webui-reactor 
Roop is no longer supported by its developer
To install ReActor just follow the instruction https://github.com/Gourieff/sd-webui-reactor#installation
