### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by moo611** [Gourieff/sd-webui-reactor#122]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

install failed.

### Steps to reproduce the problem

1. Extensions -> Install from URL ->paste "https://github.com/Gourieff/sd-webui-reactor"
2. click install
3. see the message in console log

### Sysinfo

{
    "Platform": "Linux-4.15.0-180-generic-x86_64-with-glibc2.17",
    "Python": "3.8.12",
    "Version": "v1.5.1",
    "Commit": "68f336bd994bed5442ad95bad6b6ad5564a5409a",
    "Script path": "/home/ubuntu/stable-diffusion-webui",
    "Data path": "/home/ubuntu/stable-diffusion-webui",
    "Extensions dir": "/home/ubuntu/stable-diffusion-webui/extensions",
    "Checksum": "e6c0f46e0420cd67a0fab56d69fe24f5ce0ba71c4a97af359bdfbb7559563869",
    "Commandline": [
        "launch.py",
        "--api",
        "--listen",
        "--port",
        "8888",
        "--enable-insecure-extension-access"
    ],
    "Torch env info": {
        "torch_version": "2.0.1+cu118",
        "is_debug_build": "False",
        "cuda_compiled_version": "11.8",
        "gcc_version": "(Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0",
        "clang_version": null,
        "cmake_version": "version 3.27.6",
        "os": "Ubuntu 18.04.4 LTS (x86_64)",
        "libc_version": "glibc-2.27",
        "python_version": "3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0] (64-bit runtime)",
        "python_platform": "Linux-4.15.0-180-generic-x86_64-with-glibc2.17",
        "is_cuda_available": "True",
        "cuda_runtime_version": null,
        "cuda_module_loading": "LAZY",
        "nvidia_driver_version": "470.82.01",
        "nvidia_gpu_models": "GPU 0: Tesla T4",
        "cudnn_version": [
            "Probably one of the following:",
            "/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn.so.8",
            "/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8",
            "/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_adv_train.so.8",
            "/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8",
            "/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8",
            "/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8",
            "/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_ops_train.so.8"
        ],
        "pip_version": "pip3",
        "pip_packages": [
            "numpy==1.23.5",
            "open-clip-torch==2.20.0",
            "pytorch-lightning==1.9.4",
            "torch==2.0.1+cu118",
            "torchdiffeq==0.2.3",
            "torchmetrics==1.2.0",
            "torchsde==0.2.5",
            "torchvision==0.15.2+cu118"
        ],
        "conda_packages": [
            "numpy                     1.23.4                   pypi_0    pypi",
            "torch                     1.9.0                    pypi_0    pypi",
            "torchvision               0.10.0                   pypi_0    pypi"
        ],
        "hip_compiled_version": "N/A",
        "hip_runtime_version": "N/A",
        "miopen_runtime_version": "N/A",
        "caching_allocator_config": "",
        "is_xnnpack_available": "True",
        "cpu_info": [
            "Architecture:        x86_64",
            "CPU op-mode(s):      32-bit, 64-bit",
            "Byte Order:          Little Endian",
            "CPU(s):              8",
            "On-line CPU(s) list: 0-7",
            "Thread(s) per core:  1",
            "Core(s) per socket:  8",
            "Socket(s):           1",
            "NUMA node(s):        1",
            "Vendor ID:           GenuineIntel",
            "CPU family:          6",
            "Model:               85",
            "Model name:          Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz",
            "Stepping:            5",
            "CPU MHz:             2494.140",
            "BogoMIPS:            4988.28",
            "Hypervisor vendor:   KVM",
            "Virtualization type: full",
            "L1d cache:           32K",
            "L1i cache:           32K",
            "L2 cache:            4096K",
            "L3 cache:            36608K",
            "NUMA node0 CPU(s):   0-7",
            "Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 arat avx512_vnni"
        ]
    },
    "Exceptions": [
        {
            "exception": "Error running install.py for extension /home/ubuntu/stable-diffusion-webui/extensions/sd-webui-reactor.\nCommand: \"/home/ubuntu/stable-diffusion-webui/venv/bin/python3\" \"/home/ubuntu/stable-diffusion-webui/extensions/sd-webui-reactor/install.py\"\nError code: 1\nstderr: Traceback (most recent call last):\n  File \"/home/ubuntu/stable-diffusion-webui/extensions/sd-webui-reactor/install.py\", line 30, in <module>\n    package: str, version: str | None = None, strict: bool = True\nTypeError: unsupported operand type(s) for |: 'type' and 'NoneType'\n",
            "traceback": [
                [
                    "/home/ubuntu/stable-diffusion-webui/modules/launch_utils.py, line 201, run_extension_installer",
                    "print(run(f'\"{python}\" \"{path_installer}\"', errdesc=f\"Error running install.py for extension {extension_dir}\", custom_env=env))"
                ],
                [
                    "/home/ubuntu/stable-diffusion-webui/modules/launch_utils.py, line 113, run",
                    "raise RuntimeError(\"\\n\".join(error_bits))"
                ]
            ]
        }
    ],
    "CPU": {
        "model": "x86_64",
        "count logical": 8,
        "count physical": 8
    },
    "RAM": {
        "total": "31GB",
        "used": "8GB",
        "free": "11GB",
        "active": "7GB",
        "inactive": "13GB",
        "buffers": "184MB",
        "cached": "12GB",
        "shared": "22MB"
    },
    "Extensions": [
        {
            "name": "sd-webui-reactor",
            "path": "/home/ubuntu/stable-diffusion-webui/extensions/sd-webui-reactor",
            "version": "0070cea3",
            "branch": "main",
            "remote": "https://github.com/Gourieff/sd-webui-reactor"
        }
    ],
    "Inactive extensions": [],
    "Environment": {
        "GIT": "git",
        "GRADIO_ANALYTICS_ENABLED": "False"
    },
    "Config": {
        "samples_save": true,
        "samples_format": "png",
        "samples_filename_pattern": "",
        "save_images_add_number": true,
        "grid_save": true,
        "grid_format": "png",
        "grid_extended_filename": false,
        "grid_only_if_multiple": true,
        "grid_prevent_empty_spots": false,
        "grid_zip_filename_pattern": "",
        "n_rows": -1,
        "font": "",
        "grid_text_active_color": "#000000",
        "grid_text_inactive_color": "#999999",
        "grid_background_color": "#ffffff",
        "enable_pnginfo": true,
        "save_txt": false,
        "save_images_before_face_restoration": false,
        "save_images_before_highres_fix": false,
        "save_images_before_color_correction": false,
        "save_mask": false,
        "save_mask_composite": false,
        "jpeg_quality": 80,
        "webp_lossless": false,
        "export_for_4chan": true,
        "img_downscale_threshold": 4.0,
        "target_side_length": 4000,
        "img_max_size_mp": 200,
        "use_original_name_batch": true,
        "use_upscaler_name_as_suffix": false,
        "save_selected_only": true,
        "save_init_img": false,
        "temp_dir": "",
        "clean_temp_dir_at_start": false,
        "outdir_samples": "",
        "outdir_txt2img_samples": "outputs/txt2img-images",
        "outdir_img2img_samples": "outputs/img2img-images",
        "outdir_extras_samples": "outputs/extras-images",
        "outdir_grids": "",
        "outdir_txt2img_grids": "outputs/txt2img-grids",
        "outdir_img2img_grids": "outputs/img2img-grids",
        "outdir_save": "log/images",
        "outdir_init_images": "outputs/init-images",
        "save_to_dirs": true,
        "grid_save_to_dirs": true,
        "use_save_to_dirs_for_ui": false,
        "directories_filename_pattern": "[date]",
        "directories_max_prompt_words": 8,
        "ESRGAN_tile": 192,
        "ESRGAN_tile_overlap": 8,
        "realesrgan_enabled_models": [
            "R-ESRGAN 4x+",
            "R-ESRGAN 4x+ Anime6B"
        ],
        "upscaler_for_img2img": null,
        "face_restoration_model": "CodeFormer",
        "code_former_weight": 0.5,
        "face_restoration_unload": false,
        "show_warnings": false,
        "memmon_poll_rate": 8,
        "samples_log_stdout": false,
        "multiple_tqdm": true,
        "print_hypernet_extra": false,
        "list_hidden_files": true,
        "disable_mmap_load_safetensors": false,
        "unload_models_when_training": false,
        "pin_memory": false,
        "save_optimizer_state": false,
        "save_training_settings_to_txt": true,
        "dataset_filename_word_regex": "",
        "dataset_filename_join_string": " ",
        "training_image_repeats_per_epoch": 1,
        "training_write_csv_every": 500,
        "training_xattention_optimizations": false,
        "training_enable_tensorboard": false,
        "training_tensorboard_save_images": false,
        "training_tensorboard_flush_every": 120,
        "sd_model_checkpoint": "majicmixRealistic_v6.safetensors [e4a30e4607]",
        "sd_checkpoint_cache": 0,
        "sd_vae_checkpoint_cache": 0,
        "sd_vae": "Automatic",
        "sd_vae_as_default": true,
        "sd_unet": "Automatic",
        "inpainting_mask_weight": 1.0,
        "initial_noise_multiplier": 1.0,
        "img2img_color_correction": false,
        "img2img_fix_steps": false,
        "img2img_background_color": "#ffffff",
        "enable_quantization": false,
        "enable_emphasis": true,
        "enable_batch_seeds": true,
        "comma_padding_backtrack": 20,
        "CLIP_stop_at_last_layers": 1,
        "upcast_attn": false,
        "auto_vae_precision": true,
        "randn_source": "GPU",
        "sdxl_crop_top": 0,
        "sdxl_crop_left": 0,
        "sdxl_refiner_low_aesthetic_score": 2.5,
        "sdxl_refiner_high_aesthetic_score": 6.0,
        "cross_attention_optimization": "Automatic",
        "s_min_uncond": 0.0,
        "token_merging_ratio": 0.0,
        "token_merging_ratio_img2img": 0.0,
        "token_merging_ratio_hr": 0.0,
        "pad_cond_uncond": false,
        "experimental_persistent_cond_cache": false,
        "use_old_emphasis_implementation": false,
        "use_old_karras_scheduler_sigmas": false,
        "no_dpmpp_sde_batch_determinism": false,
        "use_old_hires_fix_width_height": false,
        "dont_fix_second_order_samplers_schedule": false,
        "hires_fix_use_firstpass_conds": false,
        "interrogate_keep_models_in_memory": false,
        "interrogate_return_ranks": false,
        "interrogate_clip_num_beams": 1,
        "interrogate_clip_min_length": 24,
        "interrogate_clip_max_length": 48,
        "interrogate_clip_dict_limit": 1500,
        "interrogate_clip_skip_categories": [],
        "interrogate_deepbooru_score_threshold": 0.5,
        "deepbooru_sort_alpha": true,
        "deepbooru_use_spaces": true,
        "deepbooru_escape": true,
        "deepbooru_filter_tags": "",
        "extra_networks_show_hidden_directories": true,
        "extra_networks_hidden_models": "When searched",
        "extra_networks_default_multiplier": 1.0,
        "extra_networks_card_width": 0,
        "extra_networks_card_height": 0,
        "extra_networks_card_text_scale": 1.0,
        "extra_networks_card_show_desc": true,
        "extra_networks_add_text_separator": " ",
        "ui_extra_networks_tab_reorder": "",
        "textual_inversion_print_at_load": false,
        "textual_inversion_add_hashes_to_infotext": true,
        "sd_hypernetwork": "None",
        "localization": "None",
        "gradio_theme": "Default",
        "img2img_editor_height": 720,
        "return_grid": true,
        "return_mask": false,
        "return_mask_composite": false,
        "do_not_show_images": false,
        "send_seed": true,
        "send_size": true,
        "js_modal_lightbox": true,
        "js_modal_lightbox_initially_zoomed": true,
        "js_modal_lightbox_gamepad": false,
        "js_modal_lightbox_gamepad_repeat": 250,
        "show_progress_in_title": true,
        "samplers_in_dropdown": true,
        "dimensions_and_batch_together": true,
        "keyedit_precision_attention": 0.1,
        "keyedit_precision_extra": 0.05,
        "keyedit_delimiters": ".,\\/!?%^*;:{}=`~()",
        "keyedit_move": true,
        "quicksettings_list": [
            "sd_model_checkpoint"
        ],
        "ui_tab_order": [],
        "hidden_tabs": [],
        "ui_reorder_list": [],
        "hires_fix_show_sampler": false,
        "hires_fix_show_prompts": false,
        "disable_token_counters": false,
        "add_model_hash_to_info": true,
        "add_model_name_to_info": true,
        "add_user_name_to_info": false,
        "add_version_to_infotext": true,
        "disable_weights_auto_swap": true,
        "infotext_styles": "Apply if any",
        "show_progressbar": true,
        "live_previews_enable": true,
        "live_previews_image_format": "png",
        "show_progress_grid": true,
        "show_progress_every_n_steps": 10,
        "show_progress_type": "Approx NN",
        "live_preview_content": "Prompt",
        "live_preview_refresh_period": 1000,
        "hide_samplers": [],
        "eta_ddim": 0.0,
        "eta_ancestral": 1.0,
        "ddim_discretize": "uniform",
        "s_churn": 0.0,
        "s_tmin": 0.0,
        "s_noise": 1.0,
        "k_sched_type": "Automatic",
        "sigma_min": 0.0,
        "sigma_max": 0.0,
        "rho": 0.0,
        "eta_noise_seed_delta": 0,
        "always_discard_next_to_last_sigma": false,
        "uni_pc_variant": "bh1",
        "uni_pc_skip_type": "time_uniform",
        "uni_pc_order": 3,
        "uni_pc_lower_order_final": true,
        "postprocessing_enable_in_main_ui": [],
        "postprocessing_operation_order": [],
        "upscaling_max_images_in_cache": 5,
        "disabled_extensions": [],
        "disable_all_extensions": "none",
        "restore_config_state_file": "",
        "sd_checkpoint_hash": "e4a30e4607faeb06b5d590b2ed8e092690c631da0b2becb6224d4bb5327104b7"
    },
    "Startup": {
        "total": 7.595329999923706,
        "records": {
            "start": 1.239776611328125e-05,
            "launcher": 1.7428719997406006,
            "import torch": 2.508857488632202,
            "import gradio": 0.6212248802185059,
            "setup paths": 0.6819427013397217,
            "import ldm": 0.0029840469360351562,
            "other imports": 0.6221373081207275,
            "opts onchange": 0.0008392333984375,
            "setup SD model": 4.673004150390625e-05,
            "setup codeformer": 0.06203818321228027,
            "setup gfpgan": 5.1975250244140625e-05,
            "list extensions": 0.0001423358917236328,
            "list SD models": 0.027382850646972656,
            "load scripts/custom_code.py": 0.0005023479461669922,
            "load scripts/img2imgalt.py": 0.00032973289489746094,
            "load scripts/loopback.py": 0.0001678466796875,
            "load scripts/outpainting_mk_2.py": 0.00019168853759765625,
            "load scripts/poor_mans_outpainting.py": 0.00014019012451171875,
            "load scripts/postprocessing_codeformer.py": 0.00010848045349121094,
            "load scripts/postprocessing_gfpgan.py": 9.655952453613281e-05,
            "load scripts/postprocessing_upscale.py": 0.00016427040100097656,
            "load scripts/prompt_matrix.py": 0.00014019012451171875,
            "load scripts/prompts_from_file.py": 0.00014710426330566406,
            "load scripts/sd_upscale.py": 0.00012922286987304688,
            "load scripts/xyz_grid.py": 0.001725912094116211,
            "load scripts/ldsr_model.py": 0.3046267032623291,
            "load scripts/lora_script.py": 0.14186835289001465,
            "load scripts/scunet_model.py": 0.024677276611328125,
            "load scripts/swinir_model.py": 0.024545907974243164,
            "load scripts/hotkey_config.py": 0.00014495849609375,
            "load scripts/extra_options_section.py": 0.00015544891357421875,
            "load scripts": 0.49988603591918945,
            "load upscalers": 0.004308462142944336,
            "refresh VAE": 0.0007948875427246094,
            "refresh textual inversion templates": 4.696846008300781e-05,
            "scripts list_optimizers": 0.0002655982971191406,
            "scripts list_unets": 9.059906005859375e-06,
            "reload hypernetworks": 0.005176544189453125,
            "initialize extra networks": 0.0051267147064208984,
            "scripts before_ui_callback": 9.775161743164062e-05,
            "create ui": 0.5809347629547119,
            "gradio launch": 0.13565492630004883,
            "add APIs": 0.09210467338562012,
            "app_started_callback/lora_script.py": 0.0003924369812011719,
            "app_started_callback": 0.0003972053527832031
        }
    },
    "Packages": [
        "absl-py==2.0.0",
        "accelerate==0.18.0",
        "addict==2.4.0",
        "aenum==3.1.15",
        "aiofiles==23.2.1",
        "aiohttp==3.8.6",
        "aiosignal==1.3.1",
        "altair==5.1.2",
        "antlr4-python3-runtime==4.9.3",
        "anyio==3.7.1",
        "async-timeout==4.0.3",
        "attrs==23.1.0",
        "basicsr==1.4.2",
        "beautifulsoup4==4.12.2",
        "blendmodes==2022",
        "boltons==23.0.0",
        "cachetools==5.3.1",
        "certifi==2023.7.22",
        "charset-normalizer==3.3.0",
        "clean-fid==0.1.35",
        "click==8.1.7",
        "clip==1.0",
        "cmake==3.27.6",
        "contourpy==1.1.1",
        "cycler==0.12.1",
        "deprecation==2.1.0",
        "einops==0.4.1",
        "exceptiongroup==1.1.3",
        "facexlib==0.3.0",
        "fastapi==0.94.0",
        "ffmpy==0.3.1",
        "filelock==3.12.4",
        "filterpy==1.4.5",
        "fonttools==4.43.1",
        "frozenlist==1.4.0",
        "fsspec==2023.9.2",
        "ftfy==6.1.1",
        "future==0.18.3",
        "gdown==4.7.1",
        "gfpgan==1.3.8",
        "gitdb==4.0.10",
        "gitpython==3.1.30",
        "google-auth-oauthlib==0.4.6",
        "google-auth==2.23.3",
        "gradio-client==0.6.0",
        "gradio==3.32.0",
        "grpcio==1.59.0",
        "h11==0.12.0",
        "httpcore==0.15.0",
        "httpx==0.24.1",
        "huggingface-hub==0.18.0",
        "idna==3.4",
        "imageio==2.31.5",
        "importlib-metadata==6.8.0",
        "importlib-resources==6.1.0",
        "inflection==0.5.1",
        "jinja2==3.1.2",
        "jsonmerge==1.8.0",
        "jsonschema-specifications==2023.7.1",
        "jsonschema==4.19.1",
        "kiwisolver==1.4.5",
        "kornia==0.6.7",
        "lark==1.1.2",
        "lazy-loader==0.3",
        "lightning-utilities==0.9.0",
        "linkify-it-py==2.0.2",
        "lit==17.0.2",
        "llvmlite==0.41.0",
        "lmdb==1.4.1",
        "lpips==0.1.4",
        "markdown-it-py==2.2.0",
        "markdown==3.5",
        "markupsafe==2.1.3",
        "matplotlib==3.7.3",
        "mdit-py-plugins==0.3.3",
        "mdurl==0.1.2",
        "mpmath==1.3.0",
        "multidict==6.0.4",
        "networkx==3.1",
        "numba==0.58.0",
        "numpy==1.23.5",
        "oauthlib==3.2.2",
        "omegaconf==2.2.3",
        "open-clip-torch==2.20.0",
        "opencv-python==4.8.1.78",
        "orjson==3.9.8",
        "packaging==23.2",
        "pandas==2.0.3",
        "piexif==1.1.3",
        "pillow==9.5.0",
        "pip==21.1.1",
        "pkgutil-resolve-name==1.3.10",
        "platformdirs==3.11.0",
        "protobuf==3.19.6",
        "psutil==5.9.5",
        "pyasn1-modules==0.3.0",
        "pyasn1==0.5.0",
        "pydantic==1.10.13",
        "pydub==0.25.1",
        "pygments==2.16.1",
        "pyparsing==3.1.1",
        "pysocks==1.7.1",
        "python-dateutil==2.8.2",
        "python-multipart==0.0.6",
        "pytorch-lightning==1.9.4",
        "pytz==2023.3.post1",
        "pywavelets==1.4.1",
        "pyyaml==6.0.1",
        "realesrgan==0.3.0",
        "referencing==0.30.2",
        "regex==2023.10.3",
        "requests-oauthlib==1.3.1",
        "requests==2.31.0",
        "resize-right==0.0.2",
        "rpds-py==0.10.6",
        "rsa==4.9",
        "safetensors==0.3.1",
        "scikit-image==0.20.0",
        "scipy==1.9.1",
        "semantic-version==2.10.0",
        "sentencepiece==0.1.99",
        "setuptools==56.0.0",
        "six==1.16.0",
        "smmap==5.0.1",
        "sniffio==1.3.0",
        "soupsieve==2.5",
        "starlette==0.26.1",
        "sympy==1.12",
        "tb-nightly==2.11.0a20220906",
        "tensorboard-data-server==0.6.1",
        "tensorboard-plugin-wit==1.8.1",
        "tifffile==2023.7.10",
        "timm==0.6.7",
        "tokenizers==0.13.3",
        "tomesd==0.1.2",
        "tomli==2.0.1",
        "toolz==0.12.0",
        "torch==2.0.1+cu118",
        "torchdiffeq==0.2.3",
        "torchmetrics==1.2.0",
        "torchsde==0.2.5",
        "torchvision==0.15.2+cu118",
        "tqdm==4.66.1",
        "trampoline==0.1.2",
        "transformers==4.25.1",
        "triton==2.0.0",
        "typing-extensions==4.8.0",
        "tzdata==2023.3",
        "uc-micro-py==1.0.2",
        "urllib3==2.0.6",
        "uvicorn==0.23.2",
        "wcwidth==0.2.8",
        "websockets==11.0.3",
        "werkzeug==3.0.0",
        "wheel==0.41.2",
        "yapf==0.40.2",
        "yarl==1.9.2",
        "zipp==3.17.0"
    ]
}

### Relevant console log

```Shell
Error message when installing
*** Error running install.py for extension /home/ubuntu/stable-diffusion-webui/extensions/sd-webui-reactor.
*** Command: "/home/ubuntu/stable-diffusion-webui/venv/bin/python3" "/home/ubuntu/stable-diffusion-webui/extensions/sd-webui-reactor/install.py"
*** Error code: 1
*** stderr: Traceback (most recent call last):
***   File "/home/ubuntu/stable-diffusion-webui/extensions/sd-webui-reactor/install.py", line 30, in <module>
***     package: str, version: str | None = None, strict: bool = True
*** TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by Gourieff** [comment]
> "Python": "3.8.12"

You use rather old version of Python 
A1111 (or SD.Next) won't work properly with this version
You need Python 3.10.6 for A1111 venv

That's why you get `TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'`
Support of this operand appears in 3.10

So, to resolve this issue you need to re-create venv with 3.10.6 Python

**Comment by MeTRoDevlop** [comment]
if you can't change Python version like me, just make this changes in install.py:

1. change:
from typing import Any
to 
from typing import Any, Union

2. change:
package: str, version: str | None = None, strict: bool = True
to 
package: str, version: Union[str, None] = None, strict: bool = True
