### ISSUE TITLE
[Feature]: I need more params in api /reactor/image

### ISSUE THREAD

**Issue by moo611** [Gourieff/sd-webui-reactor#123]
### Feature description

Can some parameters of img2img be added to this endpoint? Such as denoising strength, prompt and negative prompt words, sampling methods, resize mode, width, height, etc. Especially denoising strength, I found that it greatly affects the effect of face swapping. Moreover, I currently cannot set the width and height of the image result, so I also need width and height parameters.

**Comment by Gourieff** [comment]
With this API you swap face(s) in the existing image, so why do you need to change width and height? These params must be equal to the input or you will get a disproportionate result

**Comment by moo611** [comment]
> With this API you swap face(s) in the existing image, so why do you need to change width and height? These params must be equal to the input or you will get a disproportionate result

okay, but what about denoising strength?

**Comment by Gourieff** [comment]
ReActor's API is for swapping faces from one image into another
Denoising strength parameter is actual when you use it via SD-WebUI API and SD-WebUI API already has the denoising strength
