### ISSUE TITLE
[Notification]: extension schedule to be added to webui extension index

### ISSUE THREAD

**Issue by w-e-w** [Gourieff/sd-webui-reactor#139]
### Feature description

@Gourieff
Hi I'm one of the maintenance of https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions
we received a [request](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/issues/209) to add this extension to the webui extension index

this extensional will be add to the index after a week if no objection is raised
see PR https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/213
if you would like to change the description name or anything about how it's being listed or if you would not like it to be please let us know or make a new PR so you can change the details yourself

**Comment by Gourieff** [comment]
@w-e-w 
Hello!
That's nice, thank you, I don't mind
Please just change the description to:
```
Fast and Simple FaceSwap Extension with a lot of improvements. Read README.md, additional installation steps required
```

**Comment by w-e-w** [comment]
changed and merged

**Comment by w-e-w** [comment]
sorry I was sleep deprived
I thought I had committed the changes in push to get up before I press merged
turns out I didn't I fixed the description again now
