### ISSUE TITLE
SD.Next | Cannot Import CodeFormer Module

### ISSUE THREAD

**Issue by videogamingeducation** [Gourieff/sd-webui-reactor#140]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

I followed the instructions to install reactor step by step in Windows 11 and I'm getting this. It used to work before.

19:02:34-691462 ERROR    Module load: extensions\sd-webui-reactor\scripts\reactor_api.py: ImportError
╭─────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────╮
│ D:\automatic\modules\script_loading.py:21 in load_module                                                         │
│                                                                                                                  │
│   20 │   │   │   with contextlib.redirect_stdout(io.StringIO()) as stdout:                                       │
│ ❱ 21 │   │   │   │   module_spec.loader.exec_module(module)                                                      │
│   22 │   │   │   setup_logging() # reset since scripts can hijaack logging                                       │
│ in exec_module:883                                                                                               │
│ in _call_with_frames_removed:241                                                                                 │
│                                                                                                                  │
│ D:\automatic\extensions\sd-webui-reactor\scripts\reactor_api.py:17 in <module>                                   │
│                                                                                                                  │
│    16                                                                                                            │
│ ❱  17 from scripts.reactor_swapper import EnhancementOptions, swap_face                                          │
│    18 from scripts.reactor_logger import logger                                                                  │
│                                                                                                                  │
│ D:\automatic\extensions\sd-webui-reactor\scripts\reactor_swapper.py:13 in <module>                               │
│                                                                                                                  │
│    12 from modules.face_restoration import FaceRestoration                                                       │
│ ❱  13 from modules import codeformer_model                                                                       │
│    14 from modules.upscaler import UpscalerData                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name 'codeformer_model' from 'modules' (unknown location)
19:02:34-724692 ERROR    Module load: extensions\sd-webui-reactor\scripts\reactor_faceswap.py: ImportError
╭─────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────╮
│ D:\automatic\modules\script_loading.py:21 in load_module                                                         │
│                                                                                                                  │
│   20 │   │   │   with contextlib.redirect_stdout(io.StringIO()) as stdout:                                       │
│ ❱ 21 │   │   │   │   module_spec.loader.exec_module(module)                                                      │
│   22 │   │   │   setup_logging() # reset since scripts can hijaack logging                                       │
│ in exec_module:883                                                                                               │
│ in _call_with_frames_removed:241                                                                                 │
│                                                                                                                  │
│ D:\automatic\extensions\sd-webui-reactor\scripts\reactor_faceswap.py:26 in <module>                              │
│                                                                                                                  │
│    25 from scripts.reactor_logger import logger                                                                  │
│ ❱  26 from scripts.reactor_swapper import EnhancementOptions, swap_face, check_process_halt, r                   │
│    27 from scripts.reactor_version import version_flag, app_title                                                │
│                                                                                                                  │
│ D:\automatic\extensions\sd-webui-reactor\scripts\reactor_swapper.py:13 in <module>                               │
│                                                                                                                  │
│    12 from modules.face_restoration import FaceRestoration                                                       │
│ ❱  13 from modules import codeformer_model                                                                       │
│    14 from modules.upscaler import UpscalerData                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name 'codeformer_model' from 'modules' (unknown location)
19:02:34-736693 ERROR    Module load: extensions\sd-webui-reactor\scripts\reactor_swapper.py: ImportError
╭─────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────╮
│ D:\automatic\modules\script_loading.py:21 in load_module                                                         │
│                                                                                                                  │
│   20 │   │   │   with contextlib.redirect_stdout(io.StringIO()) as stdout:                                       │
│ ❱ 21 │   │   │   │   module_spec.loader.exec_module(module)                                                      │
│   22 │   │   │   setup_logging() # reset since scripts can hijaack logging                                       │
│ in exec_module:883                                                                                               │
│ in _call_with_frames_removed:241                                                                                 │
│                                                                                                                  │
│ D:\automatic\extensions\sd-webui-reactor\scripts\reactor_swapper.py:13 in <module>                               │
│                                                                                                                  │
│    12 from modules.face_restoration import FaceRestoration                                                       │
│ ❱  13 from modules import codeformer_model                                                                       │
│    14 from modules.upscaler import UpscalerData                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name 'codeformer_model' from 'modules' (unknown location)

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### Sysinfo

Windows 11
RTX 3070
SDNext

### Relevant console log

```Shell
19:02:34-691462 ERROR    Module load: extensions\sd-webui-reactor\scripts\reactor_api.py: ImportError
╭─────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────╮
│ D:\automatic\modules\script_loading.py:21 in load_module                                                         │
│                                                                                                                  │
│   20 │   │   │   with contextlib.redirect_stdout(io.StringIO()) as stdout:                                       │
│ ❱ 21 │   │   │   │   module_spec.loader.exec_module(module)                                                      │
│   22 │   │   │   setup_logging() # reset since scripts can hijaack logging                                       │
│ in exec_module:883                                                                                               │
│ in _call_with_frames_removed:241                                                                                 │
│                                                                                                                  │
│ D:\automatic\extensions\sd-webui-reactor\scripts\reactor_api.py:17 in <module>                                   │
│                                                                                                                  │
│    16                                                                                                            │
│ ❱  17 from scripts.reactor_swapper import EnhancementOptions, swap_face                                          │
│    18 from scripts.reactor_logger import logger                                                                  │
│                                                                                                                  │
│ D:\automatic\extensions\sd-webui-reactor\scripts\reactor_swapper.py:13 in <module>                               │
│                                                                                                                  │
│    12 from modules.face_restoration import FaceRestoration                                                       │
│ ❱  13 from modules import codeformer_model                                                                       │
│    14 from modules.upscaler import UpscalerData                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name 'codeformer_model' from 'modules' (unknown location)
19:02:34-724692 ERROR    Module load: extensions\sd-webui-reactor\scripts\reactor_faceswap.py: ImportError
╭─────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────╮
│ D:\automatic\modules\script_loading.py:21 in load_module                                                         │
│                                                                                                                  │
│   20 │   │   │   with contextlib.redirect_stdout(io.StringIO()) as stdout:                                       │
│ ❱ 21 │   │   │   │   module_spec.loader.exec_module(module)                                                      │
│   22 │   │   │   setup_logging() # reset since scripts can hijaack logging                                       │
│ in exec_module:883                                                                                               │
│ in _call_with_frames_removed:241                                                                                 │
│                                                                                                                  │
│ D:\automatic\extensions\sd-webui-reactor\scripts\reactor_faceswap.py:26 in <module>                              │
│                                                                                                                  │
│    25 from scripts.reactor_logger import logger                                                                  │
│ ❱  26 from scripts.reactor_swapper import EnhancementOptions, swap_face, check_process_halt, r                   │
│    27 from scripts.reactor_version import version_flag, app_title                                                │
│                                                                                                                  │
│ D:\automatic\extensions\sd-webui-reactor\scripts\reactor_swapper.py:13 in <module>                               │
│                                                                                                                  │
│    12 from modules.face_restoration import FaceRestoration                                                       │
│ ❱  13 from modules import codeformer_model                                                                       │
│    14 from modules.upscaler import UpscalerData                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name 'codeformer_model' from 'modules' (unknown location)
19:02:34-736693 ERROR    Module load: extensions\sd-webui-reactor\scripts\reactor_swapper.py: ImportError
╭─────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────╮
│ D:\automatic\modules\script_loading.py:21 in load_module                                                         │
│                                                                                                                  │
│   20 │   │   │   with contextlib.redirect_stdout(io.StringIO()) as stdout:                                       │
│ ❱ 21 │   │   │   │   module_spec.loader.exec_module(module)                                                      │
│   22 │   │   │   setup_logging() # reset since scripts can hijaack logging                                       │
│ in exec_module:883                                                                                               │
│ in _call_with_frames_removed:241                                                                                 │
│                                                                                                                  │
│ D:\automatic\extensions\sd-webui-reactor\scripts\reactor_swapper.py:13 in <module>                               │
│                                                                                                                  │
│    12 from modules.face_restoration import FaceRestoration                                                       │
│ ❱  13 from modules import codeformer_model                                                                       │
│    14 from modules.upscaler import UpscalerData                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name 'codeformer_model' from 'modules' (unknown location)
```

**Comment by Gourieff** [comment]
Do you use SD.Next?
I will take a look later

**Comment by Gourieff** [comment]
Fixed https://github.com/Gourieff/sd-webui-reactor/commit/4e877445ba722250204b9d2b81e69b0f9e136b7c
