### ISSUE TITLE
[Feature]: Batch Folder/Mode + Blending of Source Faces

### ISSUE THREAD

**Issue by Webtransformer** [Gourieff/sd-webui-reactor#143]
### Feature description

Sometimes I want to test different faces. How about a batch mode like in controlnet?
A possiblity where you can set the input folder for faces and then I will iterate through each image?
With the option to include also subfolders.

**Comment by Gourieff** [comment]
It makes sense

**Comment by drdancm** [comment]
How about also doing Blending of Source Faces like in FaceSwapLab ?

**Comment by Gourieff** [comment]
Done! (Subfolders support will be added later)
Blending of Source Faces - also planned!

**Comment by Webtransformer** [comment]
Tested the batch mode and is working great, thanks for your effort!

**Comment by BigZampano** [comment]
Is there a tutorial somewhere on how to blend multiple faces and save them as face model...? (in ComfyUI)

**Comment by Gourieff** [comment]
This option is not implemented yet

**Comment by BigZampano** [comment]
Oh I see... then I'll be patient... thanks for answering..!
