### ISSUE TITLE
 AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by Aubi1337** [Gourieff/sd-webui-reactor#144]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

I'm facing an issue that I get this error below

Loading weights [7440042bbd] from D:\stable diffusion\stable-diffusion-webui\models\Stable-diffusion\New folder\sd_xl_refiner_1.0.safetensors
Creating model from config: D:\stable diffusion\stable-diffusion-webui\repositories\generative-models\configs\inference\sd_xl_refiner.yaml
Loading VAE weights specified in settings: D:\stable diffusion\stable-diffusion-webui\models\VAE\sdxl_vae.safetensors
Applying attention optimization: xformers... done.
Model loaded in 59.5s (create model: 0.3s, apply weights to model: 58.7s, load VAE: 0.3s).
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [01:15<00:00,  2.51s/it]
00:34:04 - ReActor - STATUS - Working: source face index [0], target face index [0]████| 60/60 [01:43<00:00,  4.66s/it]
00:34:04 - ReActor - STATUS - Analyzing Source Image...
set det-size: (640, 640)
00:34:07 - ReActor - STATUS - Analyzing Target Image...
set det-size: (640, 640)
00:34:08 - ReActor - STATUS - Detecting Source Face, Index = 0
00:34:08 - ReActor - STATUS - Detected: -31- y.o. Male
00:34:08 - ReActor - STATUS - Detecting Target Face, Index = 0
00:34:08 - ReActor - STATUS - Detected: -32- y.o. Male
00:34:08 - ReActor - STATUS - Swapping Source into Target
*** Error running postprocess_image: D:\stable diffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py
    Traceback (most recent call last):
      File "D:\stable diffusion\stable-diffusion-webui\modules\scripts.py", line 675, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "D:\stable diffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 376, in postprocess_image
        result, output, swapped = swap_face(
      File "D:\stable diffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 352, in swap_face
        result = face_swapper.get(result, target_face, source_face)
    AttributeError: 'NoneType' object has no attribute 'get'

I've tried to re-install the extension, also re-downloaded the 128 file, none seems to support, I'm seeking your help as I couldn't find a solution to fix it over Automatic1111, Thank you!

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### Sysinfo

Windows 10, Automatic - A1111

### Relevant console log

```Shell
Loading weights [7440042bbd] from D:\stable diffusion\stable-diffusion-webui\models\Stable-diffusion\New folder\sd_xl_refiner_1.0.safetensors
Creating model from config: D:\stable diffusion\stable-diffusion-webui\repositories\generative-models\configs\inference\sd_xl_refiner.yaml
Loading VAE weights specified in settings: D:\stable diffusion\stable-diffusion-webui\models\VAE\sdxl_vae.safetensors
Applying attention optimization: xformers... done.
Model loaded in 59.5s (create model: 0.3s, apply weights to model: 58.7s, load VAE: 0.3s).
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [01:15<00:00,  2.51s/it]
00:34:04 - ReActor - STATUS - Working: source face index [0], target face index [0]████| 60/60 [01:43<00:00,  4.66s/it]
00:34:04 - ReActor - STATUS - Analyzing Source Image...
set det-size: (640, 640)
00:34:07 - ReActor - STATUS - Analyzing Target Image...
set det-size: (640, 640)
00:34:08 - ReActor - STATUS - Detecting Source Face, Index = 0
00:34:08 - ReActor - STATUS - Detected: -31- y.o. Male
00:34:08 - ReActor - STATUS - Detecting Target Face, Index = 0
00:34:08 - ReActor - STATUS - Detected: -32- y.o. Male
00:34:08 - ReActor - STATUS - Swapping Source into Target
*** Error running postprocess_image: D:\stable diffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py
    Traceback (most recent call last):
      File "D:\stable diffusion\stable-diffusion-webui\modules\scripts.py", line 675, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "D:\stable diffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 376, in postprocess_image
        result, output, swapped = swap_face(
      File "D:\stable diffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 352, in swap_face
        result = face_swapper.get(result, target_face, source_face)
    AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by Gourieff** [comment]
https://github.com/Gourieff/sd-webui-reactor#v-invalid_protobuf--load-model-from-modelsinsightfaceinswapper_128onnx-failedprotobuf-parsing-failed-or-attributeerror-nonetype-object-has-no-attribute-get-or-attributeerror-faceswapscript-object-has-no-attribute-save_original

**Comment by Morples** [comment]
> https://github.com/Gourieff/sd-webui-reactor#v-invalid_protobuf--load-model-from-modelsinsightfaceinswapper_128onnx-failedprotobuf-parsing-failed-or-attributeerror-nonetype-object-has-no-attribute-get-or-attributeerror-faceswapscript-object-has-no-attribute-save_original

This did not work

**Comment by pixlemedia** [comment]
i also got this error message in SDN. I`ve downloaded the "inswapper_128.onnx" file and pasted it into the recommended `\models\insightface` folder as well as `models\insightface\models\buffalo_l` (where the other models are placed) but still got the error message mentioned above.

**Comment by VitoMao** [comment]
> i also got this error message in SDN. I`ve downloaded the "inswapper_128.onnx" file and pasted it into the recommended `\models\insightface`folder as well as`models\insightface\models\buffalo_l` (where the other models are placed) but still got the error message mentioned above.

Me too.

**Comment by Hans2004** [comment]
Same here.

**Comment by glmann** [comment]
redownloading onnx models from links provided and reistalling insightface directly from insightface-0.7.3-cp310-cp310-win_amd64.whl didn't help. i have clean install of sd 1.7.0 and sd 1.8.0, no other extensions installed, all defaults
