### ISSUE TITLE
Insight Face Not Found.

### ISSUE THREAD

**Issue by diadisum** [Gourieff/sd-webui-reactor#154]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

"Insight Face" module not found.

### Steps to reproduce the problem

1. Launch Stable Diffusion A1111
2. CMD Panel displays "Checking -=ReActor Force=- requirements... Error: The 'insightface==0.7.3' distribution was not found and is required by the application"

### Sysinfo

{
    "Platform": "Windows-10-10.0.22621-SP0",
    "Python": "3.10.6",
    "Version": "v1.6.0",
    "Commit": "5ef669de080814067961f28357256e8fe27544f4",
    "Script path": "C:\\Users\\MyBelovedPC\\Desktop\\The AI\\stable-diffusion-webui",
    "Data path": "C:\\Users\\MyBelovedPC\\Desktop\\The AI\\stable-diffusion-webui",
    "Extensions dir": "C:\\Users\\MyBelovedPC\\Desktop\\The AI\\stable-diffusion-webui\\extensions",
    "Checksum": "408ffc92547b9b856d490f06264342bd2f44c3788b981d198f69bce2c2233476",
    "Commandline": [
        "launch.py",
        "--xformers",
        "--medvram",
        "--autolaunch"
    ],
    "Torch env info": "'NoneType' object has no attribute 'splitlines'",
    "Exceptions": [
        {
            "exception": "No module named 'insightface'",
            "traceback": [
                [
                    "C:\\Users\\MyBelovedPC\\Desktop\\The AI\\stable-diffusion-webui\\modules\\scripts.py, line 382, load_scripts",
                    "script_module = script_loading.load_module(scriptfile.path)"
                ],
                [
                    "C:\\Users\\MyBelovedPC\\Desktop\\The AI\\stable-diffusion-webui\\modules\\script_loading.py, line 10, load_module",
                    "module_spec.loader.exec_module(module)"
                ],
                [
                    "<frozen importlib._bootstrap_external>, line 883, exec_module",
                    ""
                ],
                [
                    "<frozen importlib._bootstrap>, line 241, _call_with_frames_removed",
                    ""
                ],
                [
                    "C:\\Users\\MyBelovedPC\\Desktop\\The AI\\stable-diffusion-webui\\extensions\\sd-webui-reactor-force\\scripts\\rf_swapper.py, line 10, <module>",
                    "import insightface"
                ]
            ]
        },
        {
            "exception": "No module named 'insightface'",
            "traceback": [
                [
                    "C:\\Users\\MyBelovedPC\\Desktop\\The AI\\stable-diffusion-webui\\modules\\scripts.py, line 382, load_scripts",
                    "script_module = script_loading.load_module(scriptfile.path)"
                ],
                [
                    "C:\\Users\\MyBelovedPC\\Desktop\\The AI\\stable-diffusion-webui\\modules\\script_loading.py, line 10, load_module",
                    "module_spec.loader.exec_module(module)"
                ],
                [
                    "<frozen importlib._bootstrap_external>, line 883, exec_module",
                    ""
                ],
                [
                    "<frozen importlib._bootstrap>, line 241, _call_with_frames_removed",
                    ""
                ],
                [
                    "C:\\Users\\MyBelovedPC\\Desktop\\The AI\\stable-diffusion-webui\\extensions\\sd-webui-reactor-force\\scripts\\rf_faceswap.py, line 26, <module>",
                    "from scripts.rf_swapper import EnhancementOptions, swap_face, check_process_halt, reset_messaged"
                ],
                [
                    "C:\\Users\\MyBelovedPC\\Desktop\\The AI\\stable-diffusion-webui\\extensions\\sd-webui-reactor-force\\scripts\\rf_swapper.py, line 10, <module>",
                    "import insightface"
                ]
            ]
        },
        {
            "exception": "No module named 'insightface'",
            "traceback": [
                [
                    "C:\\Users\\MyBelovedPC\\Desktop\\The AI\\stable-diffusion-webui\\modules\\scripts.py, line 382, load_scripts",
                    "script_module = script_loading.load_module(scriptfile.path)"
                ],
                [
                    "C:\\Users\\MyBelovedPC\\Desktop\\The AI\\stable-diffusion-webui\\modules\\script_loading.py, line 10, load_module",
                    "module_spec.loader.exec_module(module)"
                ],
                [
                    "<frozen importlib._bootstrap_external>, line 883, exec_module",
                    ""
                ],
                [
                    "<frozen importlib._bootstrap>, line 241, _call_with_frames_removed",
                    ""
                ],
                [
                    "C:\\Users\\MyBelovedPC\\Desktop\\The AI\\stable-diffusion-webui\\extensions\\sd-webui-reactor-force\\scripts\\rf_console_log_patch.py, line 4, <module>",
                    "import insightface"
                ]
            ]
        },
        {
            "exception": "No module named 'insightface'",
            "traceback": [
                [
                    "C:\\Users\\MyBelovedPC\\Desktop\\The AI\\stable-diffusion-webui\\modules\\scripts.py, line 382, load_scripts",
                    "script_module = script_loading.load_module(scriptfile.path)"
                ],
                [
                    "C:\\Users\\MyBelovedPC\\Desktop\\The AI\\stable-diffusion-webui\\modules\\script_loading.py, line 10, load_module",
                    "module_spec.loader.exec_module(module)"
                ],
                [
                    "<frozen importlib._bootstrap_external>, line 883, exec_module",
                    ""
                ],
                [
                    "<frozen importlib._bootstrap>, line 241, _call_with_frames_removed",
                    ""
                ],
                [
                    "C:\\Users\\MyBelovedPC\\Desktop\\The AI\\stable-diffusion-webui\\extensions\\sd-webui-reactor-force\\scripts\\rf_api.py, line 17, <module>",
                    "from scripts.rf_swapper import EnhancementOptions, swap_face"
                ],
                [
                    "C:\\Users\\MyBelovedPC\\Desktop\\The AI\\stable-diffusion-webui\\extensions\\sd-webui-reactor-force\\scripts\\rf_swapper.py, line 10, <module>",
                    "import insightface"
                ]
            ]
        },
        {
            "exception": "No module named 'insightface'",
            "traceback": [
                [
                    "C:\\Users\\MyBelovedPC\\Desktop\\The AI\\stable-diffusion-webui\\modules\\scripts.py, line 382, load_scripts",
                    "script_module = script_loading.load_module(scriptfile.path)"
                ],
                [
                    "C:\\Users\\MyBelovedPC\\Desktop\\The AI\\stable-diffusion-webui\\modules\\script_loading.py, line 10, load_module",
                    "module_spec.loader.exec_module(module)"
                ],
                [
                    "<frozen importlib._bootstrap_external>, line 883, exec_module",
                    ""
                ],
                [
                    "<frozen importlib._bootstrap>, line 241, _call_with_frames_removed",
                    ""
                ],
                [
                    "C:\\Users\\MyBelovedPC\\Desktop\\The AI\\stable-diffusion-webui\\extensions\\sd-webui-reactor\\scripts\\reactor_swapper.py, line 10, <module>",
                    "import insightface"
                ]
            ]
        }
    ],
    "CPU": {
        "model": "AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD",
        "count logical": 16,
        "count physical": 8
    },
    "RAM": {
        "total": "32GB",
        "used": "11GB",
        "free": "21GB"
    },
    "Extensions": [
        {
            "name": "canvas-zoom",
            "path": "C:\\Users\\MyBelovedPC\\Desktop\\The AI\\stable-diffusion-webui\\extensions\\canvas-zoom",
            "version": "36762c01",
            "branch": "main",
            "remote": "https://github.com/richrobber2/canvas-zoom.git"
        },
        {
            "name": "sd-webui-ar",
            "path": "C:\\Users\\MyBelovedPC\\Desktop\\The AI\\stable-diffusion-webui\\extensions\\sd-webui-ar",
            "version": "3973c86a",
            "branch": "main",
            "remote": "https://github.com/alemelis/sd-webui-ar.git"
        },
        {
            "name": "sd-webui-reactor",
            "path": "C:\\Users\\MyBelovedPC\\Desktop\\The AI\\stable-diffusion-webui\\extensions\\sd-webui-reactor",
            "version": "780357ee",
            "branch": "main",
            "remote": "https://github.com/Gourieff/sd-webui-reactor.git"
        },
        {
            "name": "sd-webui-reactor-force",
            "path": "C:\\Users\\MyBelovedPC\\Desktop\\The AI\\stable-diffusion-webui\\extensions\\sd-webui-reactor-force",
            "version": "32b5e166",
            "branch": "main",
            "remote": "https://github.com/Gourieff/sd-webui-reactor-force"
        }
    ],
    "Inactive extensions": [],
    "Environment": {
        "COMMANDLINE_ARGS": " --xformers --medvram --autolaunch",
        "GRADIO_ANALYTICS_ENABLED": "False"
    },
    "Config": {
        "samples_save": true,
        "samples_format": "png",
        "samples_filename_pattern": "",
        "save_images_add_number": true,
        "grid_save": true,
        "grid_format": "png",
        "grid_extended_filename": false,
        "grid_only_if_multiple": true,
        "grid_prevent_empty_spots": false,
        "grid_zip_filename_pattern": "",
        "n_rows": -1,
        "font": "",
        "grid_text_active_color": "#000000",
        "grid_text_inactive_color": "#999999",
        "grid_background_color": "#ffffff",
        "enable_pnginfo": true,
        "save_txt": false,
        "save_images_before_face_restoration": false,
        "save_images_before_highres_fix": false,
        "save_images_before_color_correction": false,
        "save_mask": false,
        "save_mask_composite": false,
        "jpeg_quality": 80,
        "webp_lossless": false,
        "export_for_4chan": true,
        "img_downscale_threshold": 4.0,
        "target_side_length": 4000,
        "img_max_size_mp": 200,
        "use_original_name_batch": true,
        "use_upscaler_name_as_suffix": false,
        "save_selected_only": true,
        "save_init_img": false,
        "temp_dir": "",
        "clean_temp_dir_at_start": false,
        "save_incomplete_images": false,
        "outdir_samples": "",
        "outdir_txt2img_samples": "outputs/txt2img-images",
        "outdir_img2img_samples": "outputs/img2img-images",
        "outdir_extras_samples": "outputs/extras-images",
        "outdir_grids": "",
        "outdir_txt2img_grids": "outputs/txt2img-grids",
        "outdir_img2img_grids": "outputs/img2img-grids",
        "outdir_save": "log/images",
        "outdir_init_images": "outputs/init-images",
        "save_to_dirs": true,
        "grid_save_to_dirs": true,
        "use_save_to_dirs_for_ui": false,
        "directories_filename_pattern": "[date]",
        "directories_max_prompt_words": 8,
        "ESRGAN_tile": 192,
        "ESRGAN_tile_overlap": 8,
        "realesrgan_enabled_models": [
            "R-ESRGAN 4x+",
            "R-ESRGAN 4x+ Anime6B"
        ],
        "upscaler_for_img2img": null,
        "face_restoration": false,
        "face_restoration_model": "CodeFormer",
        "code_former_weight": 0.5,
        "face_restoration_unload": false,
        "auto_launch_browser": "Local",
        "show_warnings": false,
        "show_gradio_deprecation_warnings": true,
        "memmon_poll_rate": 8,
        "samples_log_stdout": false,
        "multiple_tqdm": true,
        "print_hypernet_extra": false,
        "list_hidden_files": true,
        "disable_mmap_load_safetensors": false,
        "hide_ldm_prints": true,
        "api_enable_requests": true,
        "api_forbid_local_requests": true,
        "api_useragent": "",
        "unload_models_when_training": false,
        "pin_memory": false,
        "save_optimizer_state": false,
        "save_training_settings_to_txt": true,
        "dataset_filename_word_regex": "",
        "dataset_filename_join_string": " ",
        "training_image_repeats_per_epoch": 1,
        "training_write_csv_every": 500,
        "training_xattention_optimizations": false,
        "training_enable_tensorboard": false,
        "training_tensorboard_save_images": false,
        "training_tensorboard_flush_every": 120,
        "sd_model_checkpoint": "photon_v1.safetensors [ec41bd2a82]",
        "sd_checkpoints_limit": 1,
        "sd_checkpoints_keep_in_cpu": true,
        "sd_checkpoint_cache": 0,
        "sd_unet": "Automatic",
        "enable_quantization": false,
        "enable_emphasis": true,
        "enable_batch_seeds": true,
        "comma_padding_backtrack": 20,
        "CLIP_stop_at_last_layers": 1,
        "upcast_attn": false,
        "randn_source": "GPU",
        "tiling": false,
        "hires_fix_refiner_pass": "second pass",
        "sdxl_crop_top": 0,
        "sdxl_crop_left": 0,
        "sdxl_refiner_low_aesthetic_score": 2.5,
        "sdxl_refiner_high_aesthetic_score": 6.0,
        "sd_vae_explanation": "<abbr title='Variational autoencoder'>VAE</abbr> is a neural network that transforms a standard <abbr title='red/green/blue'>RGB</abbr>\nimage into latent space representation and back. Latent space representation is what stable diffusion is working on during sampling\n(i.e. when the progress bar is between empty and full). For txt2img, VAE is used to create a resulting image after the sampling is finished.\nFor img2img, VAE is used to process user's input image before the sampling, and to create an image after sampling.",
        "sd_vae_checkpoint_cache": 0,
        "sd_vae": "Automatic",
        "sd_vae_overrides_per_model_preferences": true,
        "auto_vae_precision": true,
        "sd_vae_encode_method": "Full",
        "sd_vae_decode_method": "Full",
        "inpainting_mask_weight": 1.0,
        "initial_noise_multiplier": 1.0,
        "img2img_extra_noise": 0.0,
        "img2img_color_correction": false,
        "img2img_fix_steps": false,
        "img2img_background_color": "#ffffff",
        "img2img_editor_height": 720,
        "img2img_sketch_default_brush_color": "#ffffff",
        "img2img_inpaint_mask_brush_color": "#ffffff",
        "img2img_inpaint_sketch_default_brush_color": "#ffffff",
        "return_mask": false,
        "return_mask_composite": false,
        "cross_attention_optimization": "Automatic",
        "s_min_uncond": 0.0,
        "token_merging_ratio": 0.0,
        "token_merging_ratio_img2img": 0.0,
        "token_merging_ratio_hr": 0.0,
        "pad_cond_uncond": false,
        "persistent_cond_cache": true,
        "batch_cond_uncond": true,
        "use_old_emphasis_implementation": false,
        "use_old_karras_scheduler_sigmas": false,
        "no_dpmpp_sde_batch_determinism": false,
        "use_old_hires_fix_width_height": false,
        "dont_fix_second_order_samplers_schedule": false,
        "hires_fix_use_firstpass_conds": false,
        "use_old_scheduling": false,
        "interrogate_keep_models_in_memory": false,
        "interrogate_return_ranks": false,
        "interrogate_clip_num_beams": 1,
        "interrogate_clip_min_length": 24,
        "interrogate_clip_max_length": 48,
        "interrogate_clip_dict_limit": 1500,
        "interrogate_clip_skip_categories": [],
        "interrogate_deepbooru_score_threshold": 0.5,
        "deepbooru_sort_alpha": true,
        "deepbooru_use_spaces": true,
        "deepbooru_escape": true,
        "deepbooru_filter_tags": "",
        "extra_networks_show_hidden_directories": true,
        "extra_networks_hidden_models": "When searched",
        "extra_networks_default_multiplier": 1.0,
        "extra_networks_card_width": 0,
        "extra_networks_card_height": 0,
        "extra_networks_card_text_scale": 1.0,
        "extra_networks_card_show_desc": true,
        "extra_networks_add_text_separator": " ",
        "ui_extra_networks_tab_reorder": "",
        "textual_inversion_print_at_load": false,
        "textual_inversion_add_hashes_to_infotext": true,
        "sd_hypernetwork": "None",
        "localization": "None",
        "gradio_theme": "Default",
        "gradio_themes_cache": true,
        "gallery_height": "",
        "return_grid": true,
        "do_not_show_images": false,
        "send_seed": true,
        "send_size": true,
        "js_modal_lightbox": true,
        "js_modal_lightbox_initially_zoomed": true,
        "js_modal_lightbox_gamepad": false,
        "js_modal_lightbox_gamepad_repeat": 250,
        "show_progress_in_title": true,
        "samplers_in_dropdown": true,
        "dimensions_and_batch_together": true,
        "keyedit_precision_attention": 0.1,
        "keyedit_precision_extra": 0.05,
        "keyedit_delimiters": ".,\\/!?%^*;:{}=`~()",
        "keyedit_move": true,
        "quicksettings_list": [
            "sd_model_checkpoint"
        ],
        "ui_tab_order": [],
        "hidden_tabs": [],
        "ui_reorder_list": [],
        "hires_fix_show_sampler": false,
        "hires_fix_show_prompts": false,
        "disable_token_counters": false,
        "add_model_hash_to_info": true,
        "add_model_name_to_info": true,
        "add_user_name_to_info": false,
        "add_version_to_infotext": true,
        "disable_weights_auto_swap": true,
        "infotext_styles": "Apply if any",
        "show_progressbar": true,
        "live_previews_enable": true,
        "live_previews_image_format": "png",
        "show_progress_grid": true,
        "show_progress_every_n_steps": 10,
        "show_progress_type": "Approx NN",
        "live_preview_allow_lowvram_full": false,
        "live_preview_content": "Prompt",
        "live_preview_refresh_period": 1000,
        "live_preview_fast_interrupt": false,
        "hide_samplers": [],
        "eta_ddim": 0.0,
        "eta_ancestral": 1.0,
        "ddim_discretize": "uniform",
        "s_churn": 0.0,
        "s_tmin": 0.0,
        "s_tmax": 0.0,
        "s_noise": 1.0,
        "k_sched_type": "Automatic",
        "sigma_min": 0.0,
        "sigma_max": 0.0,
        "rho": 0.0,
        "eta_noise_seed_delta": 0,
        "always_discard_next_to_last_sigma": false,
        "sgm_noise_multiplier": false,
        "uni_pc_variant": "bh1",
        "uni_pc_skip_type": "time_uniform",
        "uni_pc_order": 3,
        "uni_pc_lower_order_final": true,
        "postprocessing_enable_in_main_ui": [],
        "postprocessing_operation_order": [],
        "upscaling_max_images_in_cache": 5,
        "disabled_extensions": [],
        "disable_all_extensions": "none",
        "restore_config_state_file": "",
        "sd_checkpoint_hash": "ec41bd2a8271acde4ae81cac004d9f3300e7fb0870eae8cbfe0bbc4ef8e27f91"
    },
    "Startup": {
        "total": 60.65324664115906,
        "records": {
            "initial startup": 0.0,
            "prepare environment/checks": 0.012010812759399414,
            "prepare environment/git version info": 0.1471412181854248,
            "prepare environment/torch GPU test": 15.463296175003052,
            "prepare environment/clone repositores": 0.13013839721679688,
            "prepare environment/run extensions installers/canvas-zoom": 5.649826288223267,
            "prepare environment/run extensions installers/sd-webui-ar": 0.001001119613647461,
            "prepare environment/run extensions installers/sd-webui-reactor": 16.25211524963379,
            "prepare environment/run extensions installers/sd-webui-reactor-force": 14.7218759059906,
            "prepare environment/run extensions installers": 36.624818563461304,
            "prepare environment": 52.55357360839844,
            "launcher": 0.002001523971557617,
            "import torch": 2.9597935676574707,
            "import gradio": 0.7071645259857178,
            "setup paths": 1.509448528289795,
            "import ldm": 0.0050046443939208984,
            "import sgm": 0.0,
            "initialize shared": 0.15765738487243652,
            "other imports": 1.030970573425293,
            "opts onchange": 0.0,
            "setup SD model": 0.0020017623901367188,
            "setup codeformer": 0.09859180450439453,
            "setup gfpgan": 0.02001810073852539,
            "set samplers": 0.0,
            "list extensions": 0.001001119613647461,
            "restore config state file": 0.0,
            "list SD models": 0.010009288787841797,
            "list localizations": 0.0010006427764892578,
            "load scripts/custom_code.py": 0.004003763198852539,
            "load scripts/detect_extension.py": 0.003002643585205078,
            "load scripts/img2imgalt.py": 0.001001119613647461,
            "load scripts/loopback.py": 0.0,
            "load scripts/outpainting_mk_2.py": 0.0010008811950683594,
            "load scripts/poor_mans_outpainting.py": 0.0,
            "load scripts/postprocessing_codeformer.py": 0.0,
            "load scripts/postprocessing_gfpgan.py": 0.0,
            "load scripts/postprocessing_upscale.py": 0.0010006427764892578,
            "load scripts/prompt_matrix.py": 0.0,
            "load scripts/prompts_from_file.py": 0.0,
            "load scripts/refiner.py": 0.001001119613647461,
            "load scripts/sd_upscale.py": 0.0,
            "load scripts/seed.py": 0.0,
            "load scripts/xyz_grid.py": 0.0010008811950683594,
            "load scripts/config.py": 0.0010006427764892578,
            "load scripts/sd-webui-ar.py": 0.0,
            "load scripts/console_log_patch.py": 0.013013362884521484,
            "load scripts/reactor_api.py": 0.058556556701660156,
            "load scripts/reactor_faceswap.py": 0.008007287979125977,
            "load scripts/reactor_globals.py": 0.0,
            "load scripts/reactor_helpers.py": 0.0,
            "load scripts/reactor_logger.py": 0.001001119613647461,
            "load scripts/reactor_swapper.py": 0.0010006427764892578,
            "load scripts/reactor_version.py": 0.0,
            "load scripts/rf_api.py": 0.01101064682006836,
            "load scripts/rf_console_log_patch.py": 0.006005048751831055,
            "load scripts/rf_faceswap.py": 0.007007122039794922,
            "load scripts/rf_globals.py": 0.0,
            "load scripts/rf_helpers.py": 0.0010006427764892578,
            "load scripts/rf_logger.py": 0.0,
            "load scripts/rf_swapper.py": 0.001001119613647461,
            "load scripts/rf_version.py": 0.0010008811950683594,
            "load scripts/ldsr_model.py": 0.8407993316650391,
            "load scripts/lora_script.py": 0.08557963371276855,
            "load scripts/scunet_model.py": 0.02101922035217285,
            "load scripts/swinir_model.py": 0.018016338348388672,
            "load scripts/hotkey_config.py": 0.0,
            "load scripts/extra_options_section.py": 0.0,
            "load scripts": 1.0870306491851807,
            "load upscalers": 0.0030028820037841797,
            "refresh VAE": 0.0010006427764892578,
            "refresh textual inversion templates": 0.0,
            "scripts list_optimizers": 0.0010008811950683594,
            "scripts list_unets": 0.0,
            "reload hypernetworks": 0.001001119613647461,
            "initialize extra networks": 0.014012575149536133,
            "scripts before_ui_callback": 0.0,
            "create ui": 0.3963742256164551,
            "gradio launch": 0.26275110244750977,
            "add APIs": 0.005003929138183594,
            "app_started_callback/lora_script.py": 0.0,
            "app_started_callback": 0.0
        }
    },
    "Packages": [
        "-rotobuf==3.20.0",
        "absl-py==2.0.0",
        "accelerate==0.21.0",
        "addict==2.4.0",
        "aenum==3.1.15",
        "aiofiles==23.2.1",
        "aiohttp==3.8.6",
        "aiosignal==1.3.1",
        "altair==5.1.2",
        "antlr4-python3-runtime==4.9.3",
        "anyio==3.7.1",
        "async-timeout==4.0.3",
        "attrs==23.1.0",
        "basicsr==1.4.2",
        "beautifulsoup4==4.12.2",
        "blendmodes==2022",
        "boltons==23.0.0",
        "cachetools==5.3.2",
        "certifi==2023.7.22",
        "charset-normalizer==3.3.1",
        "clean-fid==0.1.35",
        "click==8.1.7",
        "clip==1.0",
        "colorama==0.4.6",
        "coloredlogs==15.0.1",
        "contourpy==1.1.1",
        "cycler==0.12.1",
        "deprecation==2.1.0",
        "einops==0.4.1",
        "exceptiongroup==1.1.3",
        "facexlib==0.3.0",
        "fastapi==0.94.0",
        "ffmpy==0.3.1",
        "filelock==3.12.4",
        "filterpy==1.4.5",
        "flatbuffers==23.5.26",
        "fonttools==4.43.1",
        "frozenlist==1.4.0",
        "fsspec==2023.10.0",
        "ftfy==6.1.1",
        "future==0.18.3",
        "gdown==4.7.1",
        "gfpgan==1.3.8",
        "gitdb==4.0.11",
        "gitpython==3.1.32",
        "google-auth-oauthlib==1.1.0",
        "google-auth==2.23.3",
        "gradio-client==0.5.0",
        "gradio==3.41.2",
        "grpcio==1.59.0",
        "h11==0.12.0",
        "httpcore==0.15.0",
        "httpx==0.24.1",
        "huggingface-hub==0.18.0",
        "humanfriendly==10.0",
        "idna==3.4",
        "imageio==2.31.6",
        "importlib-metadata==6.8.0",
        "importlib-resources==6.1.0",
        "inflection==0.5.1",
        "jinja2==3.1.2",
        "jsonmerge==1.8.0",
        "jsonschema-specifications==2023.7.1",
        "jsonschema==4.19.1",
        "kiwisolver==1.4.5",
        "kornia==0.6.7",
        "lark==1.1.2",
        "lazy-loader==0.3",
        "lightning-utilities==0.9.0",
        "llvmlite==0.41.1",
        "lmdb==1.4.1",
        "lpips==0.1.4",
        "markdown==3.5",
        "markupsafe==2.1.3",
        "matplotlib==3.8.0",
        "mpmath==1.3.0",
        "multidict==6.0.4",
        "networkx==3.2",
        "numba==0.58.1",
        "numpy==1.23.5",
        "oauthlib==3.2.2",
        "omegaconf==2.2.3",
        "onnx==1.14.1",
        "onnxruntime-gpu==1.16.1",
        "onnxruntime==1.16.1",
        "open-clip-torch==2.20.0",
        "opencv-python==4.8.1.78",
        "orjson==3.9.9",
        "packaging==23.2",
        "pandas==2.1.1",
        "piexif==1.1.3",
        "pillow==9.5.0",
        "pip==22.2.1",
        "platformdirs==3.11.0",
        "protobuf==4.24.4",
        "psutil==5.9.5",
        "pyasn1-modules==0.3.0",
        "pyasn1==0.5.0",
        "pydantic==1.10.13",
        "pydub==0.25.1",
        "pyparsing==3.1.1",
        "pyreadline3==3.4.1",
        "pysocks==1.7.1",
        "python-dateutil==2.8.2",
        "python-multipart==0.0.6",
        "pytorch-lightning==1.9.4",
        "pytz==2023.3.post1",
        "pywavelets==1.4.1",
        "pyyaml==6.0.1",
        "realesrgan==0.3.0",
        "referencing==0.30.2",
        "regex==2023.10.3",
        "requests-oauthlib==1.3.1",
        "requests==2.31.0",
        "resize-right==0.0.2",
        "rpds-py==0.10.6",
        "rsa==4.9",
        "safetensors==0.3.1",
        "scikit-image==0.21.0",
        "scipy==1.11.3",
        "semantic-version==2.10.0",
        "sentencepiece==0.1.99",
        "setuptools==63.2.0",
        "six==1.16.0",
        "smmap==5.0.1",
        "sniffio==1.3.0",
        "soupsieve==2.5",
        "starlette==0.26.1",
        "sympy==1.12",
        "tb-nightly==2.16.0a20231024",
        "tensorboard-data-server==0.7.2",
        "tifffile==2023.9.26",
        "timm==0.9.2",
        "tokenizers==0.13.3",
        "tomesd==0.1.3",
        "tomli==2.0.1",
        "toolz==0.12.0",
        "torch==2.0.1+cu118",
        "torchdiffeq==0.2.3",
        "torchmetrics==1.2.0",
        "torchsde==0.2.5",
        "torchvision==0.15.2+cu118",
        "tqdm==4.66.1",
        "trampoline==0.1.2",
        "transformers==4.30.2",
        "typing-extensions==4.8.0",
        "tzdata==2023.3",
        "urllib3==2.0.7",
        "uvicorn==0.23.2",
        "wcwidth==0.2.8",
        "websockets==11.0.3",
        "werkzeug==3.0.1",
        "xformers==0.0.20",
        "yapf==0.40.2",
        "yarl==1.9.2",
        "zipp==3.17.0"
    ]
}

### Relevant console log

```Shell
Using cached joblib-1.3.2-py3-none-any.whl (302 kB)
Requirement already satisfied: colorama in c:\users\mybelovedpc\desktop\the ai\stable-diffusion-webui\venv\lib\site-packages (from tqdm->insightface==0.7.3) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\mybelovedpc\desktop\the ai\stable-diffusion-webui\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib->insightface==0.7.3) (1.16.0)
Using legacy 'setup.py install' for easydict, since package 'wheel' is not installed.
Building wheels for collected packages: insightface
  Building wheel for insightface (pyproject.toml): started
  Building wheel for insightface (pyproject.toml): finished with status 'error'
Failed to build insightface
Checking -=ReActor Force=- requirements... Error: The 'insightface==0.7.3' distribution was not found and is required by the application
```

### Additional information

Other extensions work fine, Reactor doesn't appear at all.

**Comment by Ummagummbo** [comment]
I am having the same issue, I have looked at the relevant console log and the only difference I can see is the 

> Building wheels for collected packages: insightface
  Building wheel for insightface (pyproject.toml): started
  Building wheel for insightface (pyproject.toml): finished with status 'error'
Failed to build insightface
Checking ReActor requirements... Error: The 'insightface==0.7.3' distribution was not found and is required by the application

Hope that helps

**Comment by diadisum** [comment]
I FIXED THE ISSUE
Here's what worked for me
1) Install Visual Basic Build Tools 2022
2) Make sure to install the option that includes c++ 
3) Open CMD and type "pip install insightface==0.7.3"
4) should install with not issues if not take a look at the error and proceed accordingly
This fixed it for me. Hopefully this can help people with similar problems!

**Comment by Gourieff** [comment]
That's right, you can find the same steps in the installation instruction https://github.com/Gourieff/sd-webui-reactor#installation
