### ISSUE TITLE
Error with Face and Age

### ISSUE THREAD

**Issue by navarisun1982** [Gourieff/sd-webui-reactor#161]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Something weird happens with reactor, when using same face and same prompt.
for first time it work great, second try, it give me this message: 

10:00:45 - ReActor - ERROR - Age Detection: No face with index = 0 was found
10:00:45 - ReActor - ERROR - Gender Detection: No face with index = 0 was found
10:00:45 - ReActor - STATUS - No target face found for 0

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### Sysinfo

windows 11
automatic1111 - 1.6

### Relevant console log

```Shell
STATUS - Working: source face index [0], target face index [0]████| 30/30 [00:15<00:00,  1.90it/s]
10:00:41 - ReActor - STATUS - Using Ready Source Face(s) Model...
10:00:41 - ReActor - STATUS - Analyzing Target Image...
10:00:43 - ReActor - STATUS - Detecting Source Face, Index = 0
10:00:43 - ReActor - STATUS - Detected: -56- y.o. Male
10:00:43 - ReActor - STATUS - Detecting Target Face, Index = 0
10:00:43 - ReActor - ERROR - Age Detection: No face with index = 0 was found
10:00:43 - ReActor - ERROR - Gender Detection: No face with index = 0 was found
10:00:43 - ReActor - STATUS - Trying to halve 'det_size' parameter
10:00:45 - ReActor - ERROR - Age Detection: No face with index = 0 was found
10:00:45 - ReActor - ERROR - Gender Detection: No face with index = 0 was found
10:00:45 - ReActor - STATUS - No target face found for 0
```

**Comment by Gourieff** [comment]
> 10:00:43 - ReActor - STATUS - Detecting Target Face, Index = 0
10:00:43 - ReActor - ERROR - Age Detection: No face with index = 0 was found
10:00:43 - ReActor - ERROR - Gender Detection: No face with index = 0 was found

This means that there were no any faces on the generated target image

**Comment by navarisun1982** [comment]
there is, but because the model i work on is caricature, it doesn't seam to recognize this kind of faces.
but i figured out that if i have large enough images and work on img2img instead of txt2img and choose gender, it works ok.

**Comment by wallyma** [comment]
I also. generated photo.

17:42:03 - ReActor - `STATUS` - Analyzing Source Image...
17:42:05 - ReActor - STATUS - Analyzing Target Image...
17:42:06 - ReActor - STATUS - Detecting Source Face, Index = 1
17:42:06 - ReActor - ERROR - Age Detection: No face with index = 1 was found
17:42:06 - ReActor - ERROR - Gender Detection: No face with index = 1 was found
17:42:06 - ReActor - STATUS - No source face(s) in the provided Index

**Comment by Gourieff** [comment]
> 17:42:06 - ReActor - STATUS - Detecting Source Face, Index = 1

Are you sure you set the face index right?
Index = 1 is the second face not the first one (the 1st one is Index = 0)

https://github.com/Gourieff/sd-webui-reactor-force#face-indexes

**Comment by hollowfatemusic** [comment]
is this problem solved? I'm having the same issue and haven't found any other conversation about it

**Comment by navarisun1982** [comment]
> is this problem solved? I'm having the same issue and haven't found any other conversation about it

yes for me its solved, now i choose the gender from reactor and it works, also choosing adetailer helps

**Comment by MadChaos** [comment]
There's something to it. It worked fine with Reactor at first, but then I discovered a CUDA version, so I reinstalled A1111, and it gave me this error only.

**Comment by drdancm** [comment]
Age and Gender identification fails approximately 1 out of 30-40 instances, depending of course on a particular context (hair length for females and or male subjects. I find it best to disable gender and overall it produces less need to go back and deal with things manually rather than in batch mode. This happens when everything is working beautifully otherwise.

**Comment by chris-sadighgroup** [comment]
same issue here, wont recognize any face anymore

**Comment by Gourieff** [comment]
> same issue here, wont recognize any face anymore

Could you provide a log and your workflow?

**Comment by hollowfatemusic** [comment]
I think I solved it somehow. First, I had ReActor Force installed, not the normal reactor. The error was with this extension. Care to say that I never had Roop installed before. So the first thing I do, was install roop as an alternative to solve it quick. I also deselec Force on the extensions. After that, I deleted ReActor Force and installed the ReActor (normal) extension. I launched auto1111 and then, ReActor and Roop seem no compatible. Closed webUi. After, I deleted Roop and re-launched auto1111, and the issue was no more, now ReActor swaps faces like if nothing ever happened. The reason why I post this written podcast is because at some point it fixed for me, so it might as well do so, but you need to know every step that I made.

**Comment by onlyreportingissues** [comment]
Saw this issue today. Appeared with some samplers, not all. Disappeared again when I chose other samplers.

**Comment by drdancm** [comment]
I also experienced some difficulty switching from Reactor-Force to just Reactor. When tried to install the Reactor extension, the message said it was already installed and failed to do it. I had to delete Reactor-Force the extension from the extensions folder, and then I was finally able to get plain Reactor from the extensions menu.

**Comment by navarisun1982** [comment]
> 9:08:30 - ReActor - STATUS - Working: source face index [0], target face index [0]
> 19:08:30 - ReActor - STATUS - Analyzing Source Image...
> 
> How exactly did you solve it

Just updated the plugin, that was a long time ago
