### ISSUE TITLE
fix installer cause it does NOT create inswapper folder inside of auto1111 models folder, and so by default this extension wont work

### ISSUE THREAD

**Issue by 2blackbar** [Gourieff/sd-webui-reactor#164]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

installed in webui itself by linkint this repo0, then restarted

### Steps to reproduce the problem

It would not swap, because there was no inswapper folder created to store actual model, would be nice if it would download onx model on its own really, its not a big file
So.. i created inswapper folder on my own ( which should not be required) and placed onxx model inside, now it works after restarting webui

### Sysinfo

win 10

### Relevant console log

```Shell
.
```

**Comment by Gourieff** [comment]
If you do everything right - it creates the folder "models\insightface" and automatically downloads all the required models into it
I've just tested from the scratch for A1111 (venv and portable)
But if you use StabilityMatrix - you could read here https://github.com/Gourieff/sd-webui-reactor/issues/129#issuecomment-1768210875
