### ISSUE TITLE
Batch Processing Fails to Produce any results

### ISSUE THREAD

**Issue by drdancm** [Gourieff/sd-webui-reactor#173]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Batch Files work fine almost invariably. I have only one other time had it refuse to process any output.

This time it just fails for no reason that I understand.

I'm showing example where it works fine, the last 5 lines (shown BOLD and ITALICIZED) is an error I have never seen before:

0: 640x448 1 eyes, 15.0ms
Speed: 4.0ms preprocess, 15.0ms inference, 14.0ms postprocess per image at shape (1, 3, 640, 448)
100%|##########| 9/9 [00:14<00:00,  1.62s/it]
02:29:07 - ReActor Force - STATUS - Working: source face index [0], target face index [0]
02:29:07 - ReActor Force - STATUS - Analyzing Source Image...
02:29:07 - ReActor Force - STATUS - Analyzing Target Image...
02:29:07 - ReActor Force - STATUS - Detecting Source Face, Index = 0
02:29:07 - ReActor Force - STATUS - Detected: -22- y.o. Male
02:29:07 - ReActor Force - STATUS - Detecting Target Face, Index = 0
02:29:07 - ReActor Force - STATUS - Detected: -24- y.o. Female
02:29:07 - ReActor Force - STATUS - Swapping Source into Target
02:29:09 - ReActor Force - STATUS - Restoring the face with CodeFormer
Total progress: 100%|██████████| 1/1 [00:27<00:00, 27.13s/it]t]
03:46:41 - ReActor Force - STATUS - Working: source face index [0], target face index [0]
03:46:41 - ReActor Force - STATUS - Analyzing Source Image...
03:46:41 - ReActor Force - STATUS - Analyzing Target Image...
03:46:41 - ReActor Force - STATUS - Detecting Source Face, Index = 0
03:46:41 - ReActor Force - STATUS - Detected: -22- y.o. Male
03:46:41 - ReActor Force - STATUS - Detecting Target Face, Index = 0
03:46:41 - ReActor Force - STATUS - Detected: -36- y.o. Female
03:46:41 - ReActor Force - STATUS - Swapping Source into Target
03:46:44 - ReActor Force - STATUS - Restoring the face with CodeFormer
100%|##########| 1/1 [00:01<00:00,  1.66s/it]

0: 640x448 1 face, 15.0ms
Speed: 4.0ms preprocess, 15.0ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 448)
[-] ADetailer: nothing detected on image 1 with 1st settings.

0: 640x448 2 eyess, 15.0ms
Speed: 4.0ms preprocess, 15.0ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 448)
100%|##########| 9/9 [00:15<00:00,  1.70s/it]
100%|##########| 9/9 [00:14<00:00,  1.63s/it]
03:47:30 - ReActor Force - STATUS - Working: source face index [0], target face index [0]
03:47:30 - ReActor Force - STATUS - Analyzing Source Image...
03:47:30 - ReActor Force - STATUS - Analyzing Target Image...
03:47:30 - ReActor Force - STATUS - Detecting Source Face, Index = 0
03:47:30 - ReActor Force - STATUS - Detected: -22- y.o. Male
03:47:30 - ReActor Force - STATUS - Detecting Target Face, Index = 0
03:47:30 - ReActor Force - STATUS - Detected: -30- y.o. Female
03:47:30 - ReActor Force - STATUS - Swapping Source into Target
03:47:33 - ReActor Force - STATUS - Restoring the face with CodeFormer
Total progress: 100%|██████████| 1/1 [00:46<00:00, 46.13s/it]t]
_**Will process 0 images, creating 1 new images for each.
Will process 0 images, creating 1 new images for each.
Will process 0 images, creating 1 new images for each.
Will process 0 images, creating 1 new images for each.
Will process 0 images, creating 1 new images for each.**_

### Steps to reproduce the problem

Input Folder:

D:\DST Photos\Models & Photography\AmandaLeigh-5D-22jul08\FSwp\

Filenames in the folder are all the same except for last 4 digits
AmandaLeigh-5D-22jul08  4417.JPG
AmandaLeigh-5D-22jul08  4359.JPG
AmandaLeigh-5D-22jul08  4361.JPG

I ran a test with 3 files by putting 01 , 02, 03, in front of the file names, but that made no difference.

There is no problem processing each file one by one manually.

### Sysinfo

Windows 10 64bit, Firefox v 119.0
Reactor Force  v 0.4.3

### Relevant console log

```Shell
As I said Batch processing always, but for one time, worked for me. I fixed that one problem by putting a space right before the last 4 digits of the file name.
```

**Comment by Gourieff** [comment]
> AmandaLeigh-5D-22jul08 4417.JPG
AmandaLeigh-5D-22jul08 4359.JPG
AmandaLeigh-5D-22jul08 4361.JPG

What's the resolution of these images?

**Comment by drdancm** [comment]
I haven't gone back to these particular images, but with some other ones I was able to improve them using ADetailer (face, eyes.pt). However, some of these later images are screwed up even with the best configuration of ADetailer that I have tested.

So, my question is, is this caused by the 128onnx? the lack of higher, quality resolution? and there is nothing you can do with Reactor, or is there still something that can improved?  Could you please explain your understanding of this problem.

My other question is why results get poorer and poorer as the original face approaches a profile view. This is a huge problem with identification and assigning names to face photos ever since Google Picasa introduced face identification to the public.

I would guess this has to do with failing to train the basic components at the very start. Am I right?

In any case I am very, very thankful for all the time and effort you have put into making Reactor. I get so much enjoyment out of this amazing tool.

Thanks

**Comment by drdancm** [comment]
I have not had a repeat of this problem, so I'm not going to worry about it - just a rare unusual fluke I guess.
