### ISSUE TITLE
Install fails Automatic1111

### ISSUE THREAD

**Issue by WeirdScienceX** [Gourieff/sd-webui-reactor#178]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Using the extensions tab installed Reactor

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### Sysinfo

[sysinfo-2023-11-05-18-21.txt](https://github.com/Gourieff/sd-webui-reactor/files/13260468/sysinfo-2023-11-05-18-21.txt)

### Relevant console log

```Shell
*** Error running install.py for extension C:\AI\stable-diffusion-webui\extensions\sd-webui-reactor.
*** Command: "C:\AI\stable-diffusion-webui\venv\Scripts\python.exe" "C:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\install.py"
*** Error code: 1
*** stderr: Traceback (most recent call last):
***   File "C:\Python310\lib\shutil.py", line 816, in move
***     os.rename(src, real_dst)
*** FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\AI\\stable-diffusion-webui\\models\\roop\\inswapper_128.onnx' -> 'C:\\AI\\stable-diffusion-webui\\models\\insightface\\inswapper_128.onnx'
***
*** During handling of the above exception, another exception occurred:
***
*** Traceback (most recent call last):
***   File "C:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\install.py", line 32, in <module>
***     shutil.move(os.path.join(models_dir_old, file), os.path.join(models_dir, file))
***   File "C:\Python310\lib\shutil.py", line 836, in move
***     copy_function(src, real_dst)
***   File "C:\Python310\lib\shutil.py", line 434, in copy2
***     copyfile(src, dst, follow_symlinks=follow_symlinks)
***   File "C:\Python310\lib\shutil.py", line 256, in copyfile
***     with open(dst, 'wb') as fdst:
*** FileNotFoundError: [Errno 2] No such file or directory: 'C:\\AI\\stable-diffusion-webui\\models\\insightface\\inswapper_128.onnx'
```

**Comment by darktar** [comment]
try download and copy inswapper_128.onnx by your own 
this line:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\AI\\stable-diffusion-webui\\models\\insightface\\inswapper_128.onnx'
says that you don't  have the file..

**Comment by nyukers** [comment]
It's strange that it doesn't want to see that file in 'C:\\AI\\stable-diffusion-webui\\models\\roop\\'

**Comment by aizazzaheer** [comment]
Getting the same issue. It does not see the inswapper_128.onnx model from /models/roop nor does it pickup the one from /models/insightface/inswapper_128.onnx  (even if I create it manually)
