### ISSUE TITLE
[SOLVED] Error when trying to swap face (ORT Error)

### ISSUE THREAD

**Issue by oliverban** [Gourieff/sd-webui-reactor#180]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Worked fine before. Now I get an error when putting in a simple faceswap. Something about an ORT error, guess that's the GPU implementation. I have gone into settings and tried setting it back to CPU but get the same error after "Save" and "Restart UI".

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### Sysinfo

Win10
A1111 (latest)
ReActor (latest, reinstalled 2 times, all dependencies are active and listed)
- I have disabled all other extensions but did not work -

### Relevant console log

```Shell
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 32.3s (prepare environment: 16.4s, import torch: 7.2s, import gradio: 0.9s, setup paths: 0.9s, initialize shared: 0.3s, other imports: 0.6s, setup codeformer: 0.1s, load scripts: 4.5s, create ui: 1.1s, gradio launch: 0.3s).
Loading VAE weights specified in settings: C:\Users\Oliver\Documents\Github\stable-diffusion-webui\models\VAE\vae-ft-MSE-840000-ema-pruned.safetensors
Applying attention optimization: sdp-no-mem... done.
Model loaded in 10.5s (load weights from disk: 1.3s, create model: 2.2s, apply weights to model: 4.2s, apply half(): 1.3s, load VAE: 0.3s, calculate empty prompt: 1.1s).
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:08<00:00,  3.40it/s]
18:16:37 - ReActor - STATUS - Working: source face index [0], target face index [0]
18:16:37 - ReActor - STATUS - Analyzing Source Image...
*** Error running postprocess_image: C:\Users\Oliver\Documents\Github\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py
    Traceback (most recent call last):
      File "C:\Users\Oliver\Documents\Github\stable-diffusion-webui\modules\scripts.py", line 675, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "C:\Users\Oliver\Documents\Github\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 433, in postprocess_image
        result, output, swapped = swap_face(
      File "C:\Users\Oliver\Documents\Github\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 333, in swap_face
        source_faces = analyze_faces(source_img)
      File "C:\Users\Oliver\Documents\Github\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 225, in analyze_faces
        face_analyser = copy.deepcopy(getAnalysisModel())
      File "c:\python\lib\copy.py", line 172, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "c:\python\lib\copy.py", line 271, in _reconstruct
        state = deepcopy(state, memo)
      File "c:\python\lib\copy.py", line 146, in deepcopy
        y = copier(x, memo)
      File "c:\python\lib\copy.py", line 231, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "c:\python\lib\copy.py", line 146, in deepcopy
        y = copier(x, memo)
      File "c:\python\lib\copy.py", line 231, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "c:\python\lib\copy.py", line 172, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "c:\python\lib\copy.py", line 271, in _reconstruct
        state = deepcopy(state, memo)
      File "c:\python\lib\copy.py", line 146, in deepcopy
        y = copier(x, memo)
      File "c:\python\lib\copy.py", line 231, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "c:\python\lib\copy.py", line 172, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "c:\python\lib\copy.py", line 273, in _reconstruct
        y.__setstate__(state)
      File "C:\Users\Oliver\Documents\Github\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 33, in __setstate__
        self.__init__(model_path)
      File "C:\Users\Oliver\Documents\Github\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
        super().__init__(model_path, **kwargs)
      File "C:\Users\Oliver\Documents\Github\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 396, in __init__
        raise e
      File "C:\Users\Oliver\Documents\Github\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
        self._create_inference_session(providers, provider_options, disabled_optimizers)
      File "C:\Users\Oliver\Documents\Github\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 415, in _create_inference_session
        raise ValueError(
    ValueError: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)

---
```

**Comment by Gourieff** [comment]
Could you provide `pip list` of your VENV?

**Comment by oliverban** [comment]
`Microsoft Windows [Version 10.0.19045.3570]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Oliver\Documents\Github\stable-diffusion-webui>venv\Scripts\activate

(venv) C:\Users\Oliver\Documents\Github\stable-diffusion-webui>pip list
WARNING: Ignoring invalid distribution -rotobuf (c:\users\oliver\documents\github\stable-diffusion-webui\venv\lib\site-packages)
Package                      Version
---------------------------- --------------------
absl-py                      1.4.0
accelerate                   0.21.0
addict                       2.4.0
aenum                        3.1.15
aiofiles                     23.1.0
aiohttp                      3.8.5
aiosignal                    1.3.1
albumentations               1.3.1
altair                       5.0.1
antlr4-python3-runtime       4.9.3
anyio                        3.7.1
appdirs                      1.4.4
astunparse                   1.6.3
async-timeout                4.0.2
attrs                        23.1.0
audioread                    3.0.0
av                           10.0.0
basicsr                      1.4.2
beautifulsoup4               4.12.2
bidict                       0.22.1
blendmodes                   2022
blip-ci                      0.0.5
boltons                      23.0.0
cachetools                   5.3.1
cairocffi                    1.6.1
CairoSVG                     2.7.1
certifi                      2023.7.22
cffi                         1.15.1
chardet                      5.2.0
charset-normalizer           3.2.0
clean-fid                    0.1.35
click                        8.1.6
clip                         1.0
clip-interrogator            0.6.0
colorama                     0.4.6
coloredlogs                  15.0.1
contourpy                    1.1.0
controlnet-aux               0.0.3
cssselect2                   0.7.0
cycler                       0.11.0
Cython                       3.0.2
decorator                    4.4.2
defusedxml                   0.7.1
deprecation                  2.1.0
diffusers                    0.21.4
dlib-bin                     19.24.2
dm-tree                      0.1.8
dynamicprompts               0.29.0
easydict                     1.10
einops                       0.4.1
exceptiongroup               1.1.2
facexlib                     0.3.0
fairscale                    0.4.13
fastapi                      0.94.0
ffmpy                        0.3.1
filelock                     3.12.2
filterpy                     1.4.5
Flask                        2.2.3
Flask-Cors                   4.0.0
Flask-SocketIO               5.3.5
flaskwebgui                  0.3.5
flatbuffers                  23.5.26
fonttools                    4.41.1
freetype-py                  2.4.0
frozenlist                   1.4.0
fsspec                       2023.6.0
ftfy                         6.1.1
future                       0.18.3
fvcore                       0.1.5.post20221221
gast                         0.5.4
gdown                        4.7.1
gfpgan                       1.3.8
gitdb                        4.0.10
GitPython                    3.1.32
google-auth                  2.22.0
google-auth-oauthlib         1.0.0
google-pasta                 0.2.0
gradient-free-optimizers     1.3.0
gradio                       3.41.2
gradio_client                0.5.0
grpcio                       1.56.2
h11                          0.12.0
h5py                         3.10.0
hsluv                        5.0.3
httpcore                     0.15.0
httpx                        0.24.1
huggingface-hub              0.17.1
humanfriendly                10.0
hyperactive                  4.5.0
idna                         3.4
ifnude                       0.0.3
image-reward                 1.0
imageio                      2.31.1
imageio-ffmpeg               0.4.8
importlib-metadata           6.8.0
importlib-resources          6.0.1
imutils                      0.5.4
inflection                   0.5.1
insightface                  0.7.3
iopath                       0.1.9
itsdangerous                 2.1.2
Jinja2                       3.1.2
joblib                       1.3.1
jsonmerge                    1.8.0
jsonschema                   4.18.4
jsonschema-specifications    2023.7.1
keras                        2.14.0
keras-core                   0.1.7
kiwisolver                   1.4.4
kornia                       0.6.7
lama-cleaner                 1.2.3
lark                         1.1.2
lazy_loader                  0.3
libclang                     16.0.6
librosa                      0.10.0.post2
lightning-utilities          0.9.0
linkify-it-py                2.0.2
llvmlite                     0.40.1
lmdb                         1.4.1
lml                          0.1.0
loguru                       0.7.0
lpips                        0.1.4
lxml                         4.9.3
Markdown                     3.4.4
markdown-it-py               2.2.0
MarkupSafe                   2.1.3
matplotlib                   3.7.2
mdit-py-plugins              0.3.3
mdurl                        0.1.2
mediapipe                    0.10.7
memory-tempfile              2.2.3
ml-dtypes                    0.2.0
moviepy                      1.0.2
mpmath                       1.3.0
msgpack                      1.0.5
msgspec                      0.18.2
multidict                    6.0.4
namex                        0.0.7
networkx                     3.1
numba                        0.57.1
numexpr                      2.8.4
numpy                        1.23.5
oauthlib                     3.2.2
omegaconf                    2.2.3
onnx                         1.14.0
onnxruntime                  1.15.0
onnxruntime-gpu              1.15.1
open-clip-torch              2.20.0
opencv-contrib-python        4.8.0.74
opencv-python                4.8.1.78
opencv-python-headless       4.8.0.74
opennsfw2                    0.11.0
opt-einsum                   3.3.0
orjson                       3.9.2
packaging                    23.1
pandas                       1.5.3
piexif                       1.1.3
Pillow                       9.5.0
PIMS                         0.6.0
pip                          23.3.1
platformdirs                 3.10.0
pooch                        1.6.0
portalocker                  2.7.0
prettytable                  3.9.0
proglog                      0.1.10
protobuf                     3.20.3
psutil                       5.9.5
py-cpuinfo                   9.0.0
pyasn1                       0.5.0
pyasn1-modules               0.3.0
pycparser                    2.21
pydantic                     1.10.12
pydub                        0.25.1
pyexcel                      0.7.0
pyexcel-io                   0.6.6
pygal                        3.0.0
Pygments                     2.15.1
PyMatting                    1.1.8
pyparsing                    3.0.9
PyQt5                        5.15.9
PyQt5-Qt5                    5.15.2
PyQt5-sip                    12.12.2
pyreadline3                  3.4.1
PySocks                      1.7.1
python-dateutil              2.8.2
python-engineio              4.5.1
python-multipart             0.0.6
python-socketio              5.8.0
pytorch-lightning            1.9.4
pytz                         2023.3
PyWavelets                   1.4.1
pywin32                      306
PyYAML                       6.0.1
qudida                       0.0.4
realesrgan                   0.3.0
referencing                  0.30.0
regex                        2023.6.3
rembg                        2.0.50
reportlab                    4.0.4
requests                     2.31.0
requests-oauthlib            1.3.1
resize-right                 0.0.2
rich                         13.5.0
rpds-py                      0.9.2
rsa                          4.9
safetensors                  0.3.1
scikit-image                 0.21.0
scikit-learn                 1.3.0
scipy                        1.11.1
seaborn                      0.12.2
search-data-collector        0.4.0
segment-anything             1.0
semantic-version             2.10.0
sentencepiece                0.1.99
setuptools                   65.5.0
simple-websocket             0.10.1
six                          1.16.0
slicerator                   1.1.0
smmap                        5.0.0
sniffio                      1.3.0
sounddevice                  0.4.6
soundfile                    0.12.1
soupsieve                    2.4.1
soxr                         0.3.5
starlette                    0.26.1
svglib                       1.5.1
sympy                        1.12
tabulate                     0.9.0
tb-nightly                   2.14.0a20230730
tensorboard                  2.14.1
tensorboard-data-server      0.7.1
tensorflow                   2.14.0
tensorflow-estimator         2.14.0
tensorflow-intel             2.14.0
tensorflow-io-gcs-filesystem 0.31.0
termcolor                    2.3.0
texttable                    1.6.7
thop                         0.1.1.post2209072238
threadpoolctl                3.2.0
tifffile                     2023.7.18
timm                         0.9.2
tinycss2                     1.2.1
tokenizers                   0.13.3
tomesd                       0.1.3
tomli                        2.0.1
tomli_w                      1.0.0
toolz                        0.12.0
torch                        2.0.1+cu118
torchdiffeq                  0.2.3
torchmetrics                 1.0.1
torchsde                     0.2.5
torchvision                  0.15.2+cu118
tqdm                         4.66.1
trampoline                   0.1.2
transformers                 4.30.2
transforms3d                 0.4.1
trimesh                      3.22.5
typing_extensions            4.7.1
tzdata                       2023.3
uc-micro-py                  1.0.2
ultralytics                  8.0.200
urllib3                      1.26.16
uvicorn                      0.23.1
vispy                        0.13.0
wcwidth                      0.2.6
webencodings                 0.5.1
websockets                   11.0.3
Werkzeug                     2.3.6
wheel                        0.41.0
whichcraft                   0.6.1
win32-setctime               1.1.0
wrapt                        1.14.1
wsproto                      1.2.0
xformers                     0.0.20
yacs                         0.1.8
yapf                         0.40.1
yarl                         1.9.2
zipp                         3.16.2

(venv) C:\Users\Oliver\Documents\Github\stable-diffusion-webui>`

**Comment by oliverban** [comment]
> Could you provide `pip list` of your VENV?

List provided above! :)

**Comment by Gourieff** [comment]
> onnxruntime 1.15.0
onnxruntime-gpu 1.15.1

Not supported version of ORT
1. Only one version of ORT should be installed
2. ReActor works with 1.16.1 version

Probably, another extensions installs 1.15.1 every time you start A1111, investigate it and disable it or update, and then (from activated VENV):

      pip uninstall -y onnxruntime onnxruntime-gpu

and then run A1111 to let ReActor install ORT or ORT-GPU 1.16.1 according to your platform

**Comment by nyukers** [comment]
And FaceSwapLab or ROOP will not works after update ORT?

**Comment by oliverban** [comment]
> > onnxruntime 1.15.0
> > onnxruntime-gpu 1.15.1
> 
> Not supported version of ORT
> 
> 1. Only one version of ORT should be installed
> 2. ReActor works with 1.16.1 version
> 
> Probably, another extensions installs 1.15.1 every time you start A1111, investigate it and disable it or update, and then (from activated VENV):
> 
> ```
>   pip uninstall -y onnxruntime onnxruntime-gpu
> ```
> 
> and then run A1111 to let ReActor install ORT or ORT-GPU 1.16.1 according to your platform

Yepp, works now, thanks! :)

**Comment by Gourieff** [comment]
> And FaceSwapLab or ROOP will not works after update ORT?

FaceSwapLab will work, Roop will not

**Comment by nyukers** [comment]
> > And FaceSwapLab or ROOP will not works after update ORT?
> 
> FaceSwapLab will work, Roop will not

I have now that FaceSwapLab works, Roop and Reactor don't work.
