### ISSUE TITLE
ERROR occured from installation

### ISSUE THREAD

**Issue by waldolin** [Gourieff/sd-webui-reactor#192]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

first time install this extensions,
and here is the information
===========
Installing requirements for Ebsynth Utility
current transparent-background 1.2.9
Installing requirements for Ebsynth Utility
Installing requirements for Ebsynth Utility
*** Error running install.py for extension C:\Users\lin\stable-diffusion-webui-directml\extensions\sd-webui-reactor.
*** Command: "C:\Users\lin\stable-diffusion-webui-directml\venv\Scripts\python.exe" "C:\Users\lin\stable-diffusion-webui-directml\extensions\sd-webui-reactor\install.py"
*** Error code: 1
*** stderr: Traceback (most recent call last):
***   File "C:\Users\lin\stable-diffusion-webui\python\lib\shutil.py", line 815, in move
***     os.rename(src, real_dst)
*** FileNotFoundError: [WinError 3] tΧ䤣w|C: 'C:\\Users\\lin\\stable-diffusion-webui-directml\\models\\roop\\inswapper_128.onnx' -> 'C:\\Users\\lin\\stable-diffusion-webui-directml\\models\\insightface\\inswapper_128.onnx'
***
*** During handling of the above exception, another exception occurred:
***
*** Traceback (most recent call last):
***   File "C:\Users\lin\stable-diffusion-webui-directml\extensions\sd-webui-reactor\install.py", line 32, in <module>
***     shutil.move(os.path.join(models_dir_old, file), os.path.join(models_dir, file))
***   File "C:\Users\lin\stable-diffusion-webui\python\lib\shutil.py", line 835, in move
***     copy_function(src, real_dst)
***   File "C:\Users\lin\stable-diffusion-webui\python\lib\shutil.py", line 434, in copy2
***     copyfile(src, dst, follow_symlinks=follow_symlinks)
***   File "C:\Users\lin\stable-diffusion-webui\python\lib\shutil.py", line 256, in copyfile
***     with open(dst, 'wb') as fdst:
*** FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\lin\\stable-diffusion-webui-directml\\models\\insightface\\inswapper_128.onnx'

====
it seems not install, i wait for 30 mins, 

### Steps to reproduce the problem

1. i have checked github, Go toStable Diffusion webui   ....
2.  pip list
insightface                  0.7.3
3. use Stable Diffusion webui  
install from URL ....
4. ...i reopen stable diffusion,
5. it can not open stable diffusion
6. it shows 
ReActor preheating... Device: CPU
7.i delete the file of  sd-webui-reactor
it can open stable diffusion

### Sysinfo

 python: 3.10.7  •  torch: 2.0.0+cpu  •  xformers: N/A  •  gradio: 3.41.2  •  checkpoint: [7f96a1a9ca](https://google.com/search?q=7f96a1a9ca9b3a3242a9ae95d19284f0d2da8d5282b42d2d974398bf7663a252)

CPU:I5-13600K
RAM:64G
AMD6950XT
### Relevant console log

```Shell
Installing requirements for Ebsynth Utility
current transparent-background 1.2.9
Installing requirements for Ebsynth Utility
Installing requirements for Ebsynth Utility
*** Error running install.py for extension C:\Users\lin\stable-diffusion-webui-directml\extensions\sd-webui-reactor.
*** Command: "C:\Users\lin\stable-diffusion-webui-directml\venv\Scripts\python.exe" "C:\Users\lin\stable-diffusion-webui-directml\extensions\sd-webui-reactor\install.py"
*** Error code: 1
*** stderr: Traceback (most recent call last):
***   File "C:\Users\lin\stable-diffusion-webui\python\lib\shutil.py", line 815, in move
***     os.rename(src, real_dst)
*** FileNotFoundError: [WinError 3] tΧ䤣w|C: 'C:\\Users\\lin\\stable-diffusion-webui-directml\\models\\roop\\inswapper_128.onnx' -> 'C:\\Users\\lin\\stable-diffusion-webui-directml\\models\\insightface\\inswapper_128.onnx'
***
*** During handling of the above exception, another exception occurred:
***
*** Traceback (most recent call last):
***   File "C:\Users\lin\stable-diffusion-webui-directml\extensions\sd-webui-reactor\install.py", line 32, in <module>
***     shutil.move(os.path.join(models_dir_old, file), os.path.join(models_dir, file))
***   File "C:\Users\lin\stable-diffusion-webui\python\lib\shutil.py", line 835, in move
***     copy_function(src, real_dst)
***   File "C:\Users\lin\stable-diffusion-webui\python\lib\shutil.py", line 434, in copy2
***     copyfile(src, dst, follow_symlinks=follow_symlinks)
***   File "C:\Users\lin\stable-diffusion-webui\python\lib\shutil.py", line 256, in copyfile
***     with open(dst, 'wb') as fdst:
*** FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\lin\\stable-diffusion-webui-directml\\models\\insightface\\inswapper_128.onnx'
```

**Comment by Gourieff** [comment]
Try to download the model file from here https://github.com/facefusion/facefusion-assets/releases/download/models/inswapper_128.onnx and put it to the `models\insightface` folder
