### ISSUE TITLE
After using ReActor Force once, sdweiui will not be able to run again, it seems that the GPU graphics memory occupied by ReActor Force has not been released

### ISSUE THREAD

**Issue by jianghuasheng** [Gourieff/sd-webui-reactor#213]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

After using ReActor Force once, sdweiui will not be able to run again, it seems that the GPU graphics memory occupied by ReActor Force has not been released.
Occasionally, img2img can run, but it takes a long time.

### Steps to reproduce the problem

1.If ReActor Force is not used, running img2img multiple times is normal;
2.After starting to use ReActor Force once, the first time it ran normally, and the second time, regardless of whether ReActor was turned on or not, when img2img, the GPUS suddenly skyrocketed to 100%, causing the graphics memory to burst.
![微信截图_20231125191138](https://github.com/Gourieff/sd-webui-reactor/assets/20856332/b392c542-6029-447d-a14a-c1210f9dba47)
![微信截图_20231125191244](https://github.com/Gourieff/sd-webui-reactor/assets/20856332/48430f63-f362-4d95-9916-9bb2cce50d5c)
![微信截图_20231125191254](https://github.com/Gourieff/sd-webui-reactor/assets/20856332/6a7c5397-6a9c-41f5-9399-797fca91548f)
![微信截图_20231125191320](https://github.com/Gourieff/sd-webui-reactor/assets/20856332/430b945c-a965-4bc2-8302-fec5b0efb43a)
![微信截图_20231125192710](https://github.com/Gourieff/sd-webui-reactor/assets/20856332/75e356fb-3601-42d9-9594-a4890b27f65a)

### Sysinfo

version: [v1.5.2]•  python: 3.10.11  •  torch: 2.0.1+cu118  •  xformers: 0.0.21
windows11,RTX 3050 4G,RAM 32G

### Relevant console log

```Shell
torch.cuda.OutOfMemoryError: Allocation on device 0 would exceed allowed memory. (out of memory)
    Currently allocated     : 1.03 GiB
    Requested               : 128.00 MiB
    Device limit            : 4.00 GiB
    Free (according to CUDA): 0 bytes
    PyTorch limit (set by user-supplied memory fraction)
                            : 17179869184.00 GiB
```

**Comment by Gourieff** [comment]
ReActor Force is deprecated
Delete it and use this version instead

> RTX 3050 4G

In this version of ReActor you can set CPU Execution Provider (in the Settings tab) instead of CUDA to reduce VRAM usage

**Comment by jianghuasheng** [comment]
您好，您的邮件已经收到！感谢您的来信，祝您生活愉快。。。

**Comment by jianghuasheng** [comment]
您好，您的邮件已经收到！感谢您的来信，祝您生活愉快。。。
