### ISSUE TITLE
'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by andysingal** [Gourieff/sd-webui-reactor#221]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

```
Error running postprocess_image: /workspace/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_faceswap.py
    Traceback (most recent call last):
      File "/workspace/stable-diffusion-webui/modules/scripts.py", line 675, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "/workspace/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_faceswap.py", line 571, in postprocess_image
        result, output, swapped = swap_face(
      File "/workspace/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_swapper.py", line 470, in swap_face
        swapped_image = face_swapper.get(result, target_face, source_face)
    AttributeError: 'NoneType' object has no attribute 'get'
```

### Steps to reproduce the problem

<img width="857" alt="Screenshot 2023-11-27 at 11 09 30 AM" src="https://github.com/Gourieff/sd-webui-reactor/assets/20493493/0092e92c-4382-4cf1-9d3d-14da87a44e3c">

target images :
<img width="439" alt="Screenshot 2023-11-27 at 11 10 09 AM" src="https://github.com/Gourieff/sd-webui-reactor/assets/20493493/c22616b1-6dfa-41f2-9b73-c1b39fee2111">

### Sysinfo

RTX 3090

### Relevant console log

```Shell
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 44/44 [00:11<00:00,  3.67it/s]
15:54:34 - ReActor - STATUS - Working: source face index [0], target face index [0]                                                             | 44/176 [00:11<00:37,  3.50it/s]
15:54:34 - ReActor - STATUS - Using Hashed Source Face(s) Model...
15:54:34 - ReActor - STATUS - Analyzing Target Image...
15:54:36 - ReActor - STATUS - Detecting Source Face, Index = 0
15:54:36 - ReActor - STATUS - Source Face 0: Detected Gender -F-
15:54:36 - ReActor - STATUS - OK - Detected Gender matches Condition
15:54:36 - ReActor - STATUS - Detected: -23- y.o. Female
15:54:36 - ReActor - STATUS - Detecting Target Face, Index = 0
15:54:36 - ReActor - STATUS - Target Face 0: Detected Gender -F-
15:54:36 - ReActor - STATUS - OK - Detected Gender matches Condition
15:54:36 - ReActor - STATUS - Detected: -27- y.o. Female
15:54:36 - ReActor - STATUS - Swapping Source into Target
*** Error running postprocess_image: /workspace/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_faceswap.py
    Traceback (most recent call last):
      File "/workspace/stable-diffusion-webui/modules/scripts.py", line 675, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "/workspace/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_faceswap.py", line 571, in postprocess_image
        result, output, swapped = swap_face(
      File "/workspace/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_swapper.py", line 470, in swap_face
        swapped_image = face_swapper.get(result, target_face, source_face)
    AttributeError: 'NoneType' object has no attribute 'get'
```
```


### Additional information

_No response_

**Comment by Gourieff** [comment]
https://github.com/Gourieff/sd-webui-reactor#v-invalid_protobuf--load-model-from-modelsinsightfaceinswapper_128onnx-failedprotobuf-parsing-failed-or-attributeerror-nonetype-object-has-no-attribute-get-or-attributeerror-faceswapscript-object-has-no-attribute-save_original

**Comment by andysingal** [comment]
> https://github.com/Gourieff/sd-webui-reactor#v-invalid_protobuf--load-model-from-modelsinsightfaceinswapper_128onnx-failedprotobuf-parsing-failed-or-attributeerror-nonetype-object-has-no-attribute-get-or-attributeerror-faceswapscript-object-has-no-attribute-save_original

Thanks for your reply, works to some extent but not  getting same face swap as you got:
<img width="1754" alt="Screenshot 2023-11-27 at 7 46 42 PM" src="https://github.com/Gourieff/sd-webui-reactor/assets/20493493/b16e90c0-1c20-4092-9d5e-32ac65a290d6">

<img width="1337" alt="Screenshot 2023-11-27 at 7 48 33 PM" src="https://github.com/Gourieff/sd-webui-reactor/assets/20493493/cc14d66d-c8de-4b1e-afed-ef7635c271cc">

<img width="1729" alt="Screenshot 2023-11-27 at 7 49 37 PM" src="https://github.com/Gourieff/sd-webui-reactor/assets/20493493/cb74ce57-1019-4685-b8e8-26248b9a6270">

<img width="863" alt="Screenshot 2023-11-27 at 7 51 36 PM" src="https://github.com/Gourieff/sd-webui-reactor/assets/20493493/04fefc6e-1632-4b6e-9b8b-f4bf3d677856">

**Comment by Gourieff** [comment]
On the target image you have only one face, that's why ReActor tells that there's no face with Index=1 for the target face
So, it swaps Source(1) to Target(0) according to the indexes you set (source 0,1; target 1,0)
