### ISSUE TITLE
*Documentation* bug (and fix!) re: InsightFace install for Windows/A1111 users

### ISSUE THREAD

**Issue by alastaira** [Gourieff/sd-webui-reactor#223]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Hi,

I believe that some of the problems encountered by people not being to install insightface (e.g. [here](https://github.com/Gourieff/sd-webui-reactor/issues?q=is%3Aissue+is%3Aclosed+ModuleNotFoundError%3A+No+module+named+%27insightface%27
) and [here](https://github.com/Gourieff/sd-webui-reactor/discussions/216)) can be explained by a slight mismatch in the Reactor installation instructions and the current A1111 installation instructions. (This only affects Windows users).

There are two ways to install A1111. The first listed is the "Installation on Windows 10/11 with NVidia-GPUs using release package", and the second is "Automatic Installation on Windows". I assume many people will initially use the first option, but that does not install a Python venv in the /webui directory. Instead, it creates a /system folder alongside the webui folder, and places a complete install of Python there.

So, while the instructions listed on the Reactor page work if you used Git to pull the A1111 repo., if you followed the instructions and downloaded the sd.webui.zip package instead, reactor installation will fail.
The solution is instead, to follow the instructions in VIII. but, from the `sd.webui\system\python\Scripts` directory, run
`pip install c:\sd.webui\webui\insightface-0.7.3-cp310-cp310-win_amd64.whl --user`

Just thought mentioning that in the documentation might solve some newbies a bit of time.

### Steps to reproduce the problem

1.) Follow A1111 "Installation on Windows 10/11 with NVidia-GPUs using release package" instructions https://github.com/AUTOMATIC1111/stable-diffusion-webui
2.) Follow Reactor "Installation for windows users" instructions. Results in insightface not being built
3.) Follow alternative "VIII. (For Windows users) If you still cannot build Insightface for some reasons or just don't want to install Visual Studio or VS C++ Build Tools" instructions. Results in 'pip' is not recognized as an internal or external command,
operable program or batch file.

### Sysinfo

Windows 11, A1111 webui version: [v1.6.0-2-g4afaaf8a]  •  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.41.2

### Relevant console log

```Shell
pip install insightface-0.7.3-cp310-cp310-win_amd64.whl
'pip' is not recognized as an internal or external command,
operable program or batch file.
```

### Additional information

Thankyou for your effort in developing and maintaining this wonderful extension!

**Comment by Gourieff** [comment]
Hi there
Yes, thanks you mentioned this, documentation is going to be reworked soon
Also I want to say that it's not right to `pip install` smth inside venv or an embedded python's folder using the flag ` --user` - with this flag installation will be executed into the users python folder (installed in your OS) but not into venv/embedded

**Comment by GsonJeong** [comment]
I was stuck for on week to fix this out because I really need this one for my new plan.
this saved my life...I'm so happy now

The solution is instead, to follow the instructions in VIII. but, from the sd.webui\system\python\Scripts directory, run
pip install c:\sd.webui\webui\insightface-0.7.3-cp310-cp310-win_amd64.whl --user

**Comment by alastaira** [comment]
> Also I want to say that it's not right to `pip install` smth inside venv or an embedded python's folder using the flag ` --user` - with this flag installation will be executed into the users python folder (installed in your OS) but not into venv/embedded

And that's exactly the sort of thing that would be good to have documented rather than follow advice I found on various YouTube tutorials ;)
