### ISSUE TITLE
Error running postprocess_image /// Protobuf parsing failed.

### ISSUE THREAD

**Issue by nftcharm** [Gourieff/sd-webui-reactor#248]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Hello, I was following instructions on the docs and tried to use the face-swapping function. However, I always get the following error:

I'm attaching the error as a screenshot for easier readability formatting:

![image](https://github.com/Gourieff/sd-webui-reactor/assets/105672339/ebab3657-d7ea-4014-bfef-aadf23a6b81c)

### May important note:
While I did my research, I came across this answer here:
https://github.com/s0md3v/sd-webui-roop/issues/29#issuecomment-1605589974

This comment is referring to the C/MyUser hard drive and **I don't have** the folders this person mentioned. 
MyUser\ .ifnude
MyUser\ .insightface\ models\ buffalo_l

**But I do have:** inswapper_128.onnx in my webui/models/roop folder
But I am also not sure if that's important for this case:

### Steps to reproduce the problem

I have a guess what the problem might be the location of my Visual Studio 2022 installement:

(Got stable diffusion ui for a few days already, working fine without problems - Saved at harddrive F, not C where windows is. Then:)

1. I downloaded Visual Studio 2022 from the link. I selected only "desktop applications with c++" and installed it it on my hard-drive F (That's not the hard drive where windows is or my "User")
2. Started the WebUI and installed this extention by loading it via URL
3. Restarted the server according to the console
4. Generated a simple portrait image via a text prompt
5. After the image was generated, I enabled reactor
6. Loaded my image to reactor
7. Clicked generate again
8. The error appeared on my console

### Sysinfo

Windows 10
main version of stable-diffusion-webui
main version of sd-webui-reactor

### Relevant console log

```Shell
*** Error running postprocess_image: F:\Projekte\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py
    Traceback (most recent call last):
      File "F:\Projekte\AI\stable-diffusion-webui\modules\scripts.py", line 675, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "F:\Projekte\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 370, in postprocess_image
        result, output, swapped = swap_face(
      File "F:\Projekte\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 578, in swap_face
        result_image, output, swapped = operate(source_img,target_img,target_img_orig,model,source_faces_index,faces_index,source_faces,target_faces,gender_source,gender_target,source_face,wrong_gender,source_age,source_gender,output,swapped,mask_face,entire_mask_image,enhancement_options)
      File "F:\Projekte\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 640, in operate
        face_swapper = getFaceSwapModel(model)
      File "F:\Projekte\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 126, in getFaceSwapModel
        FS_MODEL = insightface.model_zoo.get_model(model_path, providers=PROVIDERS)
      File "F:\Projekte\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
        model = router.get_model(providers=providers, provider_options=provider_options)
      File "F:\Projekte\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 21, in patched_get_model
        session = PickableInferenceSession(self.onnx_file, **kwargs)
      File "F:\Projekte\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
        super().__init__(model_path, **kwargs)
      File "F:\Projekte\AI\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
        self._create_inference_session(providers, provider_options, disabled_optimizers)
      File "F:\Projekte\AI\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 452, in _create_inference_session
        sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
    onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from F:\Projekte\AI\stable-diffusion-webui\models\insightface\inswapper_128.onnx failed:Protobuf parsing failed.
```

**Comment by nftcharm** [comment]
Edit: I fixed the issue by following this guide by checking older github issues:

https://github.com/Gourieff/sd-webui-reactor#v-invalid_protobuf--load-model-from-modelsinsightfaceinswapper_128onnx-failedprotobuf-parsing-failed-or-attributeerror-nonetype-object-has-no-attribute-get-or-attributeerror-faceswapscript-object-has-no-attribute-save_original

Works now by simply replacing the file!

**Comment by korbinliu** [comment]
> Edit: I fixed the issue by following this guide by checking older github issues:
> 
> https://github.com/Gourieff/sd-webui-reactor#v-invalid_protobuf--load-model-from-modelsinsightfaceinswapper_128onnx-failedprotobuf-parsing-failed-or-attributeerror-nonetype-object-has-no-attribute-get-or-attributeerror-faceswapscript-object-has-no-attribute-save_original
> 
> Works now by simply replacing the file!

What is the specific step?
