### ISSUE TITLE
[Feature]: Save Original checkbox in Folder mode

### ISSUE THREAD

**Issue by drnod** [Gourieff/sd-webui-reactor#250]
### Feature description

It would be great to add the function to save orginal image or not in Folder mode.

Currently it is always saving oringinal image in addition.

A Checkbox like in image mode would help.

**Comment by Gourieff** [comment]
Yeah, I will add it with the next commit

**Comment by Gourieff** [comment]
Done!

**Comment by drnod** [comment]
Checkbox is in newest version visible for me. But it always still saves the original image, too.

If the checkbox is selected or not. Not sure if it is a bug, or not working at all.

**Comment by Gourieff** [comment]
This will be reworked later

**Comment by Gourieff** [comment]
Reworked!
