### ISSUE TITLE
[Feature]: Random file checkbox in "Folder" mode

### ISSUE THREAD

**Issue by drnod** [Gourieff/sd-webui-reactor#252]
### Feature description

It would be great to add a checkbox to select one random image from the source folder in Folder mode.

Currently i made a workaround to get this done. (Windows .bat file)

@echo off
setlocal enabledelayedexpansion

REM Path setting for folders **** please change for your path ****
set "FacesFolder=D:\outputs\Faces"
set "RandomFacesFolder=D:\outputs\RandomFaces"

REM delete content of folder "RandomFaces"
del /q "%RandomFacesFolder%\*.*"

REM count files in folder "Faces"
set "Count=0"
for %%F in ("%FacesFolder%\*.*") do (
    set /a "Count+=1"
)

REM get random number
set /a "RandomNumber=!random! %% Count + 1"

REM copy random file to folder "RandomFaces"
set "Index=0"
for %%F in ("%FacesFolder%\*.*") do (
    set /a "Index+=1"
    if !Index! equ %RandomNumber% (
        copy "%%F" "%RandomFacesFolder%"
    )
)

echo random photo was copied.

endlocal

**Comment by nolageek** [comment]
Love the new functionality as well, but yeah - would be nice if when we generate an image with multiple people if it would pick a random face instead of using the same face for all of them.

**Comment by Gourieff** [comment]
Done!
