### ISSUE TITLE
img2img - paste Image overwrites ReActor

### ISSUE THREAD

**Issue by Webtransformer** [Gourieff/sd-webui-reactor#256]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

I am not sure if this is a ReActor problem.
When I for example use img2img and paste an image directly into the img2img zone then Reactor is also overwritten with a copy.
The paste seems to also  affect Reactor.

### Steps to reproduce the problem

1. Copy an image which you want to use for img2img (Windows)
2. On the img2img area Paste the image
3. Go to reactor, its also overwritten

### Sysinfo

Windows 10, Firefox

### Relevant console log

```Shell
none
```

**Comment by Gourieff** [comment]
UI's "features"
ReActor has nothing to do with this

**Comment by Webtransformer** [comment]
Thank you, can be closed then. Didnt knew...
