### ISSUE TITLE
Unable to inherit the original sad expression

### ISSUE THREAD

**Issue by SiuLeeBoss** [Gourieff/sd-webui-reactor#258]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Unable to inherit the original sad expression，I don't know if this is a bug or a functional flaw, but I have tried a variety of expressions so far. Only expressionless or smiling faces can be inherited, while expressions such as crying, angry, sad, and painful cannot be inherited from the original image. I don't know. Any idea if I'm the only one having this problem?

### Steps to reproduce the problem

1. Go to img2img
2. Denoising strength set to 0
3. Press enable reactor

### Sysinfo

win 10
chrome
GTX 1070
version: [v1.6.0]

### Relevant console log

```Shell
normal
```

**Comment by Gourieff** [comment]
But it really tries hard! (Just set "CodeFormer Weight" to 1)
![изображение](https://github.com/Gourieff/sd-webui-reactor/assets/85128026/335ee257-c965-4943-aa29-49fe5eaf3cff)
![изображение](https://github.com/Gourieff/sd-webui-reactor/assets/85128026/e737298d-dec9-426f-8388-846630af7190)
![изображение](https://github.com/Gourieff/sd-webui-reactor/assets/85128026/34ff8379-f1ee-4f1f-bb65-3da4421fa94f)
![изображение](https://github.com/Gourieff/sd-webui-reactor/assets/85128026/0ce68e3b-ea9d-4964-8b15-b04c329a57ec)
![изображение](https://github.com/Gourieff/sd-webui-reactor/assets/85128026/93bf7742-0359-45a0-8202-afcf5eaf196f)
![изображение](https://github.com/Gourieff/sd-webui-reactor/assets/85128026/9f9e59dc-bd0b-4edb-8c04-8c8e0291fa03)
![изображение](https://github.com/Gourieff/sd-webui-reactor/assets/85128026/2e4e2532-f835-48ae-be98-b45c56f90f9b)
![изображение](https://github.com/Gourieff/sd-webui-reactor/assets/85128026/ff39552d-077c-48cb-bb76-c95037416aba)
