### ISSUE TITLE
"Invalid encoded image" error when using face model via API 

### ISSUE THREAD

**Issue by Trojaner** [Gourieff/sd-webui-reactor#266]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

I get the follwoing error when calling the image API with `face_model` instead of `source_image`:
```
(500, '{"error":"HTTPException","detail":"Invalid encoded image","body":"","errors":""}')
```

### Steps to reproduce the problem

Call the `/reactor/image` endpoint with `face_model` set to a valid model, `source_image` unset or set to empty string and `select_source` set to 1. Obviously set the other parameters to valid values as well.

### Sysinfo

Irrelevant to issue

### Relevant console log

```Shell
API cannot decode image: cannot identify image file <_io.BytesIO object at 0x000002412EFF21B0>
```  
[raised [here](https://github.com/vladmandic/automatic/blob/2336ffc0eef3265b49688e73ef70f8cbafee1202/modules/api/api.py#L62)]

### Additional information

Issue is caused by the reactor_image API not checking `select_source` before attempting to decode source image from base64 [here](https://github.com/Gourieff/sd-webui-reactor/blob/main/scripts/reactor_api.py#L80) . As the [decode_base64_to_image API](https://github.com/vladmandic/automatic/blob/2336ffc0eef3265b49688e73ef70f8cbafee1202/modules/api/api.py#L54-L62) does not tolerate None or empty string values the related error is raised. 

### Proposed fix 
The `source_image` parameter should not be used or decoded when `select_source` is set to 1. May apply for folder (select_source = 2) as well.

**Comment by Gourieff** [comment]
I will test it later

**Comment by Trojaner** [comment]
Any updates?

**Comment by Gourieff** [comment]
Confirmed! Will be fixed with the next commit
If you need this fix now - you can manually change [L80](https://github.com/Gourieff/sd-webui-reactor/blob/main/scripts/reactor_api.py#L80) to:
```python
s_image = api.decode_base64_to_image(source_image) if select_source == 0 else None
```
