### ISSUE TITLE
This extension quality outpiut is crap compared to roop uncensored, please analyze the code to figure it out

### ISSUE THREAD

**Issue by 2blackbar** [Gourieff/sd-webui-reactor#270]
### What happened?

ITs pretty blocky and compared to roop repo quality is much worse despite using the same model, clearly pipeline is borked in this one , can you guys rework it so it wont lose quality, you can test on the same pic and compare side by side.

IMO you borked codeformer upscaler function, cause its still blocky AF despite codeformer being 512 res!

If you want to shit on me for being straight to the point thats fine i just wanted your attention.
But i still switched to roop  cause this is just unacceptable when i know that quality can be better using same models.
Id post a pics but im kinda busy now.

### Steps to reproduce the problem

....

### Sysinfo

....

### Relevant console log

```Shell
....
```

**Comment by Gourieff** [comment]
Была такая фраза из старой рекламы: "Ты просто не умеешь их готовить..."
Ламер :)
https://github.com/Gourieff/sd-webui-reactor/discussions/124#discussioncomment-7342328

**Comment by Gourieff** [comment]
Была такая фраза из старой рекламы: "Ты просто не умеешь их готовить..."

https://github.com/Gourieff/sd-webui-reactor/discussions/124#discussioncomment-7342328
