### ISSUE TITLE
The plugin's Enable Checkbox got commented out

### ISSUE THREAD

**Issue by Keshav-Pandey** [Gourieff/sd-webui-reactor#271]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

The enable checkbox got accidently commented out in `0.6.0-aplha3`

https://github.com/Gourieff/sd-webui-reactor/commit/d8e300b202e54199d3dc63468a89f16a048fcfba#diff-4992463104f35ec5fb83e291dc88c603cba18cc22d36cc7eacfbda18dbc3b662R54

### Steps to reproduce the problem

1. Load the reactor plugin on SD.Next
2. Add your source image
3. There is no enable button

### Sysinfo

```
arch: AMD64
cpu: AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD
system: Windows
release: Windows-10-10.0.22631-SP0
python: 3.10.13
```

```
app: SD.next
updated: 2023-12-17
hash: 83785628
url: https://github.com/vladmandic/automatic/tree/master
```

### Relevant console log

```Shell
N/A
```

### Additional information

Looks like the enable button got commented out during the UI makeover

**Comment by johnandreopoulos** [comment]
I encountered a similar issue with the latest refactor version and managed to resolve it successfully. Here's the solution I applied:

1. Navigate to the source code folders.
2. Access the 'extensions' directory and locate the 'sd-webui-reactor' folder.
3. Delete the entire contents of the 'sd-webui-reactor' folder.
4. Next, download an older version, specifically "0.5.0" from [this link](https://github.com/Gourieff/sd-webui-reactor/archive/refs/tags/v0.5.1.zip).
5. Unzip the downloaded folder and copy all its contents.
6. Paste the copied content into the source folder, replacing the previously deleted 'sd-webui-reactor' contents.

This method effectively reverted to the older version, resolving the issue I encountered. If you face any further difficulties or need additional assistance, feel free to ask!

https://github.com/Gourieff/sd-webui-reactor/assets/39243722/deb1ca1a-a8bf-472d-9d2b-4f165b99ef22
