### ISSUE TITLE
[SOLVED] AttributeError: module 'modules.ui_components' has no attribute 'InputAccordion'

### ISSUE THREAD

**Issue by yeh111w** [Gourieff/sd-webui-reactor#282]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

i got a error info when i open  webui-user.bat

### Steps to reproduce the problem

I dont know how to fix

### Sysinfo

arch: AMD64
cpu: AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD
system: Windows
release: Windows-10-10.0.19045-SP0
python: 3.10.9
2.0.1+cu118 autocast  half
device: NVIDIA GeForce RTX 4070 (1) (compute_37) (8, 9)
cuda: 11.8
cudnn: 8700
driver: 537.13

### Relevant console log

```Shell
*** Error calling: F:\stable-diffusion-webui-master\extensions\sd-webui-reactor\scripts\reactor_faceswap.py/ui
    Traceback (most recent call last):
      File "F:\stable-diffusion-webui-master\modules\scripts.py", line 339, in wrap_call
        return func(*args, **kwargs)
      File "F:\stable-diffusion-webui-master\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 44, in ui
        with ui_components.InputAccordion(False, label=f"{app_title}") as enable:
    AttributeError: module 'modules.ui_components' has no attribute 'InputAccordion'

---
*** Error calling: F:\stable-diffusion-webui-master\extensions\sd-webui-reactor\scripts\reactor_faceswap.py/ui
    Traceback (most recent call last):
      File "F:\stable-diffusion-webui-master\modules\scripts.py", line 339, in wrap_call
        return func(*args, **kwargs)
      File "F:\stable-diffusion-webui-master\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 44, in ui
        with ui_components.InputAccordion(False, label=f"{app_title}") as enable:
    AttributeError: module 'modules.ui_components' has no attribute 'InputAccordion'

---
calling F:\stable-diffusion-webui-master\extensions\sd-webui-reactor\scripts\reactor_faceswap.py/ui: AttributeError
Traceback (most recent call last):
  File "F:\stable-diffusion-webui-master\modules\scripts_postprocessing.py", line 53, in wrap_call
    res = func(*args, **kwargs)
  File "F:\stable-diffusion-webui-master\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 414, in ui
    with ui_components.InputAccordion(False, label=f"{app_title}") as enable:
AttributeError: module 'modules.ui_components' has no attribute 'InputAccordion'

Traceback (most recent call last):
  File "F:\stable-diffusion-webui-master\launch.py", line 39, in <module>
    main()
  File "F:\stable-diffusion-webui-master\launch.py", line 35, in main
    start()
  File "F:\stable-diffusion-webui-master\modules\launch_utils.py", line 394, in start
    webui.webui()
  File "F:\stable-diffusion-webui-master\webui.py", line 393, in webui
    shared.demo = modules.ui.create_ui()
  File "F:\stable-diffusion-webui-master\modules\ui.py", line 1061, in create_ui
    ui_postprocessing.create_ui()
  File "F:\stable-diffusion-webui-master\modules\ui_postprocessing.py", line 25, in create_ui
    script_inputs = scripts.scripts_postproc.setup_ui()
  File "F:\stable-diffusion-webui-master\modules\scripts_postprocessing.py", line 113, in setup_ui
    self.create_script_ui(script, inputs)
  File "F:\stable-diffusion-webui-master\modules\scripts_postprocessing.py", line 84, in create_script_ui
    for control in script.controls.values():
AttributeError: 'NoneType' object has no attribute 'values'
```

**Comment by Gourieff** [comment]
Please update your A1111, you use rather old version of sd-webui

If you don't want to update, you can use 0.6.0 alpha2, open CMD inside ReActor's folder and run the following:

    git checkout ed66d91

To return version back:

    git checkout main

**Comment by yeh111w** [comment]
OH, THANKS!
but now it suck when it say ReActor preheating... Device: CUDA
It has been more than 20 minutes. Is this correct?
![image](https://github.com/Gourieff/sd-webui-reactor/assets/139565794/54fe453c-ac95-45e9-b172-019974f6aedf)

**Comment by yeh111w** [comment]
ops.. never mind i fix it 
i download a new inswapper_128.onnx file and replace it
![image](https://github.com/Gourieff/sd-webui-reactor/assets/139565794/c73bd112-84e5-4674-9807-23543c8847d8)

**Comment by ENTPRESTIGIOUS** [comment]
I have the same problem, tried downloading the inswapper manually from the README and this is my log
`*** Error calling: D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py/ui
    Traceback (most recent call last):
      File "D:\ai\masterbranch\stable-diffusion-webui\modules\scripts.py", line 339, in wrap_call
        return func(*args, **kwargs)
      File "D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 44, in ui
        with ui_components.InputAccordion(False, label=f"{app_title}") as enable:
    AttributeError: module 'modules.ui_components' has no attribute 'InputAccordion'

---
*** Error calling: D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py/ui
    Traceback (most recent call last):
      File "D:\ai\masterbranch\stable-diffusion-webui\modules\scripts.py", line 339, in wrap_call
        return func(*args, **kwargs)
      File "D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 44, in ui
        with ui_components.InputAccordion(False, label=f"{app_title}") as enable:
    AttributeError: module 'modules.ui_components' has no attribute 'InputAccordion'

---
calling D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py/ui: AttributeError
Traceback (most recent call last):
  File "D:\ai\masterbranch\stable-diffusion-webui\modules\scripts_postprocessing.py", line 53, in wrap_call
    res = func(*args, **kwargs)
  File "D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 414, in ui
    with ui_components.InputAccordion(False, label=f"{app_title}") as enable:
AttributeError: module 'modules.ui_components' has no attribute 'InputAccordion'

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\ai\masterbranch\stable-diffusion-webui\launch.py:39 in <module>                               │
│                                                                                                  │
│   36                                                                                             │
│   37                                                                                             │
│   38 if __name__ == "__main__":                                                                  │
│ ❱ 39 │   main()                                                                                  │
│   40                                                                                             │
│                                                                                                  │
│ D:\ai\masterbranch\stable-diffusion-webui\launch.py:35 in main                                   │
│                                                                                                  │
│   32 │   if args.test_server:                                                                    │
│   33 │   │   configure_for_tests()                                                               │
│   34 │                                                                                           │
│ ❱ 35 │   start()                                                                                 │
│   36                                                                                             │
│   37                                                                                             │
│   38 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ D:\ai\masterbranch\stable-diffusion-webui\modules\launch_utils.py:394 in start                   │
│                                                                                                  │
│   391 │   if '--nowebui' in sys.argv:                                                            │
│   392 │   │   webui.api_only()                                                                   │
│   393 │   else:                                                                                  │
│ ❱ 394 │   │   webui.webui()                                                                      │
│   395                                                                                            │
│                                                                                                  │
│ D:\ai\masterbranch\stable-diffusion-webui\webui.py:393 in webui                                  │
│                                                                                                  │
│   390 │   │   modules.script_callbacks.before_ui_callback()                                      │
│   391 │   │   startup_timer.record("scripts before_ui_callback")                                 │
│   392 │   │                                                                                      │
│ ❱ 393 │   │   shared.demo = modules.ui.create_ui()                                               │
│   394 │   │   startup_timer.record("create ui")                                                  │
│   395 │   │                                                                                      │
│   396 │   │   if not cmd_opts.no_gradio_queue:                                                   │
│                                                                                                  │
│ D:\ai\masterbranch\stable-diffusion-webui\modules\ui.py:1061 in create_ui                        │
│                                                                                                  │
│   1058 │   modules.scripts.scripts_current = None                                                │
│   1059 │                                                                                         │
│   1060 │   with gr.Blocks(analytics_enabled=False) as extras_interface:                          │
│ ❱ 1061 │   │   ui_postprocessing.create_ui()                                                     │
│   1062 │                                                                                         │
│   1063 │   with gr.Blocks(analytics_enabled=False) as pnginfo_interface:                         │
│   1064 │   │   with gr.Row().style(equal_height=False):                                          │
│                                                                                                  │
│ D:\ai\masterbranch\stable-diffusion-webui\modules\ui_postprocessing.py:25 in create_ui           │
│                                                                                                  │
│   22 │   │   │                                                                                   │
│   23 │   │   │   submit = gr.Button('Generate', elem_id="extras_generate", variant='primary')    │
│   24 │   │   │                                                                                   │
│ ❱ 25 │   │   │   script_inputs = scripts.scripts_postproc.setup_ui()                             │
│   26 │   │                                                                                       │
│   27 │   │   with gr.Column():                                                                   │
│   28 │   │   │   result_images, html_info_x, html_info, html_log = ui_common.create_output_pa    │
│                                                                                                  │
│ D:\ai\masterbranch\stable-diffusion-webui\modules\scripts_postprocessing.py:113 in setup_ui      │
│                                                                                                  │
│   110 │   │                                                                                      │
│   111 │   │   for script in self.scripts_in_preferred_order():                                   │
│   112 │   │   │   with gr.Row() as group:                                                        │
│ ❱ 113 │   │   │   │   self.create_script_ui(script, inputs)                                      │
│   114 │   │   │                                                                                  │
│   115 │   │   │   script.group = group                                                           │
│   116                                                                                            │
│                                                                                                  │
│ D:\ai\masterbranch\stable-diffusion-webui\modules\scripts_postprocessing.py:84 in                │
│ create_script_ui                                                                                 │
│                                                                                                  │
│    81 │   │                                                                                      │
│    82 │   │   script.controls = wrap_call(script.ui, script.filename, "ui")                      │
│    83 │   │                                                                                      │
│ ❱  84 │   │   for control in script.controls.values():                                           │
│    85 │   │   │   control.custom_script_source = os.path.basename(script.filename)               │
│    86 │   │                                                                                      │
│    87 │   │   inputs += list(script.controls.values())                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute 'values'
Creating model from config: D:\ai\masterbranch\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying attention optimization: xformers... done.
Model loaded in 2.2s (load weights from disk: 0.5s, create model: 0.4s, apply weights to model: 0.4s, apply half(): 0.4s, move model to device: 0.5s).`

**Comment by yeh111w** [comment]
> Please update your A1111, you use rather old version of sd-webui
> 
> If you don't want to update, you can use 0.6.0 alpha2, open CMD inside ReActor's folder and run the following:
> 
> ```
> git checkout ed66d91
> ```
> 
> To return version back:
> 
> ```
> git checkout main
> ```

did u try update?

**Comment by ENTPRESTIGIOUS** [comment]
> > Please update your A1111, you use rather old version of sd-webui
> > If you don't want to update, you can use 0.6.0 alpha2, open CMD inside ReActor's folder and run the following:
> > ```
> > git checkout ed66d91
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > To return version back:
> > ```
> > git checkout main
> > ```
> 
> did u try update?

thx, using git checkout worked.

**Comment by 70pice** [comment]
how to update A1111?
