### ISSUE TITLE
[Feature]: Toddler girl swaps looking like older men 🤪

### ISSUE THREAD

**Issue by rinogo** [Gourieff/sd-webui-reactor#297]
### Feature description

I'm trying to swap a photo of a 1-year-old baby girl onto a Stable Diffusion-generated baby.

My workflow typically consists of swapping uising the "Folder" Source method. This allows me to quickly trial a bunch of different source photos to see which one works best.

This works great with adults, but somewhat terribly in this "baby swap" instance.

For example, some of my images end up looking like this - which is nothing like the source baby - and actually looks like an adult man:
<img width="217" alt="Pasted Graphic 8" src="https://github.com/Gourieff/sd-webui-reactor/assets/3732514/81bd1016-1bc5-4141-932e-2b6c89b6ffd1">

In the logs, I saw how the age on these source images was often guessed completely inaccurately. I thought that might be the source of the weirdness.

However, after inspecting [the code](https://github.com/Gourieff/sd-webui-reactor/blob/cec1d41dc75ea576b91905a7e50e6ab09b530602/scripts/reactor_swapper.py#L388), **it looks like `source_age` isn't used as input into any models - it's basically just written to the log. Does that sound correct?**

If that's the case, my theory about incorrectly detected ages being problematic isn't accurate. **Do you have any idea why some of my baby swaps are ending up looking like this?**

Thank you!

(P.S. Happy to send a PR if there's something that you'd suggest!)

**Comment by Gourieff** [comment]
Yes, there's the issue with age detection, it works not very correct or even totally incorrect with children
The point is about Buffalo models we use, the age detection model is not very accurate
