### ISSUE TITLE
AttributeError: module 'modules.ui_components' has no attribute 'InputAccordion'

### ISSUE THREAD

**Issue by unalman** [Gourieff/sd-webui-reactor#300]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

When I download reactor, Stable Diffusion doesn't open.

### Steps to reproduce the problem

I tried to install with link from extensions then restart ui, i got this error. I read other issues but it didn't help me.  I have VS Professional but i also install community version. Also i installed visual cpp build tools

### Sysinfo

{
    "Platform": "Windows-10-10.0.22621-SP0",
    "Python": "3.10.6",
    "Version": "v1.5.1",
    "Commit": "68f336bd994bed5442ad95bad6b6ad5564a5409a",
    "Script path": "C:\\Users\\pc\\Documents\\stable-diffusion-webui",
    "Data path": "C:\\Users\\pc\\Documents\\stable-diffusion-webui",
    "Extensions dir": "C:\\Users\\pc\\Documents\\stable-diffusion-webui\\extensions",
    "Checksum": "38527f5bf8672e5daf3ada54bed2285f2c3432a333bb8a09720c105fb401eb4b",
    "Commandline": [
        "launch.py"
    ],
    "Torch env info": {
        "torch_version": "2.0.1+cu118",
        "is_debug_build": "False",
        "cuda_compiled_version": "11.8",
        "gcc_version": null,
        "clang_version": null,
        "cmake_version": null,
        "os": "Microsoft Windows 11 Pro",
        "libc_version": "N/A",
        "python_version": "3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] (64-bit runtime)",
        "python_platform": "Windows-10-10.0.22621-SP0",
        "is_cuda_available": "True",
        "cuda_runtime_version": null,
        "cuda_module_loading": "LAZY",
        "nvidia_driver_version": "546.33",
        "nvidia_gpu_models": "GPU 0: NVIDIA GeForce RTX 3060",
        "cudnn_version": null,
        "pip_version": "pip3",
        "pip_packages": [
            "numpy==1.23.5",
            "open-clip-torch==2.20.0",
            "pytorch-lightning==1.9.4",
            "torch==2.0.1+cu118",
            "torchdiffeq==0.2.3",
            "torchmetrics==1.2.1",
            "torchsde==0.2.5",
            "torchvision==0.15.2+cu118"
        ],
        "conda_packages": null,
        "hip_compiled_version": "N/A",
        "hip_runtime_version": "N/A",
        "miopen_runtime_version": "N/A",
        "caching_allocator_config": "",
        "is_xnnpack_available": "True",
        "cpu_info": [
            "Architecture=9",
            "CurrentClockSpeed=3600",
            "DeviceID=CPU0",
            "Family=107",
            "L2CacheSize=3072",
            "L2CacheSpeed=",
            "Manufacturer=AuthenticAMD",
            "MaxClockSpeed=3600",
            "Name=AMD Ryzen 5 5500                               ",
            "ProcessorType=3",
            "Revision=20480"
        ]
    },
    "Exceptions": [],
    "CPU": {
        "model": "AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD",
        "count logical": 12,
        "count physical": 6
    },
    "RAM": {
        "total": "16GB",
        "used": "8GB",
        "free": "8GB"
    },
    "Extensions": [
        {
            "name": "a1111-sd-webui-lycoris",
            "path": "C:\\Users\\pc\\Documents\\stable-diffusion-webui\\extensions\\a1111-sd-webui-lycoris",
            "version": "df9c0093",
            "branch": "main",
            "remote": "https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris"
        },
        {
            "name": "openpose-editor",
            "path": "C:\\Users\\pc\\Documents\\stable-diffusion-webui\\extensions\\openpose-editor",
            "version": "db07b9c6",
            "branch": "master",
            "remote": "https://github.com/fkunn1326/openpose-editor"
        },
        {
            "name": "sd-webui-additional-networks",
            "path": "C:\\Users\\pc\\Documents\\stable-diffusion-webui\\extensions\\sd-webui-additional-networks",
            "version": "e9f3d622",
            "branch": "main",
            "remote": "https://github.com/kohya-ss/sd-webui-additional-networks.git"
        },
        {
            "name": "sd-webui-controlnet",
            "path": "C:\\Users\\pc\\Documents\\stable-diffusion-webui\\extensions\\sd-webui-controlnet",
            "version": "7a4805c8",
            "branch": "main",
            "remote": "https://github.com/Mikubill/sd-webui-controlnet.git"
        },
        {
            "name": "sd-webui-segment-anything",
            "path": "C:\\Users\\pc\\Documents\\stable-diffusion-webui\\extensions\\sd-webui-segment-anything",
            "version": "c555c6d9",
            "branch": "master",
            "remote": "https://github.com/continue-revolution/sd-webui-segment-anything.git"
        },
        {
            "name": "ultimate-upscale-for-automatic1111",
            "path": "C:\\Users\\pc\\Documents\\stable-diffusion-webui\\extensions\\ultimate-upscale-for-automatic1111",
            "version": "728ffcec",
            "branch": "master",
            "remote": "https://github.com/Coyote-A/ultimate-upscale-for-automatic1111"
        }
    ],
    "Inactive extensions": [],
    "Environment": {
        "GRADIO_ANALYTICS_ENABLED": "False"
    },
    "Config": {
        "samples_save": true,
        "samples_format": "png",
        "samples_filename_pattern": "",
        "save_images_add_number": true,
        "grid_save": true,
        "grid_format": "png",
        "grid_extended_filename": false,
        "grid_only_if_multiple": true,
        "grid_prevent_empty_spots": false,
        "grid_zip_filename_pattern": "",
        "n_rows": -1,
        "font": "",
        "grid_text_active_color": "#000000",
        "grid_text_inactive_color": "#999999",
        "grid_background_color": "#ffffff",
        "enable_pnginfo": true,
        "save_txt": false,
        "save_images_before_face_restoration": false,
        "save_images_before_highres_fix": false,
        "save_images_before_color_correction": false,
        "save_mask": false,
        "save_mask_composite": false,
        "jpeg_quality": 80,
        "webp_lossless": false,
        "export_for_4chan": true,
        "img_downscale_threshold": 4.0,
        "target_side_length": 4000,
        "img_max_size_mp": 200,
        "use_original_name_batch": true,
        "use_upscaler_name_as_suffix": false,
        "save_selected_only": true,
        "save_init_img": false,
        "temp_dir": "",
        "clean_temp_dir_at_start": false,
        "outdir_samples": "",
        "outdir_txt2img_samples": "outputs/txt2img-images",
        "outdir_img2img_samples": "outputs/img2img-images",
        "outdir_extras_samples": "outputs/extras-images",
        "outdir_grids": "",
        "outdir_txt2img_grids": "outputs/txt2img-grids",
        "outdir_img2img_grids": "outputs/img2img-grids",
        "outdir_save": "log/images",
        "outdir_init_images": "outputs/init-images",
        "save_to_dirs": true,
        "grid_save_to_dirs": true,
        "use_save_to_dirs_for_ui": false,
        "directories_filename_pattern": "[date]",
        "directories_max_prompt_words": 8,
        "ESRGAN_tile": 192,
        "ESRGAN_tile_overlap": 8,
        "realesrgan_enabled_models": [
            "R-ESRGAN 4x+",
            "R-ESRGAN 4x+ Anime6B"
        ],
        "upscaler_for_img2img": "R-ESRGAN 4x+",
        "face_restoration_model": "CodeFormer",
        "code_former_weight": 0.5,
        "face_restoration_unload": false,
        "show_warnings": false,
        "memmon_poll_rate": 8,
        "samples_log_stdout": false,
        "multiple_tqdm": true,
        "print_hypernet_extra": false,
        "list_hidden_files": true,
        "disable_mmap_load_safetensors": false,
        "unload_models_when_training": false,
        "pin_memory": false,
        "save_optimizer_state": false,
        "save_training_settings_to_txt": true,
        "dataset_filename_word_regex": "",
        "dataset_filename_join_string": " ",
        "training_image_repeats_per_epoch": 1,
        "training_write_csv_every": 500,
        "training_xattention_optimizations": false,
        "training_enable_tensorboard": false,
        "training_tensorboard_save_images": false,
        "training_tensorboard_flush_every": 120,
        "sd_model_checkpoint": "chilloutmix_NiPrunedFp32Fix.safetensors [fc2511737a]",
        "sd_checkpoint_cache": 0,
        "sd_vae_checkpoint_cache": 0,
        "sd_vae": "None",
        "sd_vae_as_default": true,
        "sd_unet": "Automatic",
        "inpainting_mask_weight": 1.0,
        "initial_noise_multiplier": 1.0,
        "img2img_color_correction": false,
        "img2img_fix_steps": false,
        "img2img_background_color": "#ffffff",
        "enable_quantization": false,
        "enable_emphasis": true,
        "enable_batch_seeds": true,
        "comma_padding_backtrack": 20,
        "CLIP_stop_at_last_layers": 2,
        "upcast_attn": false,
        "auto_vae_precision": true,
        "randn_source": "GPU",
        "sdxl_crop_top": 0,
        "sdxl_crop_left": 0,
        "sdxl_refiner_low_aesthetic_score": 2.5,
        "sdxl_refiner_high_aesthetic_score": 6.0,
        "cross_attention_optimization": "Automatic",
        "s_min_uncond": 0.0,
        "token_merging_ratio": 0.0,
        "token_merging_ratio_img2img": 0.0,
        "token_merging_ratio_hr": 0.0,
        "pad_cond_uncond": false,
        "experimental_persistent_cond_cache": false,
        "use_old_emphasis_implementation": false,
        "use_old_karras_scheduler_sigmas": false,
        "no_dpmpp_sde_batch_determinism": false,
        "use_old_hires_fix_width_height": false,
        "dont_fix_second_order_samplers_schedule": false,
        "hires_fix_use_firstpass_conds": false,
        "interrogate_keep_models_in_memory": false,
        "interrogate_return_ranks": false,
        "interrogate_clip_num_beams": 1,
        "interrogate_clip_min_length": 24,
        "interrogate_clip_max_length": 48,
        "interrogate_clip_dict_limit": 1500,
        "interrogate_clip_skip_categories": [],
        "interrogate_deepbooru_score_threshold": 0.5,
        "deepbooru_sort_alpha": true,
        "deepbooru_use_spaces": true,
        "deepbooru_escape": true,
        "deepbooru_filter_tags": "",
        "extra_networks_show_hidden_directories": true,
        "extra_networks_hidden_models": "When searched",
        "extra_networks_default_multiplier": 1.0,
        "extra_networks_card_width": 0,
        "extra_networks_card_height": 0,
        "extra_networks_card_text_scale": 1.0,
        "extra_networks_card_show_desc": true,
        "extra_networks_add_text_separator": " ",
        "ui_extra_networks_tab_reorder": "",
        "textual_inversion_print_at_load": false,
        "textual_inversion_add_hashes_to_infotext": true,
        "sd_hypernetwork": "None",
        "localization": "None",
        "gradio_theme": "Default",
        "img2img_editor_height": 720,
        "return_grid": true,
        "return_mask": false,
        "return_mask_composite": false,
        "do_not_show_images": false,
        "send_seed": true,
        "send_size": true,
        "js_modal_lightbox": true,
        "js_modal_lightbox_initially_zoomed": true,
        "js_modal_lightbox_gamepad": false,
        "js_modal_lightbox_gamepad_repeat": 250,
        "show_progress_in_title": true,
        "samplers_in_dropdown": true,
        "dimensions_and_batch_together": true,
        "keyedit_precision_attention": 0.1,
        "keyedit_precision_extra": 0.05,
        "keyedit_delimiters": ".,\\/!?%^*;:{}=`~()",
        "keyedit_move": true,
        "quicksettings_list": [
            "sd_model_checkpoint",
            "CLIP_stop_at_last_layers",
            "sd_vae"
        ],
        "ui_tab_order": [],
        "hidden_tabs": [],
        "ui_reorder_list": [],
        "hires_fix_show_sampler": false,
        "hires_fix_show_prompts": false,
        "disable_token_counters": false,
        "add_model_hash_to_info": true,
        "add_model_name_to_info": true,
        "add_user_name_to_info": false,
        "add_version_to_infotext": true,
        "disable_weights_auto_swap": true,
        "infotext_styles": "Apply if any",
        "show_progressbar": true,
        "live_previews_enable": true,
        "live_previews_image_format": "png",
        "show_progress_grid": true,
        "show_progress_every_n_steps": 10,
        "show_progress_type": "Approx NN",
        "live_preview_content": "Prompt",
        "live_preview_refresh_period": 1000,
        "hide_samplers": [],
        "eta_ddim": 0.0,
        "eta_ancestral": 1.0,
        "ddim_discretize": "uniform",
        "s_churn": 0.0,
        "s_tmin": 0.0,
        "s_noise": 1.0,
        "k_sched_type": "Automatic",
        "sigma_min": 0.0,
        "sigma_max": 0.0,
        "rho": 0.0,
        "eta_noise_seed_delta": 0,
        "always_discard_next_to_last_sigma": false,
        "uni_pc_variant": "bh1",
        "uni_pc_skip_type": "time_uniform",
        "uni_pc_order": 3,
        "uni_pc_lower_order_final": true,
        "postprocessing_enable_in_main_ui": [],
        "postprocessing_operation_order": [],
        "upscaling_max_images_in_cache": 5,
        "disabled_extensions": [],
        "disable_all_extensions": "none",
        "restore_config_state_file": "",
        "sd_checkpoint_hash": "fc2511737a54c5e80b89ab03e0ab4b98d051ab187f92860f3cd664dc9d08b271",
        "ldsr_steps": 100,
        "ldsr_cached": false,
        "SCUNET_tile": 256,
        "SCUNET_tile_overlap": 8,
        "SWIN_tile": 192,
        "SWIN_tile_overlap": 8,
        "lora_functional": false,
        "sd_lora": "None",
        "lora_preferred_name": "Alias from file",
        "lora_add_hashes_to_infotext": true,
        "lora_show_all": false,
        "lora_hide_unknown_for_versions": [],
        "extra_options": [],
        "extra_options_accordion": false,
        "canvas_hotkey_zoom": "Alt",
        "canvas_hotkey_adjust": "Ctrl",
        "canvas_hotkey_move": "F",
        "canvas_hotkey_fullscreen": "S",
        "canvas_hotkey_reset": "R",
        "canvas_hotkey_overlap": "O",
        "canvas_show_tooltip": true,
        "canvas_blur_prompt": false,
        "canvas_disabled_functions": [
            "Overlap"
        ],
        "additional_networks_extra_lora_path": "\"stable-diffusion-webui/models/Lora\"",
        "additional_networks_sort_models_by": "name",
        "additional_networks_reverse_sort_order": false,
        "additional_networks_model_name_filter": "",
        "additional_networks_xy_grid_model_metadata": "",
        "additional_networks_hash_thread_count": 1.0,
        "additional_networks_back_up_model_when_saving": true,
        "additional_networks_show_only_safetensors": false,
        "additional_networks_show_only_models_with_metadata": "disabled",
        "additional_networks_max_top_tags": 20.0,
        "additional_networks_max_dataset_folders": 20.0,
        "control_net_model_config": "models\\cldm_v15.yaml",
        "control_net_model_adapter_config": "models\\t2iadapter_sketch_sd14v1.yaml",
        "control_net_detectedmap_dir": "detected_maps",
        "control_net_models_path": "",
        "control_net_modules_path": "",
        "control_net_max_models_num": 3,
        "control_net_model_cache_size": 1,
        "control_net_inpaint_blur_sigma": 7,
        "control_net_no_high_res_fix": false,
        "control_net_no_detectmap": false,
        "control_net_detectmap_autosaving": false,
        "control_net_allow_script_control": false,
        "control_net_sync_field_args": false,
        "controlnet_show_batch_images_in_ui": false,
        "controlnet_increment_seed_during_batch": false,
        "controlnet_disable_control_type": false,
        "controlnet_disable_openpose_edit": false,
        "controlnet_ignore_noninpaint_mask": false,
        "sam_use_local_groundingdino": false
    },
    "Startup": {
        "total": 11.483854532241821,
        "records": {
            "start": 0.0,
            "launcher": 2.703721284866333,
            "import torch": 3.1943657398223877,
            "import gradio": 0.986987829208374,
            "setup paths": 0.9000487327575684,
            "import ldm": 0.006011486053466797,
            "other imports": 0.7860100269317627,
            "opts onchange": 0.0030007362365722656,
            "setup SD model": 0.0,
            "setup codeformer": 0.07272052764892578,
            "setup gfpgan": 0.0010001659393310547,
            "list extensions": 0.0,
            "list SD models": 0.1593916416168213,
            "load scripts/custom_code.py": 0.007062435150146484,
            "load scripts/img2imgalt.py": 0.0,
            "load scripts/loopback.py": 0.001039266586303711,
            "load scripts/outpainting_mk_2.py": 0.0,
            "load scripts/poor_mans_outpainting.py": 0.0010046958923339844,
            "load scripts/postprocessing_codeformer.py": 0.0,
            "load scripts/postprocessing_gfpgan.py": 0.0,
            "load scripts/postprocessing_upscale.py": 0.001003265380859375,
            "load scripts/prompt_matrix.py": 0.0,
            "load scripts/prompts_from_file.py": 0.0,
            "load scripts/sd_upscale.py": 0.0010042190551757812,
            "load scripts/xyz_grid.py": 0.00150299072265625,
            "load scripts/lycoris_script.py": 0.0,
            "load scripts/main.py": 0.9400143623352051,
            "load scripts/additional_networks.py": 0.08392882347106934,
            "load scripts/addnet_xyz_grid_support.py": 0.0009999275207519531,
            "load scripts/lora_compvis.py": 0.0010001659393310547,
            "load scripts/metadata_editor.py": 0.0,
            "load scripts/model_util.py": 0.005020856857299805,
            "load scripts/safetensors_hack.py": 0.0010001659393310547,
            "load scripts/util.py": 0.0,
            "load scripts/adapter.py": 0.0009999275207519531,
            "load scripts/api.py": 0.3528614044189453,
            "load scripts/batch_hijack.py": 0.0010001659393310547,
            "load scripts/cldm.py": 0.0,
            "load scripts/controlmodel_ipadapter.py": 0.001003265380859375,
            "load scripts/controlnet.py": 0.10791826248168945,
            "load scripts/controlnet_diffusers.py": 0.0,
            "load scripts/controlnet_lllite.py": 0.001003265380859375,
            "load scripts/controlnet_lora.py": 0.0,
            "load scripts/controlnet_model_guess.py": 0.0,
            "load scripts/controlnet_version.py": 0.0010035037994384766,
            "load scripts/external_code.py": 0.0,
            "load scripts/global_state.py": 0.0015032291412353516,
            "load scripts/hook.py": 0.0,
            "load scripts/infotext.py": 0.0010104179382324219,
            "load scripts/logging.py": 0.0,
            "load scripts/lvminthin.py": 0.0010056495666503906,
            "load scripts/movie2movie.py": 0.0,
            "load scripts/processor.py": 0.0010187625885009766,
            "load scripts/utils.py": 0.0,
            "load scripts/xyz_grid_support.py": 0.0010039806365966797,
            "load scripts/auto.py": 0.0,
            "load scripts/dino.py": 0.001003265380859375,
            "load scripts/process_params.py": 0.0,
            "load scripts/sam.py": 0.02761983871459961,
            "load scripts/ultimate-upscale.py": 0.0010001659393310547,
            "load scripts/ldsr_model.py": 0.025385379791259766,
            "load scripts/lora_script.py": 0.14406418800354004,
            "load scripts/scunet_model.py": 0.02053046226501465,
            "load scripts/swinir_model.py": 0.028201818466186523,
            "load scripts/hotkey_config.py": 0.0010106563568115234,
            "load scripts/extra_options_section.py": 0.0010061264038085938,
            "load scripts": 1.7657349109649658,
            "load upscalers": 0.002999544143676758,
            "refresh VAE": 0.0020003318786621094,
            "refresh textual inversion templates": 0.0,
            "scripts list_optimizers": 0.0010008811950683594,
            "scripts list_unets": 0.0,
            "reload hypernetworks": 0.006025552749633789,
            "initialize extra networks": 0.010311365127563477,
            "scripts before_ui_callback": 0.001004934310913086,
            "create ui": 0.4845919609069824,
            "gradio launch": 0.38541245460510254,
            "add APIs": 0.004511356353759766,
            "app_started_callback/api.py": 0.007003068923950195,
            "app_started_callback/lora_script.py": 0.0,
            "app_started_callback": 0.007003068923950195
        }
    },
    "Packages": [
        "absl-py==2.0.0",
        "accelerate==0.18.0",
        "addict==2.4.0",
        "aenum==3.1.15",
        "aiofiles==23.2.1",
        "aiohttp==3.9.1",
        "aiosignal==1.3.1",
        "albumentations==1.3.1",
        "altair==5.2.0",
        "antlr4-python3-runtime==4.9.3",
        "anyio==3.7.1",
        "async-timeout==4.0.3",
        "attrs==23.2.0",
        "basicsr==1.4.2",
        "beautifulsoup4==4.12.2",
        "blendmodes==2022",
        "boltons==23.1.1",
        "cachetools==5.3.2",
        "certifi==2023.11.17",
        "cffi==1.16.0",
        "chardet==5.2.0",
        "charset-normalizer==3.3.2",
        "clean-fid==0.1.35",
        "click==8.1.7",
        "clip==1.0",
        "colorama==0.4.6",
        "coloredlogs==15.0.1",
        "contourpy==1.2.0",
        "cssselect2==0.7.0",
        "cycler==0.12.1",
        "cython==3.0.7",
        "deprecation==2.1.0",
        "easydict==1.11",
        "einops==0.4.1",
        "exceptiongroup==1.2.0",
        "facexlib==0.3.0",
        "fastapi==0.94.0",
        "ffmpy==0.3.1",
        "filelock==3.13.1",
        "filterpy==1.4.5",
        "flatbuffers==23.5.26",
        "fonttools==4.47.0",
        "frozenlist==1.4.1",
        "fsspec==2023.12.2",
        "ftfy==6.1.3",
        "future==0.18.3",
        "fvcore==0.1.5.post20221221",
        "gdown==4.7.1",
        "gfpgan==1.3.8",
        "gitdb==4.0.11",
        "gitpython==3.1.30",
        "google-auth-oauthlib==1.2.0",
        "google-auth==2.25.2",
        "gradio-client==0.8.0",
        "gradio==3.32.0",
        "grpcio==1.60.0",
        "h11==0.12.0",
        "httpcore==0.15.0",
        "httpx==0.24.1",
        "huggingface-hub==0.20.1",
        "humanfriendly==10.0",
        "idna==3.6",
        "imageio==2.33.1",
        "importlib-metadata==7.0.1",
        "inflection==0.5.1",
        "insightface==0.7.3",
        "iopath==0.1.9",
        "jinja2==3.1.2",
        "joblib==1.3.2",
        "jsonmerge==1.8.0",
        "jsonschema-specifications==2023.12.1",
        "jsonschema==4.20.0",
        "kiwisolver==1.4.5",
        "kornia==0.6.7",
        "lark==1.1.2",
        "lazy-loader==0.3",
        "lightning-utilities==0.10.0",
        "linkify-it-py==2.0.2",
        "llvmlite==0.41.1",
        "lmdb==1.4.1",
        "lpips==0.1.4",
        "lxml==5.0.0",
        "markdown-it-py==2.2.0",
        "markdown==3.5.1",
        "markupsafe==2.1.3",
        "matplotlib==3.8.2",
        "mdit-py-plugins==0.3.3",
        "mdurl==0.1.2",
        "mediapipe==0.10.9",
        "mpmath==1.3.0",
        "multidict==6.0.4",
        "networkx==3.2.1",
        "numba==0.58.1",
        "numpy==1.23.5",
        "oauthlib==3.2.2",
        "omegaconf==2.2.3",
        "onnx==1.15.0",
        "onnxruntime-gpu==1.16.3",
        "open-clip-torch==2.20.0",
        "opencv-contrib-python==4.9.0.80",
        "opencv-python-headless==4.8.1.78",
        "opencv-python==4.9.0.80",
        "orjson==3.9.10",
        "packaging==23.2",
        "pandas==2.1.4",
        "piexif==1.1.3",
        "pillow==9.5.0",
        "pip==23.3.2",
        "platformdirs==4.1.0",
        "portalocker==2.8.2",
        "prettytable==3.9.0",
        "protobuf==4.25.1",
        "psutil==5.9.5",
        "pyasn1-modules==0.3.0",
        "pyasn1==0.5.1",
        "pycparser==2.21",
        "pydantic==1.10.13",
        "pydub==0.25.1",
        "pygments==2.17.2",
        "pyparsing==3.1.1",
        "pyreadline3==3.4.1",
        "pysocks==1.7.1",
        "python-dateutil==2.8.2",
        "python-multipart==0.0.6",
        "pytorch-lightning==1.9.4",
        "pytz==2023.3.post1",
        "pywavelets==1.5.0",
        "pywin32==306",
        "pyyaml==6.0.1",
        "qudida==0.0.4",
        "realesrgan==0.3.0",
        "referencing==0.32.0",
        "regex==2023.12.25",
        "reportlab==4.0.8",
        "requests-oauthlib==1.3.1",
        "requests==2.31.0",
        "resize-right==0.0.2",
        "rpds-py==0.16.2",
        "rsa==4.9",
        "safetensors==0.3.1",
        "scikit-image==0.20.0",
        "scikit-learn==1.3.2",
        "scipy==1.11.4",
        "segment-anything==1.0",
        "semantic-version==2.10.0",
        "sentencepiece==0.1.99",
        "setuptools==63.2.0",
        "six==1.16.0",
        "smmap==5.0.1",
        "sniffio==1.3.0",
        "sounddevice==0.4.6",
        "soupsieve==2.5",
        "starlette==0.26.1",
        "supervision==0.17.1",
        "svglib==1.5.1",
        "sympy==1.12",
        "tabulate==0.9.0",
        "tb-nightly==2.16.0a20240101",
        "tensorboard-data-server==0.7.2",
        "termcolor==2.4.0",
        "tf-keras-nightly==2.16.0.dev2023123010",
        "threadpoolctl==3.2.0",
        "tifffile==2023.12.9",
        "timm==0.6.7",
        "tinycss2==1.2.1",
        "tokenizers==0.13.3",
        "tomesd==0.1.2",
        "tomli==2.0.1",
        "toolz==0.12.0",
        "torch==2.0.1+cu118",
        "torchdiffeq==0.2.3",
        "torchmetrics==1.2.1",
        "torchsde==0.2.5",
        "torchvision==0.15.2+cu118",
        "tqdm==4.66.1",
        "trampoline==0.1.2",
        "transformers==4.25.1",
        "typing-extensions==4.9.0",
        "tzdata==2023.4",
        "uc-micro-py==1.0.2",
        "urllib3==2.1.0",
        "uvicorn==0.25.0",
        "wcwidth==0.2.12",
        "webencodings==0.5.1",
        "websockets==11.0.3",
        "werkzeug==3.0.1",
        "yacs==0.1.8",
        "yapf==0.40.2",
        "yarl==1.9.4",
        "zipp==3.17.0"
    ]
}

### Relevant console log

```Shell
venv "C:\Users\pc\Documents\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.5.1
Commit hash: 68f336bd994bed5442ad95bad6b6ad5564a5409a

ReActor preheating... Device: CUDA


Launching Web UI with arguments:
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.

========================= a1111-sd-webui-lycoris =========================
Starting from stable-diffusion-webui version 1.5.0
a1111-sd-webui-lycoris extension is no longer needed

All its features have been integrated into the native LoRA extension
LyCORIS models can now be used as if there are regular LoRA models

This extension has been automatically deactivated
Please remove this extension
==========================================================================

[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
2024-01-02 02:51:57,582 - ControlNet - INFO - ControlNet v1.1.410
ControlNet preprocessor location: C:\Users\pc\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2024-01-02 02:51:57,722 - ControlNet - INFO - ControlNet v1.1.410
02:51:58 - ReActor - STATUS - Running v0.6.0-a4
Loading weights [fc2511737a] from C:\Users\pc\Documents\stable-diffusion-webui\models\Stable-diffusion\chilloutmix_NiPrunedFp32Fix.safetensors
*** Error calling: C:\Users\pc\Documents\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py/ui
    Traceback (most recent call last):
      File "C:\Users\pc\Documents\stable-diffusion-webui\modules\scripts.py", line 339, in wrap_call
        return func(*args, **kwargs)
      File "C:\Users\pc\Documents\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 44, in ui
        with ui_components.InputAccordion(False, label=f"{app_title}") as enable:
    AttributeError: module 'modules.ui_components' has no attribute 'InputAccordion'

---
*** Error calling: C:\Users\pc\Documents\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py/ui
    Traceback (most recent call last):
      File "C:\Users\pc\Documents\stable-diffusion-webui\modules\scripts.py", line 339, in wrap_call
        return func(*args, **kwargs)
      File "C:\Users\pc\Documents\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 44, in ui
        with ui_components.InputAccordion(False, label=f"{app_title}") as enable:
    AttributeError: module 'modules.ui_components' has no attribute 'InputAccordion'

---
calling C:\Users\pc\Documents\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py/ui: AttributeError
Traceback (most recent call last):
  File "C:\Users\pc\Documents\stable-diffusion-webui\modules\scripts_postprocessing.py", line 53, in wrap_call
    res = func(*args, **kwargs)
  File "C:\Users\pc\Documents\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 414, in ui
    with ui_components.InputAccordion(False, label=f"{app_title}") as enable:
AttributeError: module 'modules.ui_components' has no attribute 'InputAccordion'

Traceback (most recent call last):
  File "C:\Users\pc\Documents\stable-diffusion-webui\launch.py", line 39, in <module>
    main()
  File "C:\Users\pc\Documents\stable-diffusion-webui\launch.py", line 35, in main
    start()
  File "C:\Users\pc\Documents\stable-diffusion-webui\modules\launch_utils.py", line 394, in start
    webui.webui()
  File "C:\Users\pc\Documents\stable-diffusion-webui\webui.py", line 393, in webui
    shared.demo = modules.ui.create_ui()
  File "C:\Users\pc\Documents\stable-diffusion-webui\modules\ui.py", line 1061, in create_ui
    ui_postprocessing.create_ui()
  File "C:\Users\pc\Documents\stable-diffusion-webui\modules\ui_postprocessing.py", line 25, in create_ui
    script_inputs = scripts.scripts_postproc.setup_ui()
  File "C:\Users\pc\Documents\stable-diffusion-webui\modules\scripts_postprocessing.py", line 113, in setup_ui
    self.create_script_ui(script, inputs)
  File "C:\Users\pc\Documents\stable-diffusion-webui\modules\scripts_postprocessing.py", line 84, in create_script_ui
    for control in script.controls.values():
AttributeError: 'NoneType' object has no attribute 'values'
Creating model from config: C:\Users\pc\Documents\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying attention optimization: Doggettx... done.
Model loaded in 2.9s (load weights from disk: 0.4s, create model: 0.6s, apply weights to model: 0.7s, apply half(): 0.6s, move model to device: 0.5s, calculate empty prompt: 0.1s).
Press any key to continue . . .
```
```


### Additional information

_No response_

**Comment by Gourieff** [comment]
https://github.com/Gourieff/sd-webui-reactor/issues?q=is%3Aissue+is%3Aclosed+has+no+attribute+%27InputAccordion%27

**Comment by unalman** [comment]
thank you very much
