### ISSUE TITLE
can not work

### ISSUE THREAD

**Issue by savadica** [Gourieff/sd-webui-reactor#305]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Both automatic1111 and reactor are the latest versions. The extension has been installed successfully and the UI has been restarted, but the reactor function cannot be seen in the ribbon.

### Steps to reproduce the problem

Both automatic1111 and reactor are the latest versions. The extension has been installed successfully and the UI has been restarted, but the reactor function cannot be seen in the ribbon.

### Sysinfo

Both automatic1111 and reactor are the latest versions. The extension has been installed successfully and the UI has been restarted, but the reactor function cannot be seen in the ribbon.

### Relevant console log

```Shell
Both automatic1111 and reactor are the latest versions. The extension has been installed successfully and the UI has been restarted, but the reactor function cannot be seen in the ribbon.
```

**Comment by Gourieff** [comment]
Please fill out all the required fields (sysinfo and so on) and provide the full log from your Console or Terminal
