### ISSUE TITLE
How to use Reactor plugin on web server?

### ISSUE THREAD

**Issue by justinason** [Gourieff/sd-webui-reactor#316]
### Feature description

Hi guys. Is it possible to use Reactor plugin on web server? We want to create a face swapping service online available for customers worldwide.

**Comment by Gourieff** [comment]
Hi!
This is not the issue to create such online service, the main point is that you cannot use Inswapper model for commercial purposes due to the Insightface licence

**Comment by justinason** [comment]
> Hi! This is not the issue to create such online service, the main point is that you cannot use Inswapper model for commercial purposes due to the Insightface licence

Thank you. We are planning to have a free face swap (non commercial) service and gradually transition into commercial licence, provided by Insight Face when we have a big user base. However, until we reach needed amount of calls the Insight Face does not provide us with API. So for that we need some solution for process automation. What solution could we used for that?

**Comment by Gourieff** [comment]
You need a good server with GPU CUDA, A1111 or ComfyUI as the base server application, installed ReActor extension or Node and that's all, you can use ReActor's [API](https://github.com/Gourieff/sd-webui-reactor/blob/main/API.md) (you can find examples inside the examples folder) with A1111/SD.Next or any pipeline you need with ComfyUI+TD
And I will be very glad if you mention this extension as the Core for swapping, a lot of work has been done to make all these things "fast and furious"... And a lot of work is in the plans...

**Comment by justinason** [comment]
> You need a good server with GPU CUDA, A1111 or ComfyUI as the base server application, installed ReActor extension or Node and that's all, you can use ReActor's [API](https://github.com/Gourieff/sd-webui-reactor/blob/main/API.md) (you can find examples inside the examples folder) with A1111/SD.Next or any pipeline you need with ComfyUI+TD And I will be very glad if you mention this extension as the Core for swapping, a lot of work has been done to make all these things "fast and furious"... And a lot of work is in the plans...

Thank you, That is very helpful. We will mention you guys. The work you do is very really meaningful.
Also, maybe you have in mind using some additional AI models for faceswap and facemorph, not just Insight Face? Because they have a really high bar in order to go to into commercial licence.

**Comment by justinason** [comment]
> You need a good server with GPU CUDA, A1111 or ComfyUI as the base server application, installed ReActor extension or Node and that's all, you can use ReActor's [API](https://github.com/Gourieff/sd-webui-reactor/blob/main/API.md) (you can find examples inside the examples folder) with A1111/SD.Next or any pipeline you need with ComfyUI+TD And I will be very glad if you mention this extension as the Core for swapping, a lot of work has been done to make all these things "fast and furious"... And a lot of work is in the plans...

Do you guys think you could consult us how to connect Reactor and Stable Diffusion to your API and make it online? What would be your consultation fee?

**Comment by Gourieff** [comment]
You can PM me via Telegram [@gourieff](https://t.me/gourieff)

**Comment by Gourieff** [comment]
> Also, maybe you have in mind using some additional AI models for faceswap and facemorph, not just Insight Face?
Inswapper model is still the best one even with such a low res 128px
