### ISSUE TITLE
cuda12 can't used?

### ISSUE THREAD

**Issue by rigelzhang** [Gourieff/sd-webui-reactor#319]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

When I used reactor, it encountered some errors, like this` RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:743 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported`, does it support cuda12?

### Steps to reproduce the problem

1. txt2img,img2img can't use

### Sysinfo

gpu 4070 .latest SD WEBUI

### Relevant console log

```Shell
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:743 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported
```

**Comment by Gourieff** [comment]
No, not yet https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements
