### ISSUE TITLE
[SOLVED] Dependencies Conflict

### ISSUE THREAD

**Issue by GunnyNinja** [Gourieff/sd-webui-reactor#32]
I started getting the restart server message. I did that. nothing. I deleted and reinstalled. Followed all troubleshooting. Started getting Done! message. Restarting UI did nothing. Installed a branch 21 commits behind yours. works again.

**Comment by Gourieff** [comment]
Console log please and what SD WebUI you use

**Comment by Gourieff** [comment]
I've just tried to do the clear install on the latest A1111, works perfect with no errors
Also tried with Cagliostro Colab UI - perfect, no errors during the install, no errors while swapping

**Comment by deezee999** [comment]
I'm having issues too. Despite following troubleshooting I get this, 

  ValueError: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)

**Comment by Gourieff** [comment]
> I'm having issues too. Despite following troubleshooting I get this,
> 
> ValueError: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)

Please read https://github.com/Gourieff/sd-webui-roop-nsfw#troubleshooting sec VI
You need `onnxruntime==1.15.0` to be installed
Not `onnxruntime-gpu` or `onnxruntime-silicon`
The only way to get this error is if you're experimenting with "onnxruntime" package or you have another extension that uninstalls `onnxruntime` and installs `onnxruntime-gpu` or `onnxruntime-silicon` every time when SD WebUI server starts and checks requirements

This extension won't correctly work or won't work at all without the correct "onnxruntime" package

That's why it can cause the issue with permanent "restart request". SD WebUI server installing "onnxruntime" for this extension, but highly likely that another extension calls to uninstall "onnxruntime" and install "gpu" or "silicon" version

So guys check your other extensions please 
Today I've tested my extension on different platforms and with different SD WebUIs - everything works without any errors out of the box

**Comment by GunnyNinja** [comment]
> > I'm having issues too. Despite following troubleshooting I get this,
> > ValueError: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)
> 
> Please read https://github.com/Gourieff/sd-webui-roop-nsfw#troubleshooting sec VI You need `onnxruntime==1.15.0` to be installed Not `onnxruntime-gpu` or `onnxruntime-silicon` The only way to get this error is if you're experimenting with "onnxruntime" package or you have another extension that uninstalls `onnxruntime` and installs `onnxruntime-gpu` every time when SD WebUI server starts and checks requirements
> 
> This extension won't correctly work or won't work at all without the correct "onnxruntime" package
> 
> That's why it can cause the issue with permanent "restart request". SD WebUI server installing "onnxruntime" for this extension, but highly likely that another extension calls to uninstall "onnxruntime" and to install "onnxruntime-gpu" version
> 
> So guys check your other extensions please Today I've tested my extension on different platforms and with different SD WebUIs - everything works without any errors out of the box

I got this as well and followed the steps you listed. I did not change anything. I had the same problem on two PC's but reinstalling only worked on one of them.

**Comment by GunnyNinja** [comment]
> Console log please and what SD WebUI you use What OS do you use? What the package is trying to be installed (or reinstalled) during the SD WebUI boot?
> 
> Please provide more info for the Issue

A1111 on Windows 11. I will get you a log next time I am on that machine.

**Comment by deezee999** [comment]
Tried what you @Gourieff recommended again. No luck. Here is a more complete error code: 

`EP Error D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\DW\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
EP Error D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\DW\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
EP Error D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\DW\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
EP Error D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\DW\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
EP Error D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\DW\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
*** Error running postprocess_image: C:\Users\DW\stable-diffusion-webui\extensions\sd-webui-roop-nsfw\scripts\faceswap.py
    Traceback (most recent call last):
      File "C:\Users\DW\stable-diffusion-webui\modules\scripts.py", line 575, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "C:\Users\DW\stable-diffusion-webui\extensions\sd-webui-roop-nsfw\scripts\faceswap.py", line 213, in postprocess_image
        result = swap_face(
      File "C:\Users\DW\stable-diffusion-webui\extensions\sd-webui-roop-nsfw\scripts\swapper.py", line 169, in swap_face        source_face = get_face_single(source_img, face_index=source_faces_index[0])
      File "C:\Users\DW\stable-diffusion-webui\extensions\sd-webui-roop-nsfw\scripts\swapper.py", line 129, in get_face_single
        face_analyser = copy.deepcopy(getAnalysisModel())
      File "C:\Users\DW\AppData\Local\Programs\Python\Python310\lib\copy.py", line 172, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "C:\Users\DW\AppData\Local\Programs\Python\Python310\lib\copy.py", line 271, in _reconstruct
        state = deepcopy(state, memo)
      File "C:\Users\DW\AppData\Local\Programs\Python\Python310\lib\copy.py", line 146, in deepcopy
        y = copier(x, memo)
      File "C:\Users\DW\AppData\Local\Programs\Python\Python310\lib\copy.py", line 231, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "C:\Users\DW\AppData\Local\Programs\Python\Python310\lib\copy.py", line 146, in deepcopy
        y = copier(x, memo)
      File "C:\Users\DW\AppData\Local\Programs\Python\Python310\lib\copy.py", line 231, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "C:\Users\DW\AppData\Local\Programs\Python\Python310\lib\copy.py", line 172, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "C:\Users\DW\AppData\Local\Programs\Python\Python310\lib\copy.py", line 271, in _reconstruct
        state = deepcopy(state, memo)
      File "C:\Users\DW\AppData\Local\Programs\Python\Python310\lib\copy.py", line 146, in deepcopy
        y = copier(x, memo)
      File "C:\Users\DW\AppData\Local\Programs\Python\Python310\lib\copy.py", line 231, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "C:\Users\DW\AppData\Local\Programs\Python\Python310\lib\copy.py", line 172, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "C:\Users\DW\AppData\Local\Programs\Python\Python310\lib\copy.py", line 273, in _reconstruct
        y.__setstate__(state)
      File "C:\Users\DW\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 33, in __setstate__
        self.__init__(model_path)
      File "C:\Users\DW\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
        super().__init__(model_path, **kwargs)
      File "C:\Users\DW\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 396, in __init__
        raise e
      File "C:\Users\DW\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
        self._create_inference_session(providers, provider_options, disabled_optimizers)
      File "C:\Users\DW\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 415, in _create_inference_session
        raise ValueError(
    ValueError: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)`

**Comment by Gourieff** [comment]
> FAIL : LoadLibrary failed with error 126 "" when trying to load **"C:\Users\DW\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"** when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']

This string means that you have gpu version of "onnxruntime" package, because simple "onnxruntime" has no such provider library inside (as onnxruntime_providers_tensorrt.dll or cuda) or your version is partly installed and mixed with gpu version
Such libraries are only inside the "onnxruntime-gpu" package but ORT cannot find them
Non-gpu "onnxruntime" has the only one dll inside the "capi": "onnxruntime_providers_shared.dll" and never refers to tensorrt or cuda providers

You need to uninstall "onnxruntime-gpu" or corrupted version of "onnxruntime" inside your activated venv:
- run cmd in sd-webui root -> .\venv\Scripts\activate
- then: pip uninstall -y onnxruntime onnxruntime-gpu
- then look for the folders with names starting from "~" (inside the directory "stable-diffusion-webui\venv\lib\site-packages", e.g. "~rotobuf", "~nnxruntime" etc.), delete them
- then: pip install onnxruntime==1.15.0

Or you can manually delete two folders with names containing "onnxruntime" inside the "site-packages" directory and then "pip install onnxruntime==1.15.0" within the activated venv

After that everything should work pretty fine unless there are any extensions trying to reinstall "onnxruntime" to a different version

**Comment by Gourieff** [comment]
> > Console log please and what SD WebUI you use What OS do you use? What the package is trying to be installed (or reinstalled) during the SD WebUI boot?
> > Please provide more info for the Issue
> 
> A1111 on Windows 11. I will get you a log next time I am on that machine.

Ok, will wait

**Comment by deezee999** [comment]
> After that everything should work pretty fine unless there are any extensions trying to reinstall "onnxruntime" to a different version

Did exactly what you said. Still got the same error, I'll see if I can find any other extensions that could be messing it up. Don't know where to start though.

**Comment by Gourieff** [comment]
Try clear install of A1111 with only built-in extensions and then add others one-by-one starting from this one

**Comment by deezee999** [comment]
Tried a fresh install of A1111 on my other hard drive and it worked. I don't know what could be causing it on my main A1111 setup though. I'll let you know if I run into the cause.

**Comment by deezee999** [comment]
Figured it out on my end. It was the WD14 tagger extension causing issues. After disabling it and a fresh uninstall of onnxruntime-gpu, and reinstalling onnx==1.14.0 and onnxruntime==1.15.0 it worked great. Thanks for leading me into the right direction.

**Comment by 1nterfect0rem** [comment]
![image](https://github.com/Gourieff/sd-webui-roop-nsfw/assets/110246177/c45de0b8-78b0-4e1a-a1b8-f0ba8f185148)
What should I do with this, I use the portable version of Automatic, I did everything according to the instructions, in general I even have VS and C ++, I tried different installation methods, as a result, in both cases it ended with this

**Comment by Gourieff** [comment]
@1nterfect0rem Hm... Try to set "Console Log Level" to the "Default" value, it should work

**Comment by Gourieff** [comment]
> Figured it out on my end. It was the WD14 tagger extension causing issues. After disabling it and a fresh uninstall of onnxruntime-gpu, and reinstalling onnx==1.14.0 and onnxruntime==1.15.0 it worked great. Thanks for leading me into the right direction.

You're welcome! I'm glad that it's figured out! And thank you as well that you brought this issue to the finish line :) I will add an info about the WD14 tagger to the Troubleshooting section

**Comment by 1nterfect0rem** [comment]
> > > 
> > 
> > 
> > here? i don't know, not experienced enough i guess (ignore blue color, just accident) ![image](https://user-images.githubusercontent.com/110246177/258155225-ea555e81-4297-49d8-a815-c35e0da45298.png)
> 
> In the UI, just set the level to the Default ![here](https://user-images.githubusercontent.com/85128026/258155857-a0914e62-669b-465c-b715-2c3220df110a.png)

![image](https://github.com/Gourieff/sd-webui-roop-nsfw/assets/110246177/6bc8231f-46e1-485f-b5a5-ca149d3035b7)
ok, but idk why it should work

**Comment by 1nterfect0rem** [comment]
@Gourieff 
![image](https://github.com/Gourieff/sd-webui-roop-nsfw/assets/110246177/9d8fa15e-6d9c-407f-bcac-b202f7738923)

**Comment by Gourieff** [comment]
Very strange... Maybe you have another Python instance running with active A1111?

**Comment by 1nterfect0rem** [comment]
@Gourieff In general, okay, I will describe the situation in more detail in all colors. First I installed automatic from the author himself, it was a couple of months ago, I also installed the roop, swf version there, downloaded VS and C ++, Then a couple of days ago I decided to download the portable version from Xpuct, I think you know who it is . He also has a tutorial on how to install roop. and just leads a link to your version. But its portable version contains everything in one folder. That is, the python is also most likely re-downloaded, and I kind of didn’t delete the old python and VS. Everything else works well, except for roop

**Comment by Gourieff** [comment]
Franky, I haven't tried the Xpuct's portable version yet
So I will try it tomorrow following his instruction and see what can be wrong

**Comment by 1nterfect0rem** [comment]
@Gourieff basically his instructions is 
![image](https://github.com/Gourieff/sd-webui-reactor/assets/110246177/0a9bcd1f-bf54-4a9f-93ee-2e4c72669844)

**Comment by 1nterfect0rem** [comment]
@Gourieff I do not know what exactly the reason was, but a complete reinstallation helped, perhaps the new roop could really somehow use the models of the old roop from another directory and this could cause conflicts. And perhaps at some point the installation of models did not go quite according to plan

**Comment by Gourieff** [comment]
That's nice!
A clean install often really solves any issues :)
