### ISSUE TITLE
Error with Img2Img

### ISSUE THREAD

**Issue by KakaoXI** [Gourieff/sd-webui-reactor#326]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

When i use all samplers excluded DPM +2 Karras and Euler a, stable diffusion says this error:  UnboundLocalError: local variable 'h' referenced before assignment

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3.  UnboundLocalError: local variable 'h' referenced before assignment

### Sysinfo

Windows 11

### Relevant console log

```Shell
UnboundLocalError: local variable 'h' referenced before assignment
```

**Comment by KakaoXI** [comment]
``  0%|                                                                                            | 0/1 [00:02<?, ?it/s]
*** Error completing request                                                                     | 0/1 [00:00<?, ?it/s]
*** Arguments: ('task(kfdsju4yd5mvyes)', 0, '', '', [], <PIL.Image.Image image mode=RGBA size=896x1344 at 0x286249DE7D0>, None, None, None, None, None, None, 20, 'DPM++ 2M SDE Karras', 4, 0, 1, 1, 1, 7, 1.5, 0, 0, 1344, 896, 1, 0, 0, 32, 0, '', '', '', [], False, [], '', <gradio.routes.Request object at 0x000002862497E350>, 0, False, '', 0.8, -1, False, -1, 0, 0, 0, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', UiControlNetUnit(enabled=False, module='none', model='None', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', inpaint_crop_input_image=False, hr_option='Both', save_detected_map=True, advanced_weighting=None), UiControlNetUnit(enabled=False, module='none', model='None', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', inpaint_crop_input_image=False, hr_option='Both', save_detected_map=True, advanced_weighting=None), UiControlNetUnit(enabled=False, module='none', model='None', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', inpaint_crop_input_image=False, hr_option='Both', save_detected_map=True, advanced_weighting=None), None, '', None, True, False, False, False, False, False, 0, 0, '0', 0, False, True, 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, None, 1, 1, '', False, False, False, 1, 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, None, '', None, True, False, False, False, False, False, 0, 0, '0', 0, False, True, 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, None, 1, 1, '', False, False, False, 1, 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, None, '', None, True, False, False, False, False, False, 0, 0, '0', 0, False, True, 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, None, 1, 1, '', False, False, False, 1, 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, None, 1, 1, '', 1, 1, ['After Upscaling/Before Restore Face'], 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, <PIL.Image.Image image mode=RGB size=716x579 at 0x286249DD490>, True, '0', '0', 'inswapper_128.onnx', 'CodeFormer', 1, True, 'None', 1, 1, False, True, 1, 0, 0, False, 0.5, True, False, 'CUDA', False, 0, 'None', '', None, None, False, '0', 'D:\\Generale\\Ricordi\\StableDiffusion\\models\\roop\\inswapper_128.onnx', 'CodeFormer', 1, '', 1, 1, False, True, '* `CFG Scale` should be 2 or lower.', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, 'start', '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, None, None, False, None, None, False, None, None, False, 50, '<p style="margin-bottom:0.75em">Will upscale the image depending on the selected target size type</p>', 512, 0, 8, 32, 64, 0.35, 32, 0, True, 0, False, 8, 0, 0, 2048, 2048, 2) {}
    Traceback (most recent call last):
      File "D:\Generale\Ricordi\StableDiffusion\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
                   ^^^^^^^^^^^^^^^^^^^^^
      File "D:\Generale\Ricordi\StableDiffusion\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
      File "D:\Generale\Ricordi\StableDiffusion\modules\img2img.py", line 238, in img2img
        processed = process_images(p)
                    ^^^^^^^^^^^^^^^^^
      File "D:\Generale\Ricordi\StableDiffusion\modules\processing.py", line 734, in process_images
        res = process_images_inner(p)
              ^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Generale\Ricordi\StableDiffusion\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Generale\Ricordi\StableDiffusion\modules\processing.py", line 868, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Generale\Ricordi\StableDiffusion\modules\processing.py", line 1527, in sample
        samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Generale\Ricordi\StableDiffusion\modules\sd_samplers_kdiffusion.py", line 188, in sample_img2img
        samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Generale\Ricordi\StableDiffusion\modules\sd_samplers_common.py", line 261, in launch_sampling
        return func()
               ^^^^^^
      File "D:\Generale\Ricordi\StableDiffusion\modules\sd_samplers_kdiffusion.py", line 188, in <lambda>
        samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Generale\Ricordi\StableDiffusion\venv\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "D:\Generale\Ricordi\StableDiffusion\repositories\k-diffusion\k_diffusion\sampling.py", line 651, in sample_dpmpp_2m_sde
        h_last = h
                 ^
    UnboundLocalError: cannot access local variable 'h' where it is not associated with a value``

**Comment by Gourieff** [comment]
ReActor has nothing to do with this error

**Comment by KakaoXI** [comment]
> ReActor has nothing to do with this error

I have this issue only with ReActor

**Comment by Gourieff** [comment]
I can see that you have "roop" in the log and no ReActor
ReActor doesn't use the path "D:\Generale\Ricordi\StableDiffusion\models\\**roop**\\inswapper_128.onnx"

**Comment by KakaoXI** [comment]
I have also reactor, when i enable reactor use that idk why

**Comment by Gourieff** [comment]
According to the log you have no errors with ReActor but you have Roop enabled
I can suggest you to delete both extensions and install only one of them
You probably have the dependencies conflict, sd-webui-roop is deprecated and not being updated for months, it can cause conflicts with other extensions which use the most actual requirements

**Comment by KakaoXI** [comment]
I will try thanks

**Comment by KakaoXI** [comment]
also removing roop i have same issue

**Comment by KakaoXI** [comment]
![Screenshot 2024-01-16 154012](https://github.com/Gourieff/sd-webui-reactor/assets/79526923/8d819c2a-53ef-4384-b631-1eb4c99ea6ea)

**Comment by KakaoXI** [comment]
Is working only with denoising streght at 0.75, because also without reactor doesn't work with denoising streght at 0, but i need denoising at 0 with reactor

**Comment by Gourieff** [comment]
Instead of denoising 0 you can use ReActor via Extras tab

**Comment by KakaoXI** [comment]
So i can put a face over an image also with extra? However i saw that also without reactor enabled don't work same with denoising0, so is not reactor, denoising 0 doesn't work with SDE in img2img

**Comment by KakaoXI** [comment]
But in extra i can't choose a sampler
