### ISSUE TITLE
[Feature]: X/Y/Z plot parameters

### ISSUE THREAD

**Issue by ledahu** [Gourieff/sd-webui-reactor#329]
### Feature description

Hello, 

Maybe i didn't saw them, but i can't find the ReActor parameters in the X/Y/Z script to try different values 

Did i miss something ? 

Thank you

**Comment by mykeehu** [comment]
I think it is a good idea, especially for the Face Model, to be able to change the output. I've done a lot of Face Models and this way I could generate the best version of the face for the image.

**Comment by Gourieff** [comment]
Hi guys
This feature will be added soon

**Comment by Gourieff** [comment]
Done!

**Comment by mykeehu** [comment]
You're fantastic, thank you!

**Comment by Gourieff** [comment]
> I think it is a good idea, especially for the Face Model, to be able to change the output. I've done a lot of Face Models and this way I could generate the best version of the face for the image.

"Face Model" axis is also ready! Good idea 👍
