### ISSUE TITLE
VRAM≤8GB | Reactor Slowing Down Generating Images

### ISSUE THREAD

**Issue by GeneralHealer** [Gourieff/sd-webui-reactor#339]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

When I use Reactor or Image2Image to generate an image for the first time, it works fine. But when I try again, it becomes very slow, taking from 6 to 11 seconds per step depending on the resolution. I have tried reinstalling it, but it did not solve the problem.

### Steps to reproduce the problem

I already explained it.

### Sysinfo

Windows, Chrome, GTX 1660 6gb, AUTOMATIC1111, Extensions: adetailer, multidiffusion-upscaler-for-automatic1111, sd-webui-controlnet, sd-webui-reactor.

### Relevant console log

```Shell
Normal console log.
```

**Comment by GeneralHealer** [comment]
I switched from CUDA to CPU and it seems to fix it for now.

**Comment by Gourieff** [comment]
Yes, known issue of the ORT-GPU implementation
You can read here for some details: https://github.com/Gourieff/sd-webui-reactor/issues/307#issuecomment-1876994178
