### ISSUE TITLE
Changing the github repository link name

### ISSUE THREAD

**Issue by Kaneki010** [Gourieff/sd-webui-reactor#34]
first , i wanna thank you for your hard work on this extension  🙏, at this point this is better than the original extension in all aspects
ok now i'll move to the subject . 
even after changing the repository name , the github link to it is still " 
Gourieff/sd-webui-roop-nsfw " which might cause slight confusion , and it would be generally more convenient if the name was reactor (dope name btw) 
*also , colab refuses and stop properly running any code that has " webui " in it , so that's another reason

**Comment by Gourieff** [comment]
Thanks for your good words 🤝
Yeah, you're right, I've been also thinking about changing the link and as I know Github will permanently keep redirects from the old url to a new one
It remains only to test how the updates will work within the SD WebUI, but I think it should work ok

> *also , colab refuses and stop properly running any code that has " webui " in it , so that's another reason

Wow... Thanks for the info, I didn't know that

**Comment by Kaneki010** [comment]
well when i try to install any lora /extension it works but if the link has "webui" in it it doesn't work , an example colab : " colab.research.google.com/drive/1wEa-tS10h4LlDykd87TF5zzpXIIQoCmq#scrollTo=8Uvqba0yKW7U "

its not a real problem though , as anyone can just make a personal fork with a different name so colab doesn't detect it . so as long as you personally like the name you want to put then you should put it ( i personally really love it )

**Comment by Gourieff** [comment]
And you're right again :)

**Comment by Gourieff** [comment]
Done 🚀
