### ISSUE TITLE
Generated Imaged not getting saved

### ISSUE THREAD

**Issue by AnnieBunnieX** [Gourieff/sd-webui-reactor#342]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Generated Imaged not saving. Only saving when "Save Original" enabled. Sorry for my bad English.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### Sysinfo

NA

### Relevant console log

```Shell
NA
```

**Comment by Gourieff** [comment]
Can you provide your workflow and the log from your Console when you generate images with face swapping?

**Comment by AnnieBunnieX** [comment]
Hi Eugene,
I simply added my face and Generated using Automatic1111. Once generation if complete I can see the swapped image on browser. When I go to the folder the image is not save. In order to fix this, I'm turning on "Save Original" option to get both Original as Swapped Image.

As of now in order to fix this I'm using "Save Original" option.

Also on Console, It looks normal and no errors. 

I don't know how to provide the info that you asked. _**scarlet_skye**_ is my Discord. Feel free to ping me I will share my screen and show you the issue.

**Comment by AnnieBunnieX** [comment]
Hi @Gourieff ,
Thank you for the quick update and fix. I will give it a try and update you if it is fixed or not.
