### ISSUE TITLE
No module named 'insightface' despite attempting all the fixes :(

### ISSUE THREAD

**Issue by marcusaureliusfun** [Gourieff/sd-webui-reactor#35]
I've tried a number of things to fix this error on launching the webui to no avail, along with a few reinstalls of the extension.

Every time I start the server I get this error:
Collecting insightface==0.7.3
  Using cached insightface-0.7.3.tar.gz (439 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
Checking ReActor (ex Roop-GE) requirements...
--- PLEASE, RESTART the Server! ---

This is following by three import errors:
  File "C:\Program Files\sd.webui\webui\extensions\sd-webui-roop-nsfw\scripts\console_log_patch.py", line 4, in <module>
    import insightface
ModuleNotFoundError: No module named 'insightface'

  File "C:\Program Files\sd.webui\webui\extensions\sd-webui-roop-nsfw\scripts\swapper.py", line 10, in <module>
    import insightface
ModuleNotFoundError: No module named 'insightface'

  File "C:\Program Files\sd.webui\webui\extensions\sd-webui-roop-nsfw\scripts\swapper.py", line 10, in <module>
    import insightface
ModuleNotFoundError: No module named 'insightface'

I tried following this section to fix the issue, but no luck (II. Any problems with installing Insightface or other dependencies)

I then followed this section to try installing the prebuilt one:
VIII. (For Windows users) If you still cannot build Insightface for some reasons or just don't want to install Visual Studio or VS C++ Build Tools - do the following:

> pip install insightface-0.7.3-cp310-cp310-win_amd64.whl
This errors, telling me I already have insightface installed.
insightface is already installed with the same version as the provided wheel.

So I also tried reinstalling it:
pip install insightface-0.7.3-cp310-cp310-win_amd64.whl --force-reinstall

I do get an error when trying to force-reinstall insightface but it says it is successfully installed
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xformers 0.0.17 requires pyre-extensions==0.0.23, which is not installed.
blendmodes 2022 requires Pillow<10,>=9.0.0, but you have pillow 10.0.0 which is incompatible.
google-auth 2.20.0 requires urllib3<2.0, but you have urllib3 2.0.4 which is incompatible.
mediapipe 0.10.1 requires protobuf<4,>=3.11, but you have protobuf 4.23.4 which is incompatible.
numba 0.57.0 requires numpy<1.25,>=1.21, but you have numpy 1.25.2 which is incompatible.
open-clip-torch 2.7.0 requires protobuf==3.20.0, but you have protobuf 4.23.4 which is incompatible.
xformers 0.0.17 requires torch==2.0.0, but you have torch 2.0.1+cu118 which is incompatible.

So for some reason everything indicates that I successfully installed insightface but I get errors that it isn't available when launching the webui. Any idea what might be causing this?

**Comment by Gourieff** [comment]
Look for the Insightface package in "webui\venv\Lib\site-packages"
Do you have it there? Are there any folders with names start from "~"? If they are - delete them and then reinstall Insightface through the activated venv

Also you have a wrong version of protobuf 4.23.4, you need 3.20.3 or 3.20.0
So you need to reinstall it
pip install protobuf==3.20.3

**Comment by marcusaureliusfun** [comment]
Thanks for the reply! :) I walked through these recommendations.. I get the same error though :( Fortunately, for some reason, running as administrator lets SD find the insightface package. It still doesn't work when I run without admin.

> Look for the Insightface package in "webui\venv\Lib\site-packages"
Yep, I find these two entries there:
insightface
insightface-0.7.3.dist-info

> Are there any folders with names start from "~"?
I found a folder there called ~umpy and deleted it.

> Also you have a wrong version of protobuf 4.23.4, you need 3.20.3 or 3.20.0
Switched to protobuf 3.20.3
Installing collected packages: protobuf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 4.23.4
    Uninstalling protobuf-4.23.4:
      Successfully uninstalled protobuf-4.23.4

**Comment by marcusaureliusfun** [comment]
Going to close since I think this is probably my fault installing something as admin somewhere along the way. I read somewhere I might be able to fix that by just copy the folder and using the copied version, but I'm content for now.

**Comment by sudip550** [comment]
> Look for the Insightface package in "webui\venv\Lib\site-packages" Do you have it there? Are there any folders with names start from "~"? If they are - delete them and then reinstall Insightface through the activated venv
> 
> Also you have a wrong version of protobuf 4.23.4, you need 3.20.3 or 3.20.0 So you need to reinstall it pip install protobuf==3.20.3


when i am going to run sd webui im getting below error =

modelnotfounderror: no module named insightface.models_zoo
