### ISSUE TITLE
[SOLVED] AttributeError: module 'numpy' has no attribute 'warnings'

### ISSUE THREAD

**Issue by Arctycus** [Gourieff/sd-webui-reactor#38]
16:23:11-346996 ERROR    Module load: H:\Vladmatic\automatic\extensions\sd-webui-reactor\scripts\faceswap.py:
                         AttributeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ H:\Vladmatic\automatic\modules\script_loading.py:10 in load_module                                                  │
│                                                                                                                     │
│    9 │   try:                                                                                                       │
│ > 10 │   │   module_spec.loader.exec_module(module)                                                                 │
│   11 │   except Exception as e:                                                                                     │
│ in exec_module:883                                                                                                  │
│                                                                                                                     │
│                                               ... 2 frames hidden ...                                               │
│                                                                                                                     │
│ H:\Vladmatic\automatic\extensions\sd-webui-reactor\scripts\swapper.py:17 in <module>                                │
│                                                                                                                     │
│    16                                                                                                               │
│ >  17 np.warnings.filterwarnings('ignore')                                                                          │
│    18                                                                                                               │
│                                                                                                                     │
│ H:\Vladmatic\automatic\venv\lib\site-packages\numpy\__init__.py:320 in __getattr__                                  │
│                                                                                                                     │
│   319 │   │                                                                                                         │
│ > 320 │   │   raise AttributeError("module {!r} has no attribute "                                                  │
│   321 │   │   │   │   │   │   │    "{!r}".format(__name__, attr))                                                   │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: module 'numpy' has no attribute 'warnings'
16:23:11-384496 ERROR    Module load: H:\Vladmatic\automatic\extensions\sd-webui-reactor\scripts\swapper.py:
                         AttributeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ H:\Vladmatic\automatic\modules\script_loading.py:10 in load_module                                                  │
│                                                                                                                     │
│    9 │   try:                                                                                                       │
│ > 10 │   │   module_spec.loader.exec_module(module)                                                                 │
│   11 │   except Exception as e:                                                                                     │
│ in exec_module:883                                                                                                  │
│                                                                                                                     │
│                                               ... 1 frames hidden ...                                               │
│                                                                                                                     │
│ H:\Vladmatic\automatic\extensions\sd-webui-reactor\scripts\swapper.py:17 in <module>                                │
│                                                                                                                     │
│    16                                                                                                               │
│ >  17 np.warnings.filterwarnings('ignore')                                                                          │
│    18                                                                                                               │
│                                                                                                                     │
│ H:\Vladmatic\automatic\venv\lib\site-packages\numpy\__init__.py:320 in __getattr__                                  │
│                                                                                                                     │
│   319 │   │                                                                                                         │
│ > 320 │   │   raise AttributeError("module {!r} has no attribute "                                                  │
│   321 │   │   │   │   │   │   │    "{!r}".format(__name__, attr))                                                   │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: module 'numpy' has no attribute 'warnings'
16:23:11 - ReActor - STATUS - Running v0.3.0

**Comment by Gourieff** [comment]
Fixed!

**Comment by Arctycus** [comment]
Much appreciated!
