### ISSUE TITLE
enhancement - translucent background

### ISSUE THREAD

**Issue by johndpope** [Gourieff/sd-webui-reactor#382]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

I'm using with https://github.com/layerdiffusion/sd-forge-layerdiffuse + sd forge.
when I use this plugin - it puts in a grid background instead of a transparent pixel. 

### Steps to reproduce the problem

install sd forge
https://github.com/lllyasviel/stable-diffusion-webui-forge

add extension
https://github.com/layerdiffusion/sd-forge-layerdiffuse

### Sysinfo

ubuntu

### Relevant console log

```Shell
a
```

### Additional information

.

**Comment by Dutch77** [comment]
+1

I'm doing currently very painful procedure because of this. Be able to faceswap on transparent png would be great feature.

**Comment by altoiddealer** [comment]
ReActor face swap actually works... technically... if you take the transparent output from [layerdiffuse](https://github.com/layerdiffusion/sd-forge-layerdiffuse) and send it to Extras tab, then use ReActor.

However, it totally borks the image and makes it fully opaque

![tmp07ugz0_g](https://github.com/Gourieff/sd-webui-reactor/assets/1613484/43a1eee8-45b2-4ae7-9a26-d39b10bfb08e)
![00001](https://github.com/Gourieff/sd-webui-reactor/assets/1613484/42042f30-8bbf-4611-8a1d-da52b5350db5)

**Comment by altoiddealer** [comment]
Sorry to double post, but it seems like this could be a solution... I'll be trying it personally tomorrow when time permits

[ChatGPT says this works supposedly](https://chat.openai.com/share/7ca84e4f-6e6b-4590-8b4e-be8a6a40517e)

**Comment by Gourieff** [comment]
There're several issues we have in SD WebUI with all these things
1. The main image that is generated by "sd-forge-layerdiffuse" - the checkerboarded image but not the one with alpha-channel (and it still doesn't save the image with alpha)
2. It seems that SD WebUI cuts Alpha channel when even we process the image via Extras tab (correct me if I'm wrong)
3. Insightface doesn't work with Alpha-channel as well :( It needs BGR as the input...

> Sorry to double post, but it seems like this could be a solution... I'll be trying it personally tomorrow when time permits
> [ChatGPT says this works supposedly](https://chat.openai.com/share/7ca84e4f-6e6b-4590-8b4e-be8a6a40517e)

But it's rather interesting solution if we could get alpha-png from the SD WebUI pipeline to postprocess it without the alpha-channel being cut
Or we even could simply blend it by the face mask

**Comment by Woisek** [comment]
Why using a transparent PNG _before_ the face swap?
Why not make a transparent PNG opaque, face swap and _then_ remove the bg or use the transparency of the original to re-cut out the face swapped copy ... ?
🤷‍♂️

**Comment by Dutch77** [comment]
@Gourieff `Or we even could simply blend it by the face mask` this would be great! If I understand it correctly, you would 

1. get the target pic,  on it and 
2. faceswap as is now
3. crop faces via faces masks
4. cropped faces apply to original target img to keep it transparent.

This would be awesome and solve a lot of pain I'm currently doing in my pipeline to be even able to swap face to cropped characters :D

Also really good feature would be if you can return new faces as mask. I bet that would also help a lot of people.

**Comment by johndpope** [comment]
a hack from chatgpt - 
I asked it to remove this grid

RGB
 if item[0] == item[1] == item[2]: // eg. 3333333

problem is gray is a little off.

![Screenshot from 2024-03-07 20-53-44](https://github.com/Gourieff/sd-webui-reactor/assets/289994/77440f30-9418-4534-9cb9-1e07e8111d6e)


```

from PIL import Image

# Open the image file with the grid background
with Image.open("path_to_your_image.png") as img:
    # Convert the image to RGBA if it's not already in that mode
    if img.mode != 'RGBA':
        img = img.convert('RGBA')
    
    # Get the data of the image
    datas = img.getdata()
    
    newData = []
    for item in datas:
        # Check if the pixel is part of the grid (assumed to be shades of gray)
        if item[0] == item[1] == item[2]:
            # Make the grid transparent
            newData.append((255, 255, 255, 0))
        else:
            newData.append(item)

    # Update image data with new data
    img.putdata(newData)
    
    # Save the modified image with a transparent grid
    img.save("path_to_your_new_image.png", "PNG")


```
![Screenshot from 2024-03-07 20-58-29](https://github.com/Gourieff/sd-webui-reactor/assets/289994/0aeedf55-df8f-4092-ab2b-5e64dc8a4620)

**Comment by Woisek** [comment]
> @Woisek One of the reason is because after you bring back bg, several other people are gonna be present and face indexes would be different. It cannot be automated without human intervention.

Huh? What 'several other people are gonna be present' when you make the transparent image opaque with any color ... ??

**Comment by Dutch77** [comment]
> 
> Huh? What 'several other people are gonna be present' when you make the transparent image opaque with any color ... ??

Sry. Should have better describe it. My use case currently is stable-diffusion, inpaint person with backround removal. I have it automated but problem here is when the new background has multiple other characters and I don't know which id is the face I want to swap. I have the mask of person but when I feed masked image to reactor, it removes alpha channel. Because of this I have to use another layer that detect head a feeds only the head to reactor and that head is positioned back to composition.

tldr: if reactor wouldn't strip alpha channels life would be easier. I can imagine case where you have some people assets without background and you want them face swapped. Now it's impossible.

**Comment by altoiddealer** [comment]
So what I said earlier that ChatGPT suggested, is working for [my discord bot](https://github.com/altoiddealer/ad_discordbot).

I just had to play around with it a bit.

```
        layerdiffuse = img_payload['alwayson_scripts'].get('layerdiffuse', {})
        if len(images) > 1 and layerdiffuse and layerdiffuse['args'][0]:
             # Extract alpha channel from layerdiffuse output
            img1 = images[1]
            _, _, _, alpha = img1.split()
            
            # Open ReActor output, convert to RGBA, apply alpha
            img0 = Image.open(f'temp_img_0.png')
            img0 = img0.convert('RGBA')
            img0.putalpha(alpha)
            
            # Save the image, update discord image payload
            img0.save('temp_img_0.png')
            images[0] = img0
```

<img width="589" alt="Screenshot 2024-03-07 141656" src="https://github.com/Gourieff/sd-webui-reactor/assets/1613484/2ec0864a-0b79-42b2-a0cd-049b80224521">

Downsides:

- if the layerdiffusion output has a 'mild cloudiness' to the background transparency layer, the result of this method here will have a faint checker pattern in those semitranslucent areas.

- If the overall shape changes (head turned sideways), then the alpha won't align and it will look wonky

**Comment by Gourieff** [comment]
Ok guys
With the quick commit https://github.com/Gourieff/sd-webui-reactor/commit/99b0f19553537a2f396a730455c9ea3a23623509 ReActor can work with RGBA via the Extras Tab (Single Image) - but only if SD WebUI doesn't cut Alpha channel when run postprocessing
There's a quick fix to make SD WebUI allow RGBA for Extras: https://github.com/Gourieff/stable-diffusion-webui-forge/compare/main...Gourieff:stable-diffusion-webui-forge:extras--allow-png-rgba
Fill free to test

![image](https://github.com/Gourieff/sd-webui-reactor/assets/85128026/228912ef-4ee9-4004-9008-0c63936246d4)
![image](https://github.com/Gourieff/sd-webui-reactor/assets/85128026/b438abcb-9f6b-4af7-8a7e-310fb0f22dba)

**Comment by Dutch77** [comment]
@Gourieff Idk what im doing wrong but it still thinks it's RGB

```
ai-stable-diffusion-webui-1  | 10:22:13 - ReActor - DEBUG - We're here: process()
ai-stable-diffusion-webui-1  | 10:22:13 - ReActor - DEBUG - We're here: process()
ai-stable-diffusion-webui-1  | 10:22:13 - ReActor - STATUS - Working: source face index [0], target face index [0]
ai-stable-diffusion-webui-1  | 10:22:13 - ReActor - STATUS - image = <PIL.Image.Image image mode=RGB size=1080x1440 at 0x7F59341C2110>
ai-stable-diffusion-webui-1  | 10:22:13 - ReActor - STATUS - alpha = None

```

Using extra tab in webui. Tried even transparent png in target and source. Also could you do the fix also for API? Thx

**Comment by Gourieff** [comment]
> There's a quick fix to make SD WebUI allow RGBA for Extras: https://github.com/Gourieff/stable-diffusion-webui-forge/compare/main...Gourieff:stable-diffusion-webui-forge:extras--allow-png-rgba

@Dutch77 Hm... Did you apply this fix?
