### ISSUE TITLE
[SOLVED] 'do_restore_first'

### ISSUE THREAD

**Issue by Arctycus** [Gourieff/sd-webui-reactor#39]
17:42:13 - ReActor - STATUS - Working: source face index [0], target face index [0]
17:42:13-574981 ERROR    Running script postprocess image:
                         H:\Vladmatic\automatic\extensions\sd-webui-reactor\scripts\faceswap.py: TypeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ H:\Vladmatic\automatic\modules\scripts.py:422 in postprocess_image                                                  │
│                                                                                                                     │
│   421 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_f                      │
│ > 422 │   │   │   │   script.postprocess_image(p, pp, *args)                                                        │
│   423 │   │   │   except Exception as e:                                                                            │
│                                                                                                                     │
│ H:\Vladmatic\automatic\extensions\sd-webui-reactor\scripts\faceswap.py:235 in postprocess_image                     │
│                                                                                                                     │
│   234 │   │   │   │   │   model=self.model,                                                                         │
│ > 235 │   │   │   │   │   upscale_options=self.upscale_options,                                                     │
│   236 │   │   │   │   )                                                                                             │
│                                                                                                                     │
│ H:\Vladmatic\automatic\extensions\sd-webui-reactor\scripts\faceswap.py:151 in upscale_options                       │
│                                                                                                                     │
│   150 │   def upscale_options(self) -> UpscaleOptions:                                                              │
│ > 151 │   │   return UpscaleOptions(                                                                                │
│   152 │   │   │   do_restore_first = self.restore_first,                                                            │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
TypeError: UpscaleOptions.__init__() got an unexpected keyword argument 'do_restore_first'

**Comment by Gourieff** [comment]
Please read https://github.com/Gourieff/sd-webui-reactor#troubleshooting sec. III

**Comment by Arctycus** [comment]
I read it, disabling the other Roop versions did not work. Deleting them, however, seemed to have done the trick! Thanks again.

**Comment by Gourieff** [comment]
> I read it, disabling the other Roop versions did not work. Deleting them, however, seemed to have done the trick! Thanks again.

Hm... I will mark this moment in the README
Thanks to you to for pointing this out
