### ISSUE TITLE
path not found

### ISSUE THREAD

**Issue by schofield66** [Gourieff/sd-webui-reactor#391]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

In VIII, step 3, I run the cmd, copy the code ".\venv\Scripts\activate" and press the enter button, it show me "path not found"

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...1

### Sysinfo

1

### Relevant console log

```Shell
1
```

**Comment by Gourieff** [comment]
You should run CMD from the directory containing the "venv" folder
If you use portable A1111 - just follow "(A1111 Portable)" steps
