### ISSUE TITLE
[SOLVED] Multiple Target Faces all swapped with the same Souce Face | img2img | Forge UI

### ISSUE THREAD

**Issue by Alexiazul** [Gourieff/sd-webui-reactor#416]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

After the last update I've noticed a change in behavior. Before, reactor only changed the face/faces specified in the target field. Now it's changing every face in the target image no matter what I designate. Say I have a source image with one face (0), and a target with two faces, one left (0) and one right (1). I have always been able to choose which target face to replace. For instance <source = 0 target = 1> would replace the target face on the right with the source face but leave the target face on the left alone. Now with this setting, it replaces the face on the right as specified, but it also changes the face on the left with same Source Face. The same happens with 3 or more faces in the Target image.

### Steps to reproduce the problem

See above

### Sysinfo

Windows 10 | Firefox 123.0 64bit | GEFORCE 4060Ti | Forge UI
![Screenshot 2024-04-05 at 21-28-31 Stable Diffusion](https://github.com/Gourieff/sd-webui-reactor/assets/166196454/5065587d-e2b3-4f57-8054-0338c309f84e)

[sysinfo-2024-04-06-04-25.json](https://github.com/Gourieff/sd-webui-reactor/files/14892292/sysinfo-2024-04-06-04-25.json)

### Relevant console log

```Shell
Uncertain how to do this?
```

**Comment by Gourieff** [comment]
I've just tested it and everything works fine
Cannot confirm the bug you described

**Comment by Alexiazul** [comment]
It appears the issue is related to Ultimate SD upscale 4X Ultra Sharp extension. The issue disappears when the extension is turned off while using Reactor. On occasion refreshing browser is necessary.
