### ISSUE TITLE
Pyro's NSFW SDXL | "batch count" issue

### ISSUE THREAD

**Issue by Spheren** [Gourieff/sd-webui-reactor#426]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

"batch count" with reactor not possible. Doesn't matter if I choose 1 or 10 I get every time only one picture.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### Sysinfo

Windows 11. Fresh installation of A1111.

### Relevant console log

```Shell
no error
```

**Comment by Gourieff** [comment]
This is strange
Please provide your workflow
