### ISSUE TITLE
Add support for gender selection (male/female)

### ISSUE THREAD

**Issue by g0kuvonlange** [Gourieff/sd-webui-reactor#43]
Hey man, first of all I love the project. I've got this extension running on a Runpod endpoint (docker setup) and the API works accordingly :)

Now I've explored the roop repository a lot and have played with the Insightface library before. I know they have support built-in for their module to detect the gender within the image and swap that. I believe. when the swap function gets called, some extra parameters can be passed on like age and gender and it will do more of a targeted swap as opposed to swapping the first face (or all faces).

The foundation work is already done by Insightface but just needs some small changes in the code. Would be super cool if this could be implemented into this project and also for the API. Thanks for building this repo!

**Comment by Gourieff** [comment]
Hi there! Thanks for the idea! Will be implemented soon :)

**Comment by Gourieff** [comment]
Done!
