### ISSUE TITLE
 I don't know how to use it.

### ISSUE THREAD

**Issue by mayubin258** [Gourieff/sd-webui-reactor#440]
### Feature description

I recently wanted to make a face-swapping demo to encapsulate the API, but I found that this code https://github.com/Gourieff/sd-webui-reactor seems to not be able to be used alone after I pulled it down. Do I need to combine it with other webUIs to encapsulate the face-swapping API interface?

**Comment by mayubin258** [comment]
I found that there are no files under my modules.
Do I need to download and put it in myself?

**Comment by Gourieff** [comment]
Yes, this is the extension for SD WebUIs
You should use it via: A1111 SD WebUI / SD WebUI Forge / SD.Next / Cagliostro Colab UI / StabilityMatrix 
ComfyUI as well https://github.com/Gourieff/comfyui-reactor-node
