### ISSUE TITLE
CPU and GPU issue

### ISSUE THREAD

**Issue by Michael2Miller** [Gourieff/sd-webui-reactor#446]
### Feature description

While processing it's relying on the CPU squeezing ram instead of GPU v ram it's unbelievable, always restarting in the middle of processing 
![IMG_20240508_184147_649](https://github.com/Gourieff/sd-webui-reactor/assets/168263994/440ab652-acee-4b5d-9e89-2a7baaeb3bfd)

**Comment by Michael2Miller** [comment]
This crazy maximum usage of CPU and ram always happens when rendering after choosing the face enhancement and without the face enhancement models results would be not good as it should be

So adding an option to choose Cuda or CPU would be great then the user can choose whatever is suitable for him

**Comment by Gourieff** [comment]
Related to https://github.com/Gourieff/sd-webui-reactor/issues/447
