### ISSUE TITLE
[Feature]: an option to choose Cuda or cpu for rendering 

### ISSUE THREAD

**Issue by Michael2Miller** [Gourieff/sd-webui-reactor#447]
### Feature description

An #option to choose whether Cuda or cpu for rendering would be a great addition and would solve the problem of slowliness while rendering and the other problem because most of the time the rendering in reactor is relying on CPU and RAM instead of GPU and vRam

**Comment by Gourieff** [comment]
If you have NVIDIA GPU you can choose between CUDA EP (by default) and CPU EP
![image](https://github.com/Gourieff/sd-webui-reactor/assets/85128026/e67572ad-f790-404d-bdd3-3de39ce8a4f9)
But if you have AMD GPU or Intel GPU ReActor works with CPU EP only

**Comment by Michael2Miller** [comment]
Maybe because I'm using it on comfy ui that's why I cannot see settings option

**Comment by Gourieff** [comment]
You should've opened the Issue in the ComfyUI's ReActor repo :)

So, to make ReActor work with CUDA on Comfy you just need to uninstall onnxruntime package you have and: 
- install onnxruntime-gpu (an appropriate version if you use CUDA 12.x) 
or 
- run install.bat inside the ReActor's folder and let ReActor to install it by itself
