### ISSUE TITLE
PLEASE RESTART THE SERVER!   - after recent ControlNet update

### ISSUE THREAD

**Issue by Aintru** [Gourieff/sd-webui-reactor#45]
ControlNet just received an update that seems to be conflicting with this extension, if only in a minor way.  

--------

Already up to date.
venv "D:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Version: v1.5.1
Commit hash: 68f336bd994bed5442ad95bad6b6ad5564a5409a

Installing sd-webui-controlnet requirement: changing opencv-python version from 4.7.0.72 to 4.8.0

Collecting opencv-python==4.7.0.72
  Using cached opencv_python-4.7.0.72-cp37-abi3-win_amd64.whl (38.2 MB)
Requirement already satisfied: numpy>=1.21.2 in d:\stable-diffusion-webui\venv\lib\site-packages (from opencv-python==4.7.0.72) (1.23.5)
Installing collected packages: opencv-python
  Attempting uninstall: opencv-python
    Found existing installation: opencv-python 4.8.0.76
    Uninstalling opencv-python-4.8.0.76:
      Successfully uninstalled opencv-python-4.8.0.76
Successfully installed opencv-python-4.7.0.72
Checking ReActor (ex Roop-GE) requirements...
--- PLEASE, RESTART the Server! ---

Launching Web UI with arguments: --xformers --enable-insecure-extension-access --listen
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: D:\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
[-] ADetailer initialized. version: 23.7.11, num models: 9
2023-08-10 22:08:03,246 - ControlNet - INFO - ControlNet v1.1.237
ControlNet preprocessor location: D:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-08-10 22:08:03,500 - ControlNet - INFO - ControlNet v1.1.237
22:08:03 - ReActor - STATUS - Running v0.3.0
Loading weights [c948d0c54f] from D:\stable-diffusion-webui\models\Stable-diffusion\consistentFactorEuclid_euclidV61.safetensors
Creating model from config: D:\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 43.8s (launcher: 18.9s, import torch: 9.2s, import gradio: 1.0s, setup paths: 0.9s, other imports: 1.4s, setup codeformer: 0.1s, list SD models: 0.9s, load scripts: 8.9s, scripts before_ui_callback: 1.0s, create ui: 1.1s, gradio launch: 0.3s).
Applying attention optimization: xformers... done.
Model loaded in 6.5s (load weights from disk: 1.0s, create model: 1.8s, apply weights to model: 1.8s, apply half(): 0.7s, move model to device: 0.9s).

-------

The RESTART message appears every time now.

**Comment by Gourieff** [comment]
Got it, will take a look

**Comment by Gourieff** [comment]
Fixed!
