### ISSUE TITLE
A1111 - ReActor refuses other face models

### ISSUE THREAD

**Issue by NRubric81** [Gourieff/sd-webui-reactor#454]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Hey I hope some one can help me.

ReActor didn't use the face model which I selected.
It refuses to use any other Face Model beside one certain one.
When I remove that model, ReActor ignores any of the others.

I updated ReActor to the newest version and I also deinstalled and reinstalled it fresh.
I tried it in Chrome and also Firefox.
No difference.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### Sysinfo

Win10 Pro, Firefox/Chrome, RTX 4070, A1111

### Relevant console log

```Shell
Here the error which I get, when I remove the mentioned face model.

*** Error running postprocess_image: D:\Programs AI\A1111\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py
    Traceback (most recent call last):
      File "D:\Programs AI\A1111\stable-diffusion-webui\modules\scripts.py", line 897, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "D:\Programs AI\A1111\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 450, in postprocess_image
        result, output, swapped = swap_face(
      File "D:\Programs AI\A1111\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 555, in swap_face
        source_face_model = [load_face_model(face_model)]
      File "D:\Programs AI\A1111\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_helpers.py", line 193, in load_face_model
        with safe_open(model_path, framework="pt") as f:
    FileNotFoundError: No such file or directory: "D:\\Programs AI\\A1111\\stable-diffusion-webui\\models\\reactor\\faces\\Girl1.safetensors"
```

**Comment by CrunchyBanana1** [comment]
Did you try different models via XYZ Plot beforehand? And the last model in your plot was the one Reactor now fails to load?

Try using XYZ Plot with different reactor models again and see if it works. This could be the same problem I have in #444

**Comment by NRubric81** [comment]
Thanks
I don't know why but that seem to have been the problem.
