### ISSUE TITLE
onnxruntime error

### ISSUE THREAD

**Issue by tjsworld227** [Gourieff/sd-webui-reactor#458]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

I installed  Cuda12.1, onnxrumtime 1.18 according to instruction and set right variables but still gets this error;

[E:onnxruntime:Default, provider_bridge_ort.cc:1744 onnxruntime::TryGetProviderInfo_CUDA] C:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1426 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\username\Desktop\Newfolder\system\python\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

*************** EP Error ***************
EP Error C:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:866 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.
 when using ['CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
2024-05-26 15:34:27.0110574 [E:onnxruntime:Default, provider_bridge_ort.cc:1744 onnxruntime::TryGetProviderInfo_CUDA] C:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1426 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\username\Desktop\Newfolder\system\python\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

I know there is cpu option but i want my gpu. 
I searched almost all related issues but none is seem to know what to do. 

Any idea??

### Steps to reproduce the problem

1. load the SD.
2.  Run Reactor.

### Sysinfo

Intel, 4070ti, both SD WebUI(1111) and Forge

### Relevant console log

```Shell
above.
```

**Comment by laviatf** [comment]
same problem here any1 plz help ?

**Comment by IAFFeng** [comment]
When I open it for the first time, an error message will appear, but when I regenerate it for the second time, the error message will not appear. I am using webui forge

**Comment by realzaidiguy** [comment]
Confirming. Same problem here as well. 

@IAFFeng The reason you don't see it on the second generation is because when it fails to use the GPU the first time, for subsequent generation it switches to using your CPU instead. This is generally slower. GPU is preferred.

**Comment by Gourieff** [comment]
If you used CUDA 11.8 and manually updated to 12.1 you should uninstall any ORT version you have and install the right one according to the official instructions https://onnxruntime.ai/docs/install/#install-onnx-runtime-gpu-cuda-12x
Or you can just delete all onnxruntime folders inside the "site-packages" directory and let ReActor install the right version

**Comment by IAFFeng** [comment]
> Confirming. Same problem here as well.
> 
> @IAFFeng The reason you don't see it on the second generation is because when it fails to use the GPU the first time, for subsequent generation it switches to using your CPU instead. This is generally slower. GPU is preferred.

Well, that should be the case, but how to solve this problem?

**Comment by realzaidiguy** [comment]
@Gourieff Thank you for the feedback. The problem remains. I have tried the following:

1. Tried deleting all onnxruntime folders in site-packages. ReActor did not reinstall upon server restart, and relaunch.
2. Uninstalled onnxruntime using pip, and installed using the ORT version instructions at the link you provided, for CUDA 12.x
3. Uninstalled everything, then started fresh, by first installing python 3.10.6, then doing a git pull on Automatic111's version of stable-diffusion-webui. Then followed the instructions for installing sd-webui-reactor using the install-from-url option. 
4. After attempt 3 above, again tried steps 1 and 2.

In every case, upon trying to use ReActor, continue to receive the same error:
 [E:onnxruntime:Default, provider_bridge_ort.cc:1744 onnxruntime::TryGetProviderInfo_CUDA] C:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1426 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

Additional info: 
using Nvidia's driver v555.85, which uses cuda 12.1, cudnn 8801

Thank you for any help.

**Comment by realzaidiguy** [comment]
For reference, I was able to get it working by starting with a fresh install of SD with the following steps:

1. git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git
2. run webui-user.bat in a command window (don't just double click in explorer)
3  after initial launch and auto setup is completed, shut down the server (control-c), and close the command window
4. launch a new command window, run webui-user.bat again
5. install extension with "Install from URL" tab under "Extensions" tab from "https://github.com/Gourieff/sd-webui-reactor" then verify it is installed in "Installed" tab
6. shut down the server again, and relaunch webui-user.bat 3 times. (It kept installing other things during the first 2 relaunches)
7. Shut down SD again
8. upgrade pip with the following command, but adjust the path: C:\YOUR_PATH\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip 
9. Then go into the venv/Scripts folder, and run: activate
10. pip uninstall onnxruntime-gpu
11. pip install onnxruntime-gpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
12. pip install --upgrade wheel
13. pip install nvidia-cudnn-cu12==8.9.7.29
14. deactivate
15. run webui-user.bat

There may be other ways, but after a lot of trial and error this method worked for me. I went through it a couple of times to confirm. Good luck!

**Comment by GlamoramaAttack** [comment]
@realzaidiguy 

I could us FaceReactor somehow (but not fully functional), probably because I didn't have the EP error @tjsworld227 cited. Nevertheless I thought it's better to get rid of error 126 failing to load "(...)stable-diffusion-webui\venv\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll" and then:

>     8. -15. 

YES, YES, YES!
     
> There may be other ways, but after a lot of trial and error this method worked for me.

I avoided steps 1.-7. you've used, started instead with 8. and followed the the rest, but I believe 10.-13. were the most relevant, because I didn't try those steps before. And Visual Studio Build Tools are still not on my PC - so that's a step you don't have to go, when you choose the option to install ReActor without it ('Installation' for Windows users [(sec. VIII)](https://github.com/Gourieff/sd-webui-reactor?tab=readme-ov-file#insightfacebuild). ReActor is now fully functional. Thanx a lot!

**Comment by realzaidiguy** [comment]
> I avoided steps 1.-7. you've used, started instead with 8. and followed the the rest, but I believe 10.-13. were the most relevant, because I didn't try those steps before. And Visual Studio Build Tools are still not on my PC - so that's a step you don't have to go, when you choose the option to install ReActor without it ('Installation' for Windows users [(sec. VIII)](https://github.com/Gourieff/sd-webui-reactor?tab=readme-ov-file#insightfacebuild). ReActor is now fully functional. Thanx a lot!

Thanks for confirming, and happy to hear it helped!
