### ISSUE TITLE
Interrupt

### ISSUE THREAD

**Issue by Webtransformer** [Gourieff/sd-webui-reactor#47]
The extension is working great but there is one problem.
If you interrupt the process ReActor still continues to run at the end.
It´s worse when you are using batch size. It will run each iteration event it was skipped

`
 ReActor - STATUS - Restoring the face with CodeFormer
 ReActor - STATUS - Working: source face index [0], target face index [0]`

**Comment by Gourieff** [comment]
Yeah, this is an issue to be solved

**Comment by Gourieff** [comment]
Fixed https://github.com/Gourieff/sd-webui-reactor/commit/1d55c51a741e1f389728d01e75d855015aaccd6a

**Comment by Webtransformer** [comment]
Thank you! <3
