### ISSUE TITLE
[Feature]: lllyasviel/stable-diffusion-webui-forge gradio upgrade breaks face model selection menu

### ISSUE THREAD

**Issue by GlenCarpenter** [Gourieff/sd-webui-reactor#491]
### Feature description

Forge is now using the latest version of Gradio, which has deprecated the `update` method.

Would be great to restore this functionality.

This is a request to make  sd-webui-reactor future-compatible with latest versions of Gradio,

**Comment by GlenCarpenter** [comment]
Context: 

https://github.com/Gourieff/sd-webui-reactor/blob/613b7d74ea64cc76094661492c4e6b6af59f07d5/reactor_ui/reactor_main_ui.py#L28

https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/e26abf87ecd1eefd9ab0a198eee56f9c643e4001

https://github.com/gradio-app/gradio/issues/6862#issuecomment-1866577714

**Comment by GlenCarpenter** [comment]
Current workaround for Forge is to use the `a9e0c387008734e97b8ad7fa091d170cb7bd4fc5` commit, however this is not compatible with the new SD3 features

**Comment by drdancm** [comment]
I think I am reporting the very same problem:

After installation of new Forge
version: [f1.0.2v1.10.1-previous-40-g9cb69baf](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/9cb69baf9fcd0ac2847790555fc8ab603794f1b2)

Choosing Face Model fails to show Face models that are in the usual folder that used to work fine.

**Comment by InfiniteLoop-cmd** [comment]
Same problem after updating

**Comment by javascriptdotexe** [comment]
Same problem here.

**Comment by drdancm** [comment]
I have not tried to add those same two line into the requirements.txt, but even if that works, I do not look forward to having to do it every time there is an update, and they come every couple of days.

**Comment by Darknessssenkrad** [comment]
> I have not tried to add those same two line into the requirements.txt, but even if that works, I do not look forward to having to do it every time there is an update, and they come every couple of days.

is it just adding those lines that fix it?  I can't seem to be able to select the radio button for the models option =(

**Comment by drdancm** [comment]
I tried the same fix, and it failed to work. I'm afraid I don't know which radio button you mean.

**Comment by Darknessssenkrad** [comment]
still not working not even with the fix provided in the requirements.txt
