### ISSUE TITLE
EP Error, can't load onnxruntime_providers_cuda.dll

### ISSUE THREAD

**Issue by stanleyshek** [Gourieff/sd-webui-reactor#494]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

I've just updated stable-diffusion-webui and it updated CUDA to lastest version and Reactor have error then.  I've tried get into venv uninstall onnxruntime-gpu and pip install onnxruntime-gpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/.  It doesn't help.  

I've also tried deleting all onnxruntime folders in site-packages and let ReActor reinstall the requirements, it also doesn't work.  

How this can be fixed?
![Screenshot 2024-07-31 194232](https://github.com/user-attachments/assets/1b6d9de0-4922-49c6-bae5-4f576c7f8901)

### Steps to reproduce the problem

1. Go to reactor and put photo
2. Press Generate
3. ...

### Sysinfo

{
    "Platform": "Windows-10-10.0.22621-SP0",
    "Python": "3.10.11",
    "Version": "v1.10.1",
    "Commit": "82a973c04367123ae98bd9abdf80d9eda9b910e2",
    "Git status": "On branch master\nYour branch is up to date with 'origin/master'.\n\nChanges not staged for commit:\n  (use \"git add <file>...\" to update what will be committed)\n  (use \"git restore <file>...\" to discard changes in working directory)\n\tmodified:   webui-user.bat\n\nUntracked files:\n  (use \"git add <file>...\" to include in what will be committed)\n\t4.8.0\n\tstablediffusion-env/\n\twebui-user - reinstall xformers.bat\n\t\"webui-user - \\345\\211\\257\\346\\234\\254 (2).bat\"\n\t\"webui-user - \\345\\211\\257\\346\\234\\254.bat\"\n\t\"webui-user - \\345\\277\\253\\346\\215\\267\\346\\226\\271\\345\\274\\217.lnk\"\n\twebui-user SDXL.bat\n\nno changes added to commit (use \"git add\" and/or \"git commit -a\")",
    "Script path": "D:\\SDAI\\stable-diffusion-webui",
    "Data path": "D:\\SDAI\\stable-diffusion-webui",
    "Extensions dir": "D:\\SDAI\\stable-diffusion-webui\\extensions",
    "Checksum": "e15a84e6b9e4a486fe6cddb071555f7417ca809c78a9194e2aa528917253027a",
    "Commandline": [
        "launch.py",
        "--xformers",
        "--autolaunch"
    ],
    "Torch env info": {
        "torch_version": "2.1.2+cu121",
        "is_debug_build": "False",
        "cuda_compiled_version": "12.1",
        "gcc_version": null,
        "clang_version": null,
        "cmake_version": null,
        "os": "Microsoft Windows 11 家庭中文版",
        "libc_version": "N/A",
        "python_version": "3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)",
        "python_platform": "Windows-10-10.0.22621-SP0",
        "is_cuda_available": "True",
        "cuda_runtime_version": "12.4.99\r",
        "cuda_module_loading": "LAZY",
        "nvidia_driver_version": "551.61",
        "nvidia_gpu_models": "GPU 0: NVIDIA GeForce RTX 4080 Laptop GPU",
        "cudnn_version": null,
        "pip_version": "pip3",
        "pip_packages": [
            "numpy==1.26.2",
            "open-clip-torch==2.20.0",
            "pytorch-lightning==1.9.4",
            "torch==2.1.2+cu121",
            "torchdiffeq==0.2.3",
            "torchmetrics==1.3.1",
            "torchsde==0.2.6",
            "torchvision==0.16.2+cu121"
        ],

### Relevant console log

```Shell
2024-07-31 20:08:08.4411651 [E:onnxruntime:Default, provider_bridge_ort.cc:1745 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1426 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\SDAI\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

*************** EP Error ***************
EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:891 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.
 when using ['CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
```

**Comment by In-My-Way** [comment]
#487 <-- im having the same issue, no solution yet

**Comment by eschool95** [comment]
having same issue after updating

**Comment by eschool95** [comment]
> having same issue after updating

No clue if this well help anyone, but while I was installing FaceFusion for an alternative, I ended up getting my Reactor to work again.

Here's a link to Facefusion installation guide - https://docs.facefusion.io/installation   

I followed all the steps for installation under Windows. I ended up uninstalling it because I preferred how Reactor was built in. I went ahead and reinstalled Reactor within SDForge and now it works again. I'm thinking step "3. Install Your Accelerator" is what got it to work again, but I don't know enough to verify that. Just confirming that these steps helped get it working with my updated SD.

**Comment by Shamister** [comment]
Try this

Go to extensions/sd-webui-reactor folder

In requirements.txt
add these lines
onnxruntime==1.18.1
onnxruntime-gpu==1.18.1

In install.py uncomment these lines
![image](https://github.com/user-attachments/assets/56ab9d99-8ceb-4605-9035-2c1e362971a5)

Now go to main folder and run webui-user.bat and it should reinstall the versions from the requirements.txt

**Comment by In-My-Way** [comment]
> Try this
> 
> Go to extensions/sd-webui-reactor folder
> 
> In requirements.txt add these lines onnxruntime==1.18.1 onnxruntime-gpu==1.18.1
> 
> In install.py uncomment these lines ![image](https://private-user-images.githubusercontent.com/2875842/354218443-56ab9d99-8ceb-4605-9035-2c1e362971a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1OTUyMzQsIm5iZiI6MTcyMjU5NDkzNCwicGF0aCI6Ii8yODc1ODQyLzM1NDIxODQ0My01NmFiOWQ5OS04Y2ViLTQ2MDUtOTAzNS0yYzFlMzYyOTcxYTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDJUMTAzNTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGNjY2UzNmU3ZTdhNmRiMjM4NTdkY2IwYmM2NmQ1ZTgxNjA2MDM1ODkwYTllY2M3NGNlZDk1MjgwMDRjMzQxYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jPhHOerd5cgNmkefuw_0EHxjdmpNs8hL1CUz7rQYLKE)
> 
> Now go to main folder and run webui-user.bat and it should reinstall the versions from the requirements.txt

this is in fact the right solution lads, cheers

bonus note, for me the install.py had those lines already uncommented so if yours is the same, just ignore that step and it will work just fine.

**Comment by Darknessssenkrad** [comment]
> > Try this
> > Go to extensions/sd-webui-reactor folder
> > In requirements.txt add these lines onnxruntime==1.18.1 onnxruntime-gpu==1.18.1
> > In install.py uncomment these lines ![image](https://private-user-images.githubusercontent.com/2875842/354218443-56ab9d99-8ceb-4605-9035-2c1e362971a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1OTUyMzQsIm5iZiI6MTcyMjU5NDkzNCwicGF0aCI6Ii8yODc1ODQyLzM1NDIxODQ0My01NmFiOWQ5OS04Y2ViLTQ2MDUtOTAzNS0yYzFlMzYyOTcxYTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDJUMTAzNTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGNjY2UzNmU3ZTdhNmRiMjM4NTdkY2IwYmM2NmQ1ZTgxNjA2MDM1ODkwYTllY2M3NGNlZDk1MjgwMDRjMzQxYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jPhHOerd5cgNmkefuw_0EHxjdmpNs8hL1CUz7rQYLKE)
> > Now go to main folder and run webui-user.bat and it should reinstall the versions from the requirements.txt
> 
> this is in fact the right solution lads, cheers
> 
> bonus note, for me the install.py had those lines already uncommented so if yours is the same, just ignore that step and it will work just fine.

I tried this solution and won't work in colab, almosy everthing seems to work fine just I cant select the radio option for models, which is the option I always use

**Comment by thenotrealuser** [comment]
> Experimente isto
> 
> Vá para a pasta extensions/sd-webui-reactor
> 
> Em requirements.txt adicione estas linhas onnxruntime==1.18.1 onnxruntime-gpu==1.18.1
> 
> Em install.py descomente estas linhas ![imagem](https://private-user-images.githubusercontent.com/2875842/354218443-56ab9d99-8ceb-4605-9035-2c1e362971a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NzQ0ODQsIm5iZiI6MTcyMzY3NDE4NCwicGF0aCI6Ii8yODc1ODQyLzM1NDIxODQ0My01NmFiOWQ5OS04Y2ViLTQ2MDUtOTAzNS0yYzFlMzYyOTcxYTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTRUMjIyMzA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTEwMDVmMGU4N2M0NjYyNjNkMzU0NTYzMTc3NGZkNWVjNDlkM2E1MDY2MWM4OWUxNGYyZmVlOWI3ZWNhNmZkYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uERBwSVITTrm3TjXxQo_ffVsUzKSG-weEQu5j3uEGZc)
> 
> Agora vá para a pasta principal e execute webui-user.bat e ele deve reinstalar as versões do requirements.txt

Awesome!

**Comment by Adzido** [comment]
> Try this
> 
> Go to extensions/sd-webui-reactor folder
> 
> In requirements.txt add these lines onnxruntime==1.18.1 onnxruntime-gpu==1.18.1
> 
> In install.py uncomment these lines ![image](https://private-user-images.githubusercontent.com/2875842/354218443-56ab9d99-8ceb-4605-9035-2c1e362971a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NDQ2MjgsIm5iZiI6MTcyNDk0NDMyOCwicGF0aCI6Ii8yODc1ODQyLzM1NDIxODQ0My01NmFiOWQ5OS04Y2ViLTQ2MDUtOTAzNS0yYzFlMzYyOTcxYTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjlUMTUxMjA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWJmNjY5ZDZkYmZhM2NhNGNjYjIwNGU5OWQyYzNhNmYyNTMwOWJkZGU0YjMwZTFiOTVkNjFlZDAxN2MxMTEwOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Vr_evsi28gHr3h1X5abhgqBDNI7-EMbY4uPoJpK9eGU)
> 
> Now go to main folder and run webui-user.bat and it should reinstall the versions from the requirements.txt

Thats still working? I have same errors after that, did the same 2 times. I using forge ui.

**Comment by thenotrealuser** [comment]
> > Try this
> > Go to extensions/sd-webui-reactor folder
> > In requirements.txt add these lines onnxruntime==1.18.1 onnxruntime-gpu==1.18.1
> > In install.py uncomment these lines ![image](https://private-user-images.githubusercontent.com/2875842/354218443-56ab9d99-8ceb-4605-9035-2c1e362971a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NDQ2MjgsIm5iZiI6MTcyNDk0NDMyOCwicGF0aCI6Ii8yODc1ODQyLzM1NDIxODQ0My01NmFiOWQ5OS04Y2ViLTQ2MDUtOTAzNS0yYzFlMzYyOTcxYTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjlUMTUxMjA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWJmNjY5ZDZkYmZhM2NhNGNjYjIwNGU5OWQyYzNhNmYyNTMwOWJkZGU0YjMwZTFiOTVkNjFlZDAxN2MxMTEwOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Vr_evsi28gHr3h1X5abhgqBDNI7-EMbY4uPoJpK9eGU)
> > Now go to main folder and run webui-user.bat and it should reinstall the versions from the requirements.txt
> 
> Thats still working? I have same errors after that, did the same 2 times. I using forge ui.


Yes, working.

**Comment by Malfrador** [comment]
Not working for me with latest webui-forge. Seems to correctly uninstall and install 1.18.1, but then fails again.
```
Using cached onnxruntime_gpu-1.18.1-cp310-cp310-win_amd64.whl (157.7 MB)
Installing collected packages: onnxruntime-gpu
  Attempting uninstall: onnxruntime-gpu
    Found existing installation: onnxruntime-gpu 1.19.0
    Uninstalling onnxruntime-gpu-1.19.0:
      Successfully uninstalled onnxruntime-gpu-1.19.0
Successfully installed onnxruntime-gpu-1.18.1
```
Restarting the UI a second times reverts it back to 1.19.0. Manually deleting onnxruntime from /venv/ does not solve the issue either. Two of the built-in forge extensions also install onnxruntime, however removing them also did not help.

**Comment by Arnaud3013** [comment]
i had to change in install.py to
            ```
if not is_installed(ort,"1.18.1",True):
                install_count += 1
                ort = "onnxruntime-gpu==1.18.1"
```
