### ISSUE TITLE
Stable Diffusion WebUI Forge - Latest version 2 Aug 2024

### ISSUE THREAD

**Issue by drdancm** [Gourieff/sd-webui-reactor#496]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Reactor does not work. Saved faces in Faces folder never show up. Nor can you get FSwap from a single Face Source.  I posted about this in Forge, but so far no fix.

### Steps to reproduce the problem

Confirm by trying it out.

### Sysinfo

In SDiff WebUI Reactor works fine- same hardware, same Browser

### Relevant console log

```Shell
Not Relevant - it is Forge that has changed
```

**Comment by dongxiat** [comment]
> ### First, confirm
> * [x]  I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
> * [x]  I have searched the existing issues
> * [x]  I have updated the extension to the latest version
> 
> ### What happened?
> Reactor does not work. Saved faces in Faces folder never show up. Nor can you get FSwap from a single Face Source. I posted about this in Forge, but so far no fix.
> 
> ### Steps to reproduce the problem
> Confirm by trying it out.
> 
> ### Sysinfo
> In SDiff WebUI Reactor works fine- same hardware, same Browser
> 
> ### Relevant console log
> ```shell
> Not Relevant - it is Forge that has changed
> ```
> 
> ### Additional information
> _No response_
in Gradio 4.x the` .update()` method of components has been deprecated, now you can simply return the component itself

read this [SOLUTION](https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/889#issuecomment-2257289510)

Replace lines 27-49 of reactor_main_ui.py with:

```
            return {
               control_col_1: gr.Column(visible=False),
               control_col_2: gr.Column(visible=False),
               control_col_3: gr.Column(visible=True),
                # save_original: gr.Checkbox.update(value=False,visible=False),
                imgs_hash_clear: gr.Button(visible=True)
            }
        if evt.index == 0:
            return {
               control_col_1: gr.Column(visible=True),
               control_col_2: gr.Column(visible=False),
               control_col_3: gr.Column(visible=False),
                # save_original: gr.Checkbox.update(value=SAVE_ORIGINAL,visible=show_br),
                imgs_hash_clear: gr.Button(visible=False)
            }
        if evt.index == 1:
            return {
               control_col_1: gr.Column(visible=False),
               control_col_2: gr.Column(visible=True),
               control_col_3: gr.Column(visible=False),
                # save_original: gr.Checkbox.update(value=SAVE_ORIGINAL,visible=show_br),
                imgs_hash_clear: gr.Button(visible=False)
            }
```
and read this [494#](https://github.com/Gourieff/sd-webui-reactor/issues/494#issuecomment-2262897991) see how to add these line to `extensions/sd-webui-reactor/requirements.txt `

**Comment by CpuUnlimited** [comment]
Fixes single images, Face models & folders remain broken

**Comment by drdancm** [comment]
Shamister has solved this problem by simply writing two lines into the requirments.txt
Go read and try it here:

 EP Error, can't load onnxruntime_providers_cuda.dll #494 

It fixed all of my problems, so now Reactor works fine, Faces data loads up. Great Solution.

Thanks to Shamister.

**Comment by drdancm** [comment]
However, with each Forge update, things fail again.
