### ISSUE TITLE
FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by minmie** [Gourieff/sd-webui-reactor#503]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

when i inference with optimum.onnxruntime，an error occurred:

`FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory`
![652ee3ba21bc03c88c2fabd03ca5393](https://github.com/user-attachments/assets/117bccb9-0dc7-4cf1-b937-4c321c850b00)

my env is as follow:
cuda 12.1
cudnn8
onnxruntime-gpu 1.16

and I found this doc(https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html):
![image](https://github.com/user-attachments/assets/92179d7f-2261-496b-9159-871705271007)

so I tried to update onnxruntime-gpu to 1.18.0, but the same error still occurred.

But when I updated the version of onnxruntime-gpu to 1.18.1, another error occurred， as follows：
`FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcudnn.so.9: cannot open shared object file: No such file or directory`
![cb85e4b2f35f9e91bd6dbb55e7eabb4](https://github.com/user-attachments/assets/d7f8d5dd-c056-4f7c-8bd6-4ef8faf316e8)

so， with cuda12.1 and cudnn8, which version of onnxruntime-gpu should i install？

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### Sysinfo

cuda 12.1
cudnn8
onnxruntime 1.16

### Relevant console log

```Shell
FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory
```

**Comment by septerlt** [comment]
i have some problem (latest version A1111)
