### ISSUE TITLE
Curl API Request

### ISSUE THREAD

**Issue by StuJLans** [Gourieff/sd-webui-reactor#53]
Hey there, just wondering if there is a way to use this with a Curl request? I try it in Postman and I can see it starts the process on the machine I have running locally but I get an Error write epipe as the response. Is there any way to get the image to be returned in base64 like the normal webui endpoints for image generating via curl method?

**Comment by Gourieff** [comment]
Done! 

```
curl -X POST \
	'http://127.0.0.1:7860/reactor/image' \
    -H 'accept: application/json' \
    -H 'Content-Type: application/json' \
    -d '{
    "source_image": "data:image/png;base64,/9j/4QAYRXhpZgAASUkqAAgAAAAAAAAAAAAAAP/sABFEdWNreQABAAQAAABQAAD/7g...",
    "target_image": "data:image/png;base64,/9j/4QAYRXhpZgAASUkqAAgAAAAAAAAAAAAAAP/sABFEdWNreQABAAQAAABCAAD/7g...",
    "source_faces_index": [0],
    "face_index": [2],
    "upscaler": "4x_Struzan_300000",
    "scale": 2,
    "upscale_visibility": 1,
    "face_restorer": "CodeFormer",
    "restorer_visibility": 1,
    "restore_first": 1,
    "model": "inswapper_128.onnx",
    "gender_source": 0,
    "gender_target": 0,
    "save_to_file": 1,
    "result_file_path": ""
	}'
```

set "save_to_file" to 0 if you don't need to save result to a file
"result_file_path" is set to the "outputs/api" folder by default with a timestamped filename, you can set any specific path, e.g. "C:/stable-diffusion-webui/outputs/api/output.png"

Full examples are in "example" folder

List of models can be seen by GET:
http://127.0.0.1:7860/reactor/models
http://127.0.0.1:7860/reactor/upscalers

**Comment by StuJLans** [comment]
Awesome. Works great!
