### ISSUE TITLE
Error running install.py for extension /content/sdw/extensions/sd-webui-reactor.

### ISSUE THREAD

**Issue by Sheringkapoting** [Gourieff/sd-webui-reactor#58]
sd-webui-reactor doesn't work in Google Colab. It worked well for the first time, but once got terminated it doesn't work and gives the following error message **"Error running install.py for extension /content/sdw/extensions/sd-webui-reactor."** at all and trying to reinstall again Error **"Extension Directory already exists"**

Full Error Message:

*** Error running install.py for extension /content/sdw/extensions/sd-webui-reactor. 
*** Command: "/usr/bin/python3" "/content/sdw/extensions/sd-webui-reactor/install.py" 
*** Error code: 1
*** stderr: Traceback (most recent call last):
***		File "/content/sdw/extensions/sd-webui-reactor/install.py", line 47, in <module> download (model_url, model_path)
***		File "/content/sdw/extensions/sd-webui-reactor/install.py", line 38, in download request = urllib.request.urlopen(url)
***		File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopenreturn opener.open(url, data, timeout)
***		File "/usr/lib/python3.10/urllib/request.py", line 525, in open response = meth(req, response)
***		File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response response = self.parent.error(
***		File "/usr/lib/python3.10/urllib/request.py", line 563, in error return self._call_chain (*args)
***		File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain result = func(*args)
***		File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default raise HTTPError(req.full_url, code, msg, hdrs, fp)	
*** urllib.error.HTTPError: HTTP Error 401: Unauthorized

Please suggest

**Comment by h3rmit-git** [comment]
I get the exact same error (HTTP Error 401: Unauthorized) when trying to install locally on my machine, on Stable-Diffusion-Webui. However, the extension seems to be installed regardless of the error.

**Comment by Gourieff** [comment]
Fixed!
The reason of this error is https://github.com/Gourieff/sd-webui-reactor/issues/60
The "inswapper_128.onnx" model is not accessible anymore via the old link

**Comment by guitro** [comment]
I have the same error. Just can't make it work. 

*** Error running install.py for extension I:\STABLE_DIFUSION\Automatic1111_NEW\stable-diffusion-webui\extensions\sd-webui-roop.
*** Command: "I:\STABLE_DIFUSION\Automatic1111_NEW\stable-diffusion-webui\venv\Scripts\python.exe" "I:\STABLE_DIFUSION\Automatic1111_NEW\stable-diffusion-webui\extensions\sd-webui-roop\install.py"
*** Error code: 1
*** stderr: Traceback (most recent call last):
***   File "I:\STABLE_DIFUSION\Automatic1111_NEW\stable-diffusion-webui\extensions\sd-webui-roop\install.py", line 25, in <module>
***     download(model_url, model_path)
***   File "I:\STABLE_DIFUSION\Automatic1111_NEW\stable-diffusion-webui\extensions\sd-webui-roop\install.py", line 16, in download
***     request = urllib.request.urlopen(url)
***   File "C:\Users\guilh\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
***     return opener.open(url, data, timeout)
***   File "C:\Users\guilh\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
***     response = meth(req, response)
***   File "C:\Users\guilh\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
***     response = self.parent.error(
***   File "C:\Users\guilh\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 563, in error
***     return self._call_chain(*args)
***   File "C:\Users\guilh\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
***     result = func(*args)
***   File "C:\Users\guilh\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 643, in http_error_default
***     raise HTTPError(req.full_url, code, msg, hdrs, fp)
*** urllib.error.HTTPError: HTTP Error 401: Unauthorized
