### ISSUE TITLE
ImportError: DLL load failed while importing onnxruntime_pybind11_state: The specified procedure could not be found.

### ISSUE THREAD

**Issue by h3rmit-git** [Gourieff/sd-webui-reactor#59]
I am getting the following error in Stable-Diffusion-Webui after installing this extension:

`ImportError: DLL load failed while importing onnxruntime_pybind11_state: The specified procedure could not be found.`

This seems to be caused by the version requirement `onnxruntime==1.15.0` in requirements.txt, and is probably related to this issue:
https://github.com/microsoft/onnxruntime/issues/16116

Manually changing requirements.txt to ``onnxruntime==1.14.0`` and restarting Stable-Diffusion-Webui seems to solve the issue.

**Comment by Gourieff** [comment]
I think you can try to install onnxruntime==1.15.1 according to this thread https://github.com/microsoft/onnxruntime/issues/15375
I will try to test 1.15.1 tomorrow too

**Comment by h3rmit-git** [comment]
I tried 1.15.1 as well and got the same error.

**Comment by DiegoRRR** [comment]
> I tried 1.15.1 as well and got the same error.
> 
> Edit: Actually, I had another look at the stacktrace and noticed that the error is traced back to [rembg](https://github.com/danielgatis/rembg), another very popular and convenient plugin I've installed
Did you find a solution ?

**Comment by azamet90** [comment]
so, any solution?
