### ISSUE TITLE
Current link to inswapper_128.onnx is inacessable

### ISSUE THREAD

**Issue by freecoderai01** [Gourieff/sd-webui-reactor#60]
The model from https://github.com/Gourieff/sd-webui-reactor/blob/1d55c51a741e1f389728d01e75d855015aaccd6a/install.py#L12C65-L12C83 link became private/deleted which is needed for proper usage of the extension, therefore, I belive, of high priority.
I found only following link as replacement, but not sure if that's legimate source
https://huggingface.co/deepinsight/inswapper/resolve/main/inswapper_128.onnx
(also there is pending copyright report https://huggingface.co/deepinsight/inswapper/discussions/2). 
I'm not sure if we should use this model or reupload to own HF.

**Comment by Gourieff** [comment]
Wow, thanks for noticing that... I'll fix it as soon as possible

**Comment by Gourieff** [comment]
This model https://huggingface.co/deepinsight/inswapper/resolve/main/inswapper_128.onnx is identical to the original model, so, I'll set the link to this variant as a temporary solution

**Comment by Gourieff** [comment]
Updated https://github.com/Gourieff/sd-webui-reactor/commit/94d15f517c6a42b3e9d57c76c2e6da842e66c5c3 to the legal link from https://github.com/facefusion/facefusion-assets/releases

**Comment by spammcahid** [comment]
After the recent change, "[asd](https://github.com/Gourieff/sd-webui-reactor#insightfacebuild)", one of the ways to install the extension, is no longer available.

**Comment by Gourieff** [comment]
> After the recent change, "[[(sec. VIII)](https://github.com/Gourieff/sd-webui-reactor#insightfacebuild)](https://github.com/Gourieff/sd-webui-reactor#insightfacebuild)", one of the ways to install the extension, is no longer available. Step 5: Then install Insightface: pip install insightface-0.7.3-cp310-cp310-win_amd64.whl

What is the issue about that? 
This step is useful for those who doesn't want to download VS or VS C++ BT, it's already prebuilt package, and if you do everything right - it will be installed with no problems, just do it from the root sd-webui folder and via the activated venv enclosure

**Comment by freecoderai01** [comment]
Since you switched to https://github.com/facefusion/facefusion-assets/, what about using fp16 version which is 2x smaller?  https://github.com/facefusion/facefusion-assets/releases/download/models/inswapper_128_fp16.onnx

**Comment by exeandino** [comment]
Bro the collaboration link does not work in the second step: https://colab.research.google.com/drive/1kgo3TxsJsEg8qWvZ6-anhIPaIRiiyvmI?usp=sharing&authuser=6#scrollTo=yYY03jVcWUyG
