### ISSUE TITLE
[feature] Run from extras tab?

### ISSUE THREAD

**Issue by DevilaN** [Gourieff/sd-webui-reactor#61]
I would be delighted to see possibility to use this extension in Extras tab.
Right now I am using img2img with denoising strength 0 to swap face in existing images (without need to regenerate entire image from scratch). But even using img2img seems a bit overkill as it moves image to latent space back and forth for 1 step only to generate image with changed face (it also takes more time and requires vRAM to create representation of image in Latent Space + encode / decode with VAE.

**Comment by Gourieff** [comment]
It's a piece of cake with ComfyUI
Just like here https://github.com/Gourieff/sd-webui-reactor/issues/62#issuecomment-1689839018 but with one source face
Frankly, I don't want to make this extension too heavy and hard to use, especially when something is already implemented in other related apps or extensions which can be complementary
