### ISSUE TITLE
[feature] Batch swap faces using multiple images

### ISSUE THREAD

**Issue by DevilaN** [Gourieff/sd-webui-reactor#62]
Right now you can only use one image.
I know that only one image is used for face swapping, but sometimes it is a matter of trying different images to find out which one works better.
I would like to see a possibility to use multiple images and then each of them is used for face swapping and output image with swapped face. 
So basically I generate one image, but use like 5 images in rector tab, and this results in 5 output images - each one is originally generated image with face swapped from each image provided.

**Comment by Gourieff** [comment]
But you already can do it with help of ComfyUI ([Portable](https://github.com/comfyanonymous/ComfyUI) or [SD WebUI extension](https://github.com/ModelSurge/sd-webui-comfyui)) + [ReActor Node](https://github.com/Gourieff/comfyui-reactor-node) + [FaceRestore Node](https://civitai.com/models/24690/comfyui-facerestore-node)
![ComfyUI + ReActor + facerestore](https://github.com/Gourieff/sd-webui-reactor/assets/85128026/c0a5250f-d449-4540-9d11-7a0c79b65319)

It's the most simple and fast way to do what you need

**Comment by Gourieff** [comment]
You're welcome! Try it! This is a really simple method with low resources costs
