### ISSUE TITLE
Wrong gender default value in API

### ISSUE THREAD

**Issue by andypotato** [Gourieff/sd-webui-reactor#64]
According to the API documentation (A1111 script-info), the default value for "Gender Detection (Source)" should be "No", means when no value is passed the parameter should default to "No".

However I'm seeing this in the log:

```
10:33:49 - ReActor - STATUS - Source Face 0: Detected Gender -M-
10:33:49 - ReActor - STATUS - WRONG - Detected Gender doesn't match Condition
```

As a result my face doesn't get replaced.

Seems like a bug?

**Comment by Gourieff** [comment]
Hm... I'll take a look

**Comment by Gourieff** [comment]
Fixed!
Thanks for spotting this bug!
