### ISSUE TITLE
[feature] Move the insightface models to stable-diffusion-webui\models

### ISSUE THREAD

**Issue by h3rmit-git** [Gourieff/sd-webui-reactor#66]
After reading this reply https://github.com/Gourieff/sd-webui-reactor/issues/65#issuecomment-1694169283 in an other issue, I realised that some models are in my user profile folder.

Is it possible to move these models from `%userprofile%\.insightface` to `stable-diffusion-webui\models`? 

Most other plugins put their models there, and it's more convenient.

**Comment by Gourieff** [comment]
Yes, they can be moved, but it's very light-weight models, and if you use different apps with Insightface package - it's more handy to have them in one place 
This is the reason why Insightface downloads them into the userprofile directory by default

But, ok, I will think about this moment in future commits

> Most other plugins put their models there, and it's more convenient.

If you look in your user profile folder you can find a great bunch of different AI models there, especially if you're an advanced user or AI-specialist and have a lot of ai-related applications

As for me, in my user profile directory I have such ai-related folders as:
.cache/huggingface
.cache/clip
.cahe/torch
.huggingface
.insightface
.jupyter
.keras
and many more

It's a common thing to have them there
Some models are used by different apps, and it's pretty right to have them in one place

**Comment by h3rmit-git** [comment]
Yes, but likewise, when there are multiple user profiles on the same machine, they all need to have copies of these models in their profile folder in order to use Stable-Diffusion-WebUI.

From what I've seen, the WebUI tries to be portable and self-contained, by maintaning an isolated venv and an internal folder hierarchy.

For reference, here are my model-related folders:

**User Profile**
890M    .cache/clip
1,6G    .cache/huggingface
1,4G    .cache/torch
601M    .insightface
1       .keras
168M    .u2net

**Stable-Diffusion-WebUI\models**
438M    3dphoto
855M    BLIP
360M    Codeformer
8,1G    ControlNet
618M    deepbooru
64M     ESRGAN
519M    GFPGAN
168M    hypernetworks
8,0K    karlo
0       LDSR
507M    leres
2,9G    Lora
516M    LyCORIS
0       midas
200M    openpose
304M    pix2pix
64M     RealESRGAN
529M    roop
69M     ScuNET
95G     Stable-diffusion
136M    SwinIR
615M    torch_deepdanbooru
1,9G    VAE
212K    VAE-approx

**Comment by Gourieff** [comment]
> Yes, but likewise, when there are multiple user profiles on the same machine, they all need to have copies of these models in their profile folder in order to use Stable-Diffusion-WebUI.
> 
> From what I've seen, the WebUI tries to be portable and self-contained, by maintaning an isolated venv and an internal folder hierarchy.

Hm... In general, you are right :)
Added to the "toDO" list

**Comment by h3rmit-git** [comment]
Thanks! I've taken the initiative to implement the change and opened a Pull Request for your convenience: https://github.com/Gourieff/sd-webui-reactor/pull/67

For reference, a [similar issue](https://github.com/AUTOMATIC1111/stable-diffusion-webui-rembg/issues/2) has been reported for the Rembg plugin since April (the one that the ~/.u2net folder belongs to), so I've opened a [PR](https://github.com/AUTOMATIC1111/stable-diffusion-webui-rembg/pull/28) there too.

**Comment by Gourieff** [comment]
Thanks so much for the idea and clarification!
This moment is implemented with commit https://github.com/Gourieff/sd-webui-reactor/commit/e4eecb942edef9ada67db28da259a0945389ed57
I mention you as the Contributor for [0.4.0 release version](https://github.com/Gourieff/sd-webui-reactor/releases/tag/v0.4.0)
I have to close your PR, because there's a slightly different logic in implementation
We don't need to set "root" parameter in the "getFaceSwapModel" function, because we set the inswapper model path in another way
