### ISSUE TITLE
Upscaler not running when multiple source faces selected but only one target face exists

### ISSUE THREAD

**Issue by NetCrafter99** [Gourieff/sd-webui-reactor#68]
Steps to recreate in Automatic1111:
Create any prompt that generates only one person
Add an image to ReActor with 2 faces
For source image enter 0,1
For target image enter 0,1
1. Restore Face -> 2. Upscale = CHECKED
Select Upscaler (Tried various, but R-ESRGAN 4x+ is an example)
Set "Scale By" To 2
Set console log level to default (does not impact results, but useful to see if upscaler is running)
Generate Image
The generated image will have a fuzzy face.  The log will not have an entry for the upscaler being run.

If you change the prompt to generate any image with 2 persons, and the number of source and target faces match, the upscaler will run (and will show in the log) and both faces will be clear.
If you keep the one person prompt in the generated image, and change the source image to 0 and the target image to 0, the upscaler will run and the face will be clear.

Have tested this same workflow with Roop-GE v0.2.2, and the upscaler does run if 2 source faces are selected and only one target face exists, and the face is clear.

**Comment by Gourieff** [comment]
Fixed https://github.com/Gourieff/sd-webui-reactor/commit/f5c09b53fd5681c464dfa9ed05e239717bf3d65d
Thanks for spotting!

**Comment by rdilsner** [comment]
Thank you for all your good work!

**Comment by NetCrafter99** [comment]
Thanks for the quick fix on this.
