### ISSUE TITLE
[SOLVED] reactor not showing in sd

### ISSUE THREAD

**Issue by something4411** [Gourieff/sd-webui-reactor#70]
did the install steps, reactor is no where to be found. says it is installed.
there is just no dropdown below controlnet dropdown. -.-

btw if u need any logs or anything plx also tell me how to get them

**Comment by something4411** [comment]
console doesnt show any errors, im using win10, i installed the dependencies mentioned in the post (the visual studio thing) and c++ should be installed too but i will cehck

**Comment by Gourieff** [comment]
Do you have STATUS message (in your Console) that ReActor is running?
Do you have "sd-webui-roop" (or maybe some other roop-based extension) installed and active?

**Comment by Gourieff** [comment]
I think you have no C++ Build Tools in your OS, Insightface cannot be built during the installation process without C++ BT
If you don't want to install C++ BT or VS 2022 - try these steps: Sec. VIII of [troubleshooting](https://github.com/Gourieff/sd-webui-reactor#troubleshooting)

**Comment by something4411** [comment]
brilliant, that worked, thanks so much, and sorry for the extra work!

**Comment by Gourieff** [comment]
Check please that you have no other roop-like extension enabled (e.g. sd-webui-roop) and try "Sec. V" of [troubleshooting](https://github.com/Gourieff/sd-webui-reactor#troubleshooting) after that, there's smth wrong with your "inswapper_128.onnx" file

**Comment by something4411** [comment]
thanks. it was the inswapper file, mine was only 23mb, the one linked is 500+ mb, works now!
thank you
