### ISSUE TITLE
error during install of reactor in sd

### ISSUE THREAD

**Issue by MrRyno123** [Gourieff/sd-webui-reactor#74]
*** Error running install.py for extension C:\Users\aksel\Downloads\stable-diffusion-webui-master\stable-diffusion-webui-master\extensions\sd-webui-reactor.
*** Command: "C:\Users\aksel\Downloads\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Scripts\python.exe" "C:\Users\aksel\Downloads\stable-diffusion-webui-master\stable-diffusion-webui-master\extensions\sd-webui-reactor\install.py"
*** Error code: 1
*** stderr: Traceback (most recent call last):
***   File "C:\Users\aksel\Downloads\stable-diffusion-webui-master\stable-diffusion-webui-master\extensions\sd-webui-reactor\install.py", line 24, in <module>
***     package: str, version: str | None = None, strict: bool = True
*** TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by Gourieff** [comment]
Union operator `|` was added in python 3.10
If you get this error - that means you have a not supported version of Python (<3.10)
You need Python 3.10.6 to make A1111 (and all the extensions inside) working properly
https://github.com/AUTOMATIC1111/stable-diffusion-webui/#automatic-installation-on-windows

**Comment by MrRyno123** [comment]
I currently have python 3.10, 3.11, and 3.8 installed. How can I make 3.10 the default installation?
