### ISSUE TITLE
inswapper_128.onnx location in SD.Next

### ISSUE THREAD

**Issue by solsol360** [Gourieff/sd-webui-reactor#78]
I have an issue with model location in SD.Next
 
I've done a clean install of SD.Next.
The instructions say to put the inswapper_128.onnx  to \models\insightface\

This is ok as the model can be found in the UI:

![image](https://github.com/Gourieff/sd-webui-reactor/assets/11191419/4d3d18ae-b029-4b6b-9e76-517560278666)

but the process is looking the model from \models\insightface\models\insightface\inswapper_128.onnx 

If I move the model from \models\insightface\ to \models\insightface\models\insightface then the I get error when starting the server that no models are found. 

Current workaround is to have the model in both directories.

D:\automatic\models\insightface\models\insightface
and 
D:\automatic\models\insightface\

Here are some logs if the model is not also in the D:\automatic\models\insightface\models\insightface directory
11:30:28-570656 INFO     Starting SD.Next
11:30:28-575590 INFO     Python 3.10.9 on Windows
11:30:28-621667 INFO     Version: 8bf0e71a Wed Aug 30 23:17:35 2023 +0300
11:30:45 - ReActor - STATUS - Running v0.4.1-b1

Progress 6.41it/s ---------------------------------------- 100% 0:00:00 0:00:03
11:33:04-290862 STATUS   Working: source face index [0], target face index [0]
11:33:06-805415 ERROR    Running script postprocess image: extensions\sd-webui-reactor\scripts\faceswap.py:
                         AssertionError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\automatic\modules\scripts.py:499 in postprocess_image                                                            │
│                                                                                                                     │
│   498 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_f                      │
│ > 499 │   │   │   │   script.postprocess_image(p, pp, *args)                                                        │
│   500 │   │   │   │   s.append(f'{script.title()}:{round(time.time()-t0, 2)}s')                                     │
│                                                                                                                     │
│ D:\automatic\extensions\sd-webui-reactor\scripts\faceswap.py:279 in postprocess_image                               │
│                                                                                                                     │
│   278 │   │   │   │   image: Image.Image = script_pp.image                                                          │
│ > 279 │   │   │   │   result = swap_face(                                                                           │
│   280 │   │   │   │   │   self.source,                                                                              │
│                                                                                                                     │
│ D:\automatic\extensions\sd-webui-reactor\scripts\swapper.py:261 in swap_face                                        │
│                                                                                                                     │
│   260 │   │   │   model_path = os.path.join(models_path, "insightface", model)                                      │
│ > 261 │   │   │   face_swapper = getFaceSwapModel(model_path)                                                       │
│   262                                                                                                               │
│                                                                                                                     │
│ D:\automatic\extensions\sd-webui-reactor\scripts\swapper.py:100 in getFaceSwapModel                                 │
│                                                                                                                     │
│    99 │   │   CURRENT_FS_MODEL_PATH = model_path                                                                    │
│ > 100 │   │   FS_MODEL = insightface.model_zoo.get_model(model_path, providers=providers)                           │
│   101                                                                                                               │
│                                                                                                                     │
│ D:\automatic\venv\lib\site-packages\insightface\model_zoo\model_zoo.py:91 in get_model                              │
│                                                                                                                     │
│   90 │   │   model_file = download_onnx('models', model_file, root=root, download_zip=downloa                       │
│ > 91 │   assert osp.exists(model_file), 'model_file %s should exist'%model_file                                     │
│   92 │   assert osp.isfile(model_file), 'model_file %s should be a file'%model_file                                 │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
**AssertionError: model_file models\insightface\models\insightface\inswapper_128.onnx should exist**

**Comment by Gourieff** [comment]
Got it, I will fix it soon

**Comment by Gourieff** [comment]
Fixed!

**Comment by solsol360** [comment]
Confirmed.Thanks!
