### ISSUE TITLE
Reactor install fails in Stability Multi Package Matrix (A1111, Invoke, Cumfy etc)

### ISSUE THREAD

**Issue by drdancm** [Gourieff/sd-webui-reactor#80]
I'm afraid I'm out of my element with this stuff. In any case there are a lot of errors and I'm not sure if it all stems from the very first error.
I'm pretty sure that I installed all of the required components of Visual Studio (Python, C++ Desktop, Visual Studio Extension Dev).
Looks like easydict was installed fine, but insightface module was not found.

Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: 1.6.0
Commit hash: <none>
Checking ReActor requirements... Error: The 'insightface==0.7.3' distribution was not found and is required by the application
Collecting insightface==0.7.3
  Downloading insightface-0.7.3.tar.gz (439 kB)
     -------------------------------------- 439.5/439.5 kB 9.1 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: numpy in d:\stablediff\data\packages\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (1.23.5)
Requirement already satisfied: onnx in d:\stablediff\data\packages\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (1.14.0)
Requirement already satisfied: tqdm in d:\stablediff\data\packages\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (4.66.1)
Requirement already satisfied: requests in d:\stablediff\data\packages\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (2.31.0)
Requirement already satisfied: matplotlib in d:\stablediff\data\packages\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (3.7.2)
Requirement already satisfied: Pillow in d:\stablediff\data\packages\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (9.5.0)
Requirement already satisfied: scipy in d:\stablediff\data\packages\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (1.11.2)
Collecting scikit-learn (from insightface==0.7.3)
  Obtaining dependency information for scikit-learn from https://files.pythonhosted.org/packages/96/cf/a714a655266229b51eb2bda117f15275f12457887f165f3c1cc58ab502f1/scikit_learn-1.3.0-cp310-cp310-win_amd64.whl.metadata
  Downloading scikit_learn-1.3.0-cp310-cp310-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: scikit-image in d:\stablediff\data\packages\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (0.21.0)
Collecting easydict (from insightface==0.7.3)
  Downloading easydict-1.10.tar.gz (6.4 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: cython in d:\stablediff\data\packages\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (3.0.2)
Collecting albumentations (from insightface==0.7.3)
  Obtaining dependency information for albumentations from https://files.pythonhosted.org/packages/9b/f6/c486cedb4f75147232f32ec4c97026714cfef7c7e247a1f0427bc5489f66/albumentations-1.3.1-py3-none-any.whl.metadata
  Downloading albumentations-1.3.1-py3-none-any.whl.metadata (34 kB)
Collecting prettytable (from insightface==0.7.3)
  Obtaining dependency information for prettytable from https://files.pythonhosted.org/packages/25/1e/4c284713b092ec384fad4399452f43f6446ad9aabc9c0b3c3c0920cc53b6/prettytable-3.8.0-py3-none-any.whl.metadata
  Downloading prettytable-3.8.0-py3-none-any.whl.metadata (26 kB)
Requirement already satisfied: PyYAML in d:\stablediff\data\packages\stable-diffusion-webui\venv\lib\site-packages (from albumentations->insightface==0.7.3) (6.0.1)
Collecting qudida>=0.0.4 (from albumentations->insightface==0.7.3)
  Downloading qudida-0.0.4-py3-none-any.whl (3.5 kB)
Requirement already satisfied: opencv-python-headless>=4.1.1 in d:\stablediff\data\packages\stable-diffusion-webui\venv\lib\site-packages (from albumentations->insightface==0.7.3) (4.8.0.76)
Requirement already satisfied: networkx>=2.8 in d:\stablediff\data\packages\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (3.1)
Requirement already satisfied: imageio>=2.27 in d:\stablediff\data\packages\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (2.31.2)
Requirement already satisfied: tifffile>=2022.8.12 in d:\stablediff\data\packages\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (2023.8.30)
Requirement already satisfied: PyWavelets>=1.1.1 in d:\stablediff\data\packages\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (1.4.1)
Requirement already satisfied: packaging>=21 in d:\stablediff\data\packages\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (23.1)
Requirement already satisfied: lazy_loader>=0.2 in d:\stablediff\data\packages\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (0.3)
Requirement already satisfied: contourpy>=1.0.1 in d:\stablediff\data\packages\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (1.1.0)
Requirement already satisfied: cycler>=0.10 in d:\stablediff\data\packages\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in d:\stablediff\data\packages\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (4.42.1)
Requirement already satisfied: kiwisolver>=1.0.1 in d:\stablediff\data\packages\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (1.4.5)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in d:\stablediff\data\packages\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in d:\stablediff\data\packages\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (2.8.2)
Requirement already satisfied: protobuf>=3.20.2 in d:\stablediff\data\packages\stable-diffusion-webui\venv\lib\site-packages (from onnx->insightface==0.7.3) (3.20.3)
Requirement already satisfied: typing-extensions>=3.6.2.1 in d:\stablediff\data\packages\stable-diffusion-webui\venv\lib\site-packages (from onnx->insightface==0.7.3) (4.7.1)
Requirement already satisfied: wcwidth in d:\stablediff\data\packages\stable-diffusion-webui\venv\lib\site-packages (from prettytable->insightface==0.7.3) (0.2.6)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\stablediff\data\packages\stable-diffusion-webui\venv\lib\site-packages (from requests->insightface==0.7.3) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in d:\stablediff\data\packages\stable-diffusion-webui\venv\lib\site-packages (from requests->insightface==0.7.3) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\stablediff\data\packages\stable-diffusion-webui\venv\lib\site-packages (from requests->insightface==0.7.3) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in d:\stablediff\data\packages\stable-diffusion-webui\venv\lib\site-packages (from requests->insightface==0.7.3) (2023.7.22)
Collecting joblib>=1.1.1 (from scikit-learn->insightface==0.7.3)
  Obtaining dependency information for joblib>=1.1.1 from https://files.pythonhosted.org/packages/10/40/d551139c85db202f1f384ba8bcf96aca2f329440a844f924c8a0040b6d02/joblib-1.3.2-py3-none-any.whl.metadata
  Downloading joblib-1.3.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=2.0.0 (from scikit-learn->insightface==0.7.3)
  Obtaining dependency information for threadpoolctl>=2.0.0 from https://files.pythonhosted.org/packages/81/12/fd4dea011af9d69e1cad05c75f3f7202cdcbeac9b712eea58ca779a72865/threadpoolctl-3.2.0-py3-none-any.whl.metadata
  Downloading threadpoolctl-3.2.0-py3-none-any.whl.metadata (10.0 kB)
Requirement already satisfied: colorama in d:\stablediff\data\packages\stable-diffusion-webui\venv\lib\site-packages (from tqdm->insightface==0.7.3) (0.4.6)
Requirement already satisfied: six>=1.5 in d:\stablediff\data\packages\stable-diffusion-webui\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib->insightface==0.7.3) (1.16.0)
Downloading albumentations-1.3.1-py3-none-any.whl (125 kB)
   ---------------------------------------- 125.7/125.7 kB ? eta 0:00:00
Downloading prettytable-3.8.0-py3-none-any.whl (27 kB)
Downloading scikit_learn-1.3.0-cp310-cp310-win_amd64.whl (9.2 MB)
   ---------------------------------------- 9.2/9.2 MB 29.5 MB/s eta 0:00:00
Downloading joblib-1.3.2-py3-none-any.whl (302 kB)
   --------------------------------------- 302.2/302.2 kB 18.2 MB/s eta 0:00:00
Downloading threadpoolctl-3.2.0-py3-none-any.whl (15 kB)
Building wheels for collected packages: insightface, easydict
  Building wheel for insightface (pyproject.toml): started
  Building wheel for insightface (pyproject.toml): finished with status 'error'
  Building wheel for easydict (setup.py): started
  Building wheel for easydict (setup.py): finished with status 'done'
  Created wheel for easydict: filename=easydict-1.10-py3-none-any.whl size=6515 sha256=c2cf422fed5084d9d5452ea5ff9052783ccf9bc877f2d1fddac2ba2e834ba8f7
  Stored in directory: D:\All-Temps\pip-ephem-wheel-cache-yfdaax11\wheels\b7\e3\8c\f814820ac7ef5fd96f38759ce0d3dc51166a3169008b31da53
Successfully built easydict
Failed to build insightface

--- PLEASE, RESTART the Server! ---
Launching Web UI with arguments: --xformers --api --skip-python-version-check
D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\torchaudio\backend\utils.py:74: UserWarning: No audio backend is available.
  warnings.warn("No audio backend is available.")
2023-09-01 02:22:18,063 - ControlNet - INFO - ControlNet v1.1.313
ControlNet preprocessor location: D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-09-01 02:22:18,359 - ControlNet - INFO - ControlNet v1.1.313
*** Error loading script: console_log_patch.py
    Traceback (most recent call last):
      File "D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 4, in <module>
02:22:24 - ReActor -         import insightface
    ModuleNotFoundError: No module named 'insightface'
STATUS
---
 - Running v0.4.1-b4
*** Error loading script: reactor_api.py
    Traceback (most recent call last):
      File "D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_api.py", line 17, in <module>
        from scripts.reactor_swapper import UpscaleOptions, swap_face
      File "D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 10, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_faceswap.py
    Traceback (most recent call last):
      File "D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 20, in <module>
        from scripts.reactor_swapper import UpscaleOptions, swap_face, check_process_halt, reset_messaged
      File "D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 10, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_swapper.py
    Traceback (most recent call last):
      File "D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 10, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
Loading weights [fc5d2229a1] from D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\models\Stable-diffusion\onlyrealistic_v29BakedVAE.safetensors
Civitai Shortcut: v1.6.4
Civitai Shortcut: There are no registered shortcuts.
Civitai Shortcut: There are no registered shortcuts.
Civitai Shortcut: There are no registered shortcuts.
Civitai Shortcut: There are no registered shortcuts.
Creating model from config: D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\configs\v1-inference.yaml
2023-09-01 02:22:28,565 - ControlNetFastload - INFO - Load Controlnet Fastload Filter on isRemote=None and accessLevel=2
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 127.5s (prepare environment: 83.9s, import torch: 13.6s, import gradio: 4.1s, setup paths: 3.6s, initialize shared: 0.8s, other imports: 2.8s, setup codeformer: 0.6s, setup gfpgan: 0.1s, list SD models: 0.3s, load scripts: 12.8s, create ui: 3.5s, gradio launch: 1.1s, add APIs: 0.2s).
Applying attention optimization: xformers... done.
Model loaded in 13.2s (load weights from disk: 1.3s, load config: 0.4s, create model: 1.5s, apply weights to model: 6.7s, move model to device: 0.2s, load textual inversion embeddings: 1.7s, calculate empty prompt: 1.4s).

Help would be greatly appreciated.

Thanks !

**Comment by Gourieff** [comment]
To successfully build Insightface package - you must have VS 2022 or VS C++ Build Tools in your OS
If you don't have one of them and don't want to install them - please, read Sec.VIII of [troubleshooting](https://github.com/Gourieff/sd-webui-reactor#troubleshooting)

**Comment by Codename-11** [comment]
I have tried both VS 2022 with Desktop C++ selected and VS C++ Build Tools, both times rebooting between tests, still failing to build insightface with logs the same as OP. :(

**Comment by TreemanJF** [comment]
Same issue. But I have VS 2022 installed

**Comment by drdancm** [comment]
I opened this issue, but solved it with #VIII and have not had any problems ever since. Creator installs all the updates and has gotten better and better with each update.

**Comment by nothingness6** [comment]
> I opened this issue, but solved it with #VIII and have not had any problems ever since. Creator installs all the updates and has gotten better and better with each update.

Hi, I also have the same issue. Could you explain how you solved it? What is #VIII?

**Comment by drdancm** [comment]
#VIII refers to the Reactor Troubleshooting Install solution that spells out how to get insightface:

VIII. (For Windows users) If you still cannot build Insightface for some reasons or just don't want to install Visual Studio or VS C++ Build Tools - do the following:

    Close (stop) your SD WebUI Server if it's running
    Download and put [prebuilt Insightface package](https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp310-cp310-win_amd64.whl) into the stable-diffusion-webui (or SD.Next) root folder where you have "webui-user.bat" file or (A1111 Portable) "run.bat"
    From stable-diffusion-webui (or SD.Next) root folder run CMD and .\venv\Scripts\activate
    OR
    (A1111 Portable) Run CMD
    Then update your PIP: python -m pip install -U pip
    OR
    (A1111 Portable)system\python\python.exe -m pip install -U pip
    Then install Insightface: pip install insightface-0.7.3-cp310-cp310-win_amd64.whl
    OR
    (A1111 Portable)system\python\python.exe -m pip install insightface-0.7.3-cp310-cp310-win_amd64.whl
    Enjoy!

It's from the ReadMe (scroll down until you get to VIII:
https://github.com/Gourieff/sd-webui-reactor?tab=readme-ov-file#readme

**Comment by nothingness6** [comment]
> #VIII refers to the Reactor Troubleshooting Install solution that spells out how to get insightface:
> 
> VIII. (For Windows users) If you still cannot build Insightface for some reasons or just don't want to install Visual Studio or VS C++ Build Tools - do the following:
> 
> ```
> Close (stop) your SD WebUI Server if it's running
> Download and put [prebuilt Insightface package](https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp310-cp310-win_amd64.whl) into the stable-diffusion-webui (or SD.Next) root folder where you have "webui-user.bat" file or (A1111 Portable) "run.bat"
> From stable-diffusion-webui (or SD.Next) root folder run CMD and .\venv\Scripts\activate
> OR
> (A1111 Portable) Run CMD
> Then update your PIP: python -m pip install -U pip
> OR
> (A1111 Portable)system\python\python.exe -m pip install -U pip
> Then install Insightface: pip install insightface-0.7.3-cp310-cp310-win_amd64.whl
> OR
> (A1111 Portable)system\python\python.exe -m pip install insightface-0.7.3-cp310-cp310-win_amd64.whl
> Enjoy!
> ```
> 
> It's from the ReadMe (scroll down until you get to VIII: https://github.com/Gourieff/sd-webui-reactor?tab=readme-ov-file#readme

I already tried it, but it didn't help.

**Comment by stanica** [comment]
Also struggling to install this in Stability Matrix. Followed all the instructions multiple times and it fails to import or build.

**Comment by richardm1** [comment]
The instructions from [comfyui-reactor-node](https://github.com/Gourieff/comfyui-reactor-node?tab=readme-ov-file#insightfacebuild) appear to assume a standard ComfyUI portable installation with its own Python sitting in python_embedded.  Stability Matrix users don't have this apparently.

I've followed their instructions but placing **insightface-0.7.3-cp310-cp310-win_amd64.whl** into Data\Assets\Python310.

```python.exe -m pip install insightface-0.7.3-cp310-cp310-win_amd64.whl``` succeeded but the ReActor install continues to fail.

I ran Procmon64 during the attempt and captured 9 NAME NOT FOUND events for Python.h at:

```
C:\Users\<username>\AppData\Local\Temp\pip-build-env-dfsosiez\overlay\Lib\site-packages\Cython\Includes\cpython\Python.h
C:\Users\<username>\AppData\Local\Temp\pip-install-zmhih83t\insightface_c96934e302d347ca8aef08b22212b61a\insightface\thirdparty\face3d\mesh\cython\Python.h
C:\Users\<username>\AppData\Local\Temp\pip-install-zmhih83t\insightface_c96934e302d347ca8aef08b22212b61a\Python.h\AppData\Local\Temp\pip-install-zmhih83t\insightface_c96934e302d347ca8aef08b22212b61a\Python.h
```

I'm stuck.  I don't know what's needed where...

**Comment by ArctiXArts** [comment]
I know this is an old thread - but for anyone having this issue while using StabilityMatrix , you need to follow the reactor troubleshooting to install the dependencies then you have to install the wheel in Packages\ComfyUI\venv\Scripts folder using THAT version of python.

Drop the wheel in the comfyui\venv\scripts folder and run the PIP install from that folder. 

StabilityMatrix\Data\Packages\ComfyUI\venv\Scripts\python.exe -m pip install \StabilityMatrix\Data\Packages\ComfyUI\venv\Scripts\insightface-0.7.3-cp310-cp310-win_amd64.whl
