### ISSUE TITLE
No source face(s) found

### ISSUE THREAD

**Issue by cheremo** [Gourieff/sd-webui-reactor#83]
Hey,

im gettin' the error "no source faces found". I've tryed some source images, but the error is always the same. Any idea?
im using https://github.com/lshqqytiger/stable-diffusion-webui-directml (amd gpu)

![Screenshot 2023-09-02 164341](https://github.com/Gourieff/sd-webui-reactor/assets/29504798/23f515b8-f762-4b54-aafe-3de8b2b319ce)
![Screenshot 2023-09-02 164650](https://github.com/Gourieff/sd-webui-reactor/assets/29504798/6890fbd2-4167-4bba-b6a6-7ba32071d9da)

konfig of the webUI

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--medvram --precision full --no-half --no-half-vae --opt-split-attention --opt-sub-quad-attention --disable-nan-check
set SAFETENSORS_FAST_GPU=1
git pull
call webui.bat

**Comment by Gourieff** [comment]
If you have 1 face on both images (source and target) - you must set 0 to "face index" parameters
0 - is the first element of index in this case

**Comment by Gourieff** [comment]
And what about the error above (list index out of range) - I will fix it, it shouldn't have showed any errors if no face found with any selected gender

**Comment by cheremo** [comment]
thanks, case closed :) Love your plugin!

**Comment by cheremo** [comment]
thanks, case closed :) Love your plugin!
