### ISSUE TITLE
[SOLVED] the face does not appear on the generated picture

### ISSUE THREAD

**Issue by kirstarkov** [Gourieff/sd-webui-reactor#84]
I generate an image, I attach a photo that I want to overlay on the generated image, however after clicking "generate", I just get a new image. What's my mistake? help me please
![image](https://github.com/Gourieff/sd-webui-reactor/assets/143908962/3870cea7-3164-47e2-adf4-20be1c999dd2)

**Comment by Gourieff** [comment]
Show please a console log

**Comment by kirstarkov** [comment]
> 

I see the error now, but I dont understand, what does it mean)

![image](https://github.com/Gourieff/sd-webui-reactor/assets/143908962/20582c4b-ee4a-4556-971d-7aa9990d43df)

**Comment by Gourieff** [comment]
Please try this solution https://github.com/Gourieff/sd-webui-reactor#v-invalid_protobuf--load-model-from-modelsinsightfaceinswapper_128onnx-failedprotobuf-parsing-failed

**Comment by kirstarkov** [comment]
> Please try this solution https://github.com/Gourieff/sd-webui-reactor#v-invalid_protobuf--load-model-from-modelsinsightfaceinswapper_128onnx-failedprotobuf-parsing-failed

Thank you so much! It worked!
