### ISSUE TITLE
[SOLVED] return [value for _, value in self.choices].index(x) ValueError: ['No', 'No'] is not in list

### ISSUE THREAD

**Issue by MattRM2** [Gourieff/sd-webui-reactor#88]
Hi,

I installed the extension this morning and I got this error : 

`Traceback (most recent call last):
  File "E:\00_Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\00_Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1429, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "E:\00_Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1239, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "E:\00_Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\components\radio.py", line 170, in preprocess
    return [value for _, value in self.choices].index(x)
ValueError: ['No', 'No'] is not in list`

Do you have an idea how to fix it ? thx

Matt

**Comment by Gourieff** [comment]
Hi Matt

I think, your A1111 have been updated to 1.6 version (with a lot of dependencies, including Gradio)
Just close the sd-webui server, restart your system and try to start A1111 again, it's not the ReActor's fault

It's quite a common issue after major updates https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/5607

**Comment by MattRM2** [comment]
> Hi Matt
> 
> I think, your A1111 have been updated to 1.6 version (with a lot of dependencies, including Gradio) Just close the sd-webui server, restart your system and try to start A1111 again, it's not the ReActor's fault
> 
> It's quite a common issue after major updates [AUTOMATIC1111/stable-diffusion-webui#5607](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/5607)

Hi Gourieff,

Yes, found the problem with the Gradio dependencies, I fixed it and now working great, thank you. I saw the problem only in the Reactor panel but after I saw it in img2img on others extensions.

Thx for your reply, it works good now and sorry for the post here as it was A1111 problem.
Have a nice day,

Matt
