### ISSUE TITLE
Slow when faces are not detected

### ISSUE THREAD

**Issue by Dutch77** [Gourieff/sd-webui-reactor#95]
Hi, first of all thanks for this extension, it's super useful for me.

My use case. I'm taking photo of actual people and then running them through api of controlNet + api of your face swap. Idk how many people are gonna be on the picture, so I add in both fields sourceFaceIndex and targetFaceIndex `0,1,2,3,4,5,6,7,8,9` so I can swap up to ten people.

What I have noticed is extension reports in logs that faces are not there which is fine but it takes like a 1+ second on each face that is not there and speed of img generation is crucial for me.

Proposal
Detect number of faces on source image and target image and don't try to make face swap if it doesn't make sense. There could be probably an option where you can check `automatic` and it will swap people in same order.

Are you interested in pull requests? I probably can help with that. Thx

**Comment by Dutch77** [comment]
The biggest pain is this:
https://github.com/Gourieff/sd-webui-reactor/blob/main/scripts/reactor_swapper.py#L200

Face analyzer is run again on the same photo with each face which adds time cost linearly. There is no need to calculate it again every time. Just cache the output of analyser somewhere and pass it as parameter. Or fix it properly by making another method like `get_face_multiple`. @Gourieff

**Comment by Gourieff** [comment]
> The biggest pain is this: https://github.com/Gourieff/sd-webui-reactor/blob/main/scripts/reactor_swapper.py#L200
> 
> Face analyzer is run again on the same photo with each face which adds time cost linearly. There is no need to calculate it again every time. Just cache the output of analyser somewhere and pass it as parameter. Or fix it properly by making another method like `get_face_multiple`. @Gourieff

Yes, you're right, there is no need to analyze the same face again and again if no changes in source
I will fix this moment in one of the next updates

**Comment by Gourieff** [comment]
> The biggest pain is this: https://github.com/Gourieff/sd-webui-reactor/blob/main/scripts/reactor_swapper.py#L200
> 
> Face analyzer is run again on the same photo with each face which adds time cost linearly. There is no need to calculate it again every time. Just cache the output of analyser somewhere and pass it as parameter. Or fix it properly by making another method like `get_face_multiple`. @Gourieff

Hi! 
Yes, you're right, there is no need to analyze the same face again and again if no changes in the source
I will fix this moment in one of the next updates

> Hi, first of all thanks for this extension, it's super useful for me.
> 
> My use case. I'm taking photo of actual people and then running them through api of controlNet + api of your face swap. Idk how many people are gonna be on the picture, so I add in both fields sourceFaceIndex and targetFaceIndex `0,1,2,3,4,5,6,7,8,9` so I can swap up to ten people.
> 
> What I have noticed is extension reports in logs that faces are not there which is fine but it takes like a 1+ second on each face that is not there and speed of img generation is crucial for me.
> 
> Proposal Detect number of faces on source image and target image and don't try to make face swap if it doesn't make sense. There could be probably an option where you can check `automatic` and it will swap people in same order.
> 
> Are you interested in pull requests? I probably can help with that. Thx

Yeah, I have in plans to implement smth like an auto-mode to set faces indexes automatically
If you have time for PR, so welcome, I'll be glad

**Comment by Gourieff** [comment]
@Dutch77 yeah, thanks for the PR, I will test it on the next week
Working on another project right now

**Comment by Gourieff** [comment]
So, this is the result of the test https://github.com/Gourieff/sd-webui-reactor/pull/110#issuecomment-1743670708

**Comment by Dutch77** [comment]
I believe you tested it on wrong data. See comment https://github.com/Gourieff/sd-webui-reactor/pull/110#issuecomment-1744740224

**Comment by Gourieff** [comment]
Closing this Issue and closing PR ( more info https://github.com/Gourieff/sd-webui-reactor/pull/110#issuecomment-1748717614 )
I added you as the Contributor for 0.4.2 version https://github.com/Gourieff/sd-webui-reactor/releases/tag/v0.4.2 and for the latest commit https://github.com/Gourieff/sd-webui-reactor/commit/077862376e8fb76757d9a00a6f6e241b24c3f712
Thanks a lot for showing this Issue and for pointing out the flaws in the code logic of the faces analyzing process
