### ISSUE TITLE
Reactor v0.4.2.b1

### ISSUE THREAD

**Issue by masacimace** [Gourieff/sd-webui-reactor#97]
after updating to the latest version, i always get this error on console : 
**ReActor - ERROR - Age Detection: No face with index = 0 was found**
**ReActor - ERROR - Gender Detection: No face with index = 0 was found**

https://i.postimg.cc/bJWSGhMy/Screenshot-1.png

**Comment by Gourieff** [comment]
Hm... Could you provide the workflow you use?
