### ISSUE TITLE
[Feature]: How to friend FaceSwapLab and Reactor on one automation?

### ISSUE THREAD

**Issue by mikheys** [Gourieff/sd-webui-reactor#99]
### Feature description

Good afternoon. Can you please tell me how to friend FaceSwapLab and Reactor on one automation?

![image](https://github.com/Gourieff/sd-webui-reactor/assets/34010273/4200b773-637f-4b15-b059-bf463fb9b09e)

**Comment by Gourieff** [comment]
Hello there!

You can try the following:
1. Delete FaceSwapLab from the extensions folder
2. Delete onnxruntime and onnxruntime-gpu folders from the site-packages (inside VENV Lib)
3. Run SD WebUI and let ReActor to install onnxruntime, close SD WebUI
4. `git clone https://github.com/glucauze/sd-webui-faceswaplab` into the SD WebUI extensions folder
5. Edit [sd-webui-faceswaplab/install.py](https://github.com/glucauze/sd-webui-faceswaplab/blob/main/install.py) file:
    - Line 9: `use_gpu = True` -> `use_gpu = False`
6. Run SD WebUI, both extensions must work fine after that

![изображение](https://github.com/Gourieff/sd-webui-reactor/assets/85128026/e99080e9-6f93-4648-9432-fed129a5efb6)

![изображение](https://github.com/Gourieff/sd-webui-reactor/assets/85128026/88e7ab07-e1be-4166-ad2f-23c5d8db72c0)

**Comment by Gourieff** [comment]
You can also use another version of ReActor called [ReActor Force](https://github.com/Gourieff/sd-webui-reactor-force), it supports NVIDIA GPU acceleration and it's friendly to any extension using ORT-GPU
